// Independent source hierarchy and dense first-contact sampling. Does not use
// BossPose math, its generated constants, or renderer adapter transformations.
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createRequire}from'node:module';import assert from'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),require=createRequire(path.join(root,'tools/asset-viewer/package.json')),T=require('three');
const bytes=fs.readFileSync(path.join(root,'delivery/playable/forge-tyrant.glb')),length=bytes.readUInt32LE(12),j=JSON.parse(bytes.subarray(20,20+length)),bin=bytes.subarray(28+length);
const nodes=j.nodes.map(n=>{const o=new T.Group();o.name=n.name??'';if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.mesh!==undefined)for(const p of j.meshes[n.mesh].primitives){const a=j.accessors[p.attributes.POSITION],v=j.bufferViews[a.bufferView],offset=(v.byteOffset??0)+(a.byteOffset??0),stride=v.byteStride??12,points=new Float32Array(a.count*3);for(let i=0;i<a.count;i++)for(let k=0;k<3;k++)points[3*i+k]=bin.readFloatLE(offset+i*stride+4*k);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(points,3));g.computeBoundingBox();o.add(new T.Mesh(g));}return o;});
for(let i=0;i<nodes.length;i++)for(const child of j.nodes[i].children??[])nodes[i].add(nodes[child]);
const actor=new T.Group(),model=new T.Group();actor.scale.setScalar(1.4);model.rotation.y=Math.PI;actor.add(model);for(const n of j.scenes[j.scene??0].nodes)model.add(nodes[n]);actor.updateMatrixWorld(true);
const names=['Barrel_L','Barrel_R','Pod_L','Pod_R','Leg_L','Knee_L','Foot_L','Leg_R','Knee_R','Foot_R','Torso'];
const core=JSON.parse(fs.readFileSync(path.join(root,'builds/boss-core-luminous-measurement.json'),'utf8'));
const components=names.map((name,i)=>{const node=model.getObjectByName(name);if(i===10)return{node,center:new T.Vector3(...core.localCenter),half:new T.Vector3(...core.localHalf)};const mesh=model.getObjectByName(name+'_MobileMesh'),box=new T.Box3().setFromObject(mesh,true).applyMatrix4(node.matrixWorld.clone().invert());return{node,center:box.getCenter(new T.Vector3()),half:box.getSize(new T.Vector3()).multiplyScalar(.5)};});
const cases=JSON.parse(fs.readFileSync(path.join(root,process.argv[2]??'builds/boss-pose-contact-samples.json'),'utf8'));
function pose(a,b,t){const p=a.map((v,i)=>i<3||i===16?v+(b[i]-v)*t:v+Math.atan2(Math.sin(b[i]-v),Math.cos(b[i]-v))*t);actor.position.fromArray(p);actor.rotation.set(p[3],p[4],p[5]);for(let i=0;i<2;i++){const side=i?'R':'L';model.getObjectByName('Arm_'+side).rotation.set(p[6+i],0,p[8+i]);model.getObjectByName('Leg_'+side).rotation.x=p[10+i];model.getObjectByName('Knee_'+side).rotation.x=p[12+i];model.getObjectByName('Barrel_'+side).rotation.z=p[14+i];}actor.updateMatrixWorld(true);}
function ellipsoidOutsideDistance(p,r){if((p.x/r.x)**2+(p.y/r.y)**2+(p.z/r.z)**2<=1)return 0;const a=p.toArray().map(Math.abs),rr=r.toArray().map(x=>x*x);let lo=0,hi=Math.max(r.x,r.y,r.z)*p.length(),lambda=hi*.5;
 for(let i=0;i<30;i++){let f=-1,df=0;for(let k=0;k<3;k++){const d=lambda+rr[k],u=rr[k]*a[k]*a[k]/(d*d);f+=u;df-=2*u/d;}if(f>0)lo=lambda;else hi=lambda;const next=lambda-f/df;lambda=Number.isFinite(next)&&next>lo&&next<hi?next:(lo+hi)*.5;}
 return Math.sqrt(a.reduce((sum,v,k)=>sum+(v-rr[k]*v/(lambda+rr[k]))**2,0));}
const point=new T.Vector3(),local=new T.Vector3(),box=new T.Box3(),inner=new T.Vector3();
function distance(world,i){const c=components[i];local.copy(world);c.node.worldToLocal(local);local.sub(c.center);if(i===10)return ellipsoidOutsideDistance(local,c.half)*1.4;
 const rounding=Math.min(.04/1.4,c.half.x*.25,c.half.y*.25,c.half.z*.25);inner.copy(c.half).addScalar(-rounding);box.setFromCenterAndSize(new T.Vector3(),inner.clone().multiplyScalar(2));const outside=box.distanceToPoint(local),inside=Math.min(0,Math.max(Math.abs(local.x)-inner.x,Math.abs(local.y)-inner.y,Math.abs(local.z)-inner.z));return(outside+inside-rounding)*1.4;}
function collision(c,t){pose(c.previous,c.current,t);point.fromArray(c.start).lerp(new T.Vector3(...c.end),t);let first=-1;for(let i=0;i<11;i++){const region=i<4?i:i<7?4:i<10?5:6;if(region<6&&((c.mask??0)&(1<<region)))continue;if(distance(point,i)<=c.radius+(i===10?.01:0)+(c.numericalTolerance??0)){first=i;break;}}return first;}
let hits=0,misses=0,unresolved=0,maxFractionError=0,maxSurfaceError=0;
for(const c of cases){let previous=0,found=-1,t=0;for(let step=0;step<=2048;step++){t=step/2048;found=collision(c,t);if(found>=0)break;previous=t;}
 if(found>=0){let lo=previous,hi=t;for(let i=0;i<25;i++){const m=(lo+hi)*.5;if(collision(c,m)>=0)hi=m;else lo=m;}t=hi;found=collision(c,t);}
 if(c.status===0){hits++;assert(found>=0,'compiled hit has no independently sampled physical contact');const error=Math.abs(c.fraction-t);maxFractionError=Math.max(maxFractionError,error);assert(error<.002,`earliest contact error ${error}`);pose(c.previous,c.current,c.fraction);point.fromArray(c.point);let surfaceError;
  if(c.component===10){const q=components[10];q.node.worldToLocal(point);point.sub(q.center);surfaceError=Math.abs((point.x/q.half.x)**2+(point.y/q.half.y)**2+(point.z/q.half.z)**2-1)*Math.max(...q.half.toArray())*1.4;}else surfaceError=Math.abs(distance(point,c.component));maxSurfaceError=Math.max(maxSurfaceError,surfaceError);assert(surfaceError<1e-7,`impact is not on actual source-aligned surface ${surfaceError}`);
 }else if(c.status===1){misses++;assert.equal(found,-1,'compiled miss hides an independently sampled collision');}else if(c.status===2)unresolved++;else assert.fail('unexpected invalid audit contact');}
const report={scope:'Independent Three.js raw retained GLB hierarchy; dense2048 time samples plus25 bisections; rounded source part volumes and measured luminous ellipsoid; no gameplay/device claim',cases:cases.length,hits,misses,unresolved,numericalAcceptanceToleranceMetres:Math.max(0,...cases.map(c=>c.numericalTolerance??0)),coreToleranceMetres:.01,maxFractionError,maxSurfaceErrorMetres:maxSurfaceError,timestamp:new Date().toISOString()};fs.writeFileSync(path.join(root,process.argv[3]??'builds/boss-pose-contact-oracle.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
