export type Phase='ready'|'run'|'boss'|'destroying'|'won'|'lost'|'lastStand'|'reward'|'reviving';
export type Relic=0|1|2;
export type WeaponPower='none'|'guided'|'cannons'|'railburst'|'escort';
export type CombatPower='none'|'tempest'|'arcstorm'|'salvo';
export type TimePower='none'|'freeze'|'slow'|'haste';
export type PickupPower=Exclude<WeaponPower|'freeze'|'slow'|'haste'|CombatPower|'health','none'>;
export type BossState='armored'|'exposed'|'rebuilding'|'destroying'|'guarded';
export interface Pickup {id:number;kind:PickupPower;x:number;z:number;radius:number;choiceGroup:number;bonusTroops:number;}
export interface Target {archetype?:number;shieldHp?:number;shieldMax?:number;blockFlash?:number;skillState?:number;id:number;kind:'enemy'|'crate'|'gate'|'hazard'|'orb';x:number;z:number;hp:number;maxHp:number;value:number;op:number;size:number;depth:number;hit:number;variant:number;fireState:'idle'|'tracking'|'locked'|'fire'|'reload';aimX:number;charge:number;role:'grunt'|'elite'|'gunner'|'battery'|'carrier';guidedArmor:boolean;stunTime:number;ventOpen:boolean;ventTime:number;}
export type BossRegionId='cannonL'|'cannonR'|'jetL'|'jetR'|'legL'|'legR'|'core';
export interface BossPose {rootX:number;rootY:number;worldZ:number;pitch:number;yaw:number;roll:number;arm:{pitch:number;roll:number}[];leg:number[];knee:number[];barrel:number[];poseClock:number;}
export interface BossRegion {id:BossRegionId;x:number;y:number;z:number;radiusX:number;radiusY:number;radiusZ:number;quaternion:[number,number,number,number];hp:number;maxHp:number;vulnerable:boolean;active:boolean;}
export interface BossComponent {componentIndex:number;regionId:BossRegionId;x:number;y:number;z:number;radiusX:number;radiusY:number;radiusZ:number;quaternion:[number,number,number,number];shape:'roundedBox'|'ellipsoid';active:boolean;}
export interface Shot {id:number;y?:number;dy?:number;aimRegion?:BossRegionId;epoch?:number;x:number;z:number;dx:number;dz:number;heavy:boolean;kind:'pulse'|'arc'|'rail'|'missile'|'cannon'|'salvo';owner:'commander'|'troop';}
export interface EnemyShot {id:number;x:number;z:number;dx:number;dz:number;radius:number;kind:'shell'|'rocket'|'orb';guided:boolean;homingTime:number;sourceId:number;emitter:'gunner'|'armL'|'armR'|'shoulderL'|'shoulderR'|'core';launchX:number;launchZ:number;launchY:number;}
export interface Effect {endX?:number;endY?:number;endZ?:number;y?:number;hitRegion?:BossRegionId;id:number;kind:'hit'|'kill'|'recruit'|'gate'|'damage'|'relic'|'bossShot'|'win'|'contact'|'block'|'bossDeath'|'missed'|'drop'|'pickup'|'pass'|'retreat'|'bossPhase'|'commanderHit'|'commanderDeath'|'hazardBreak'|'troopDeath'|'coreExpose'|'bossRevive'|'bossPartBreak'|'troopSacrifice'|'heal'|'revive'|'commanderDown'|'enemyFire'|'empPulse'|'empClear'|'empStun'|'shieldHit'|'escortBlock'|'combatPower'|'chainHit'|'shieldBreak'|'healthPickup'|'rewardChosen'|'clashStart'|'clashWin'|'clashLose'|'enemySupport'|'actStart';x:number;z:number;value:number;entityId:number;variant:number;size:number;}
export type BossAction='strafe'|'advance'|'retreat'|'windup'|'fire'|'dying'|'evade';
export interface Laser {y?:number;endY?:number;id:number;x:number;z:number;endX:number;endZ:number;width:number;time:number;}
export interface FormationUnit {index:number;x:number;z:number;}
export interface FriendlyBeam {id:number;x:number;y:number;z:number;endX:number;endY:number;endZ:number;width:number;time:number;}
export interface Snapshot {campaign?:boolean;actIndex?:number;stageLevel?:number;actProgress?:number;relics?:{energy:number;activeTime:number}[];laserCharges?:number;laserMeter?:number;ventTime?:number;reviveCinematicTime?:number;rewardPending?:boolean;rewardBonuses?:{laser:number;vitality:number;endurance:number};clash?:{active:boolean;progress:number;time:number;x:number;y:number;z:number;heroX:number;heroY:number;heroZ:number;enemyX:number;enemyY:number;enemyZ:number;result:'none'|'won'|'lost'};combatPower:CombatPower;combatPowerTime:number;friendlyBeams:FriendlyBeam[];bossEvadeTime:number;bossEvadeTell:number;bossFiringWindow:number;bossPose?:BossPose;bossRegions:BossRegion[];bossComponents:BossComponent[];guardHp:number;guardMax:number;bossEpoch:number;sweepUnresolved:number;phase:Phase;time:number;duration:number;level:number;levelName:string;rank:number;rankReward:number;weaponPower:WeaponPower;starterWeapon:WeaponPower;weaponPermanent:boolean;powerTime:number;timePower:TimePower;timePowerTime:number;x:number;army:number;commanderHp:number;commanderMaxHp:number;canHeal:boolean;healCost:number;healAmount:number;healUsesRemaining:number;reviveAvailable:boolean;reviveCost:number;reviveHp:number;reviveUsed:boolean;reviveProtection:number;empPulseTime:number;empStunTime:number;escortShield:number;escortMax:number;safetyAdmitted:number;safetyDeferred:number;safetyUnsupported:number;safetyExistingUnsafe:number;safetyCapacity:number;safetyAuthoredRockets:number;safetyHorizon:number;energy:number;ability:number;relic:Relic;weapon:number;weaponXP:number;weaponNeed:number;kills:number;bossHp:number;bossMax:number;bossArmor:number;bossArmorMax:number;bossCoreHp:number;bossCoreMax:number;bossCoreTime:number;bossState:BossState;bossRevives:number;bossAttack:number;bossLane:number;bossX:number;bossZ:number;bossY:number;bossPhase:1|2;bossPattern:'heavy'|'sweep'|'rockets'|'laser';bossPartsMask:number;bossPart:'cannon'|'jetpack'|'leg'|'reactor';bossPartHp:number;bossPartMax:number;bossAction:BossAction;deathProgress:number;travelDistance:number;travelGoal:number;engagement:boolean;frontline:number;score:number;formation:FormationUnit[];targets:Target[];shots:Shot[];enemyShots:EnemyShot[];lasers:Laser[];pickups:Pickup[];effects:Effect[];}
export interface GameCore {load():Promise<void>;start(relic:Relic,level?:number,rank?:number,legacy?:'laser'|'vitality'|'endurance'):void;step(dt:number,x:number):void;activate():boolean;activateRelic(relic:Relic):boolean;fireLaser():boolean;clashTap():boolean;chooseReward(choice:'laser'|'vitality'|'endurance'):boolean;heal():boolean;revive():boolean;declineRevive():boolean;pause(value:boolean):void;snapshot():Snapshot;}
