// Read-only exact retained troop geometry / camera projection audit.
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const root=process.cwd(),require=createRequire(path.resolve('tools/asset-viewer/package.json')),T=require('three');
const b=fs.readFileSync('delivery/playable/troop.glb'),n=b.readUInt32LE(12),j=JSON.parse(b.subarray(20,20+n)),bin=b.subarray(28+n);
const nodes=j.nodes.map(o=>{const node=new T.Object3D();if(o.translation)node.position.fromArray(o.translation);if(o.rotation)node.quaternion.fromArray(o.rotation);if(o.scale)node.scale.fromArray(o.scale);node.userData.mesh=o.mesh;return node;});for(let i=0;i<nodes.length;i++)for(const c of j.nodes[i].children??[])nodes[i].add(nodes[c]);const scene=new T.Group();for(const k of j.scenes[j.scene??0].nodes)scene.add(nodes[k]);scene.updateMatrixWorld(true);let mesh;scene.traverse(o=>{if(mesh===undefined&&o.userData.mesh!==undefined)mesh=o;});const prim=j.meshes[mesh.userData.mesh].primitives[0],a=j.accessors[prim.attributes.POSITION],v=j.bufferViews[a.bufferView],stride=v.byteStride??12,offset=(v.byteOffset??0)+(a.byteOffset??0),points=[];
for(let i=0;i<a.count;i++)points.push(new T.Vector3(bin.readFloatLE(offset+i*stride),bin.readFloatLE(offset+i*stride+4),bin.readFloatLE(offset+i*stride+8)).applyMatrix4(mesh.matrixWorld));
const camera=new T.PerspectiveCamera(30,.45,.1,180);const results=[];
for(const [w,h]of[[420,933],[412,915],[375,667],[352,782],[560,850]]){
 camera.aspect=w/h;camera.fov=30;camera.updateProjectionMatrix();const distance=(5.05/Math.min(.45,camera.aspect))/Math.tan(T.MathUtils.degToRad(15));let look=-9.3;const rearY=z=>{camera.position.set(0,distance*.58,z+distance*.815);camera.lookAt(0,.1,z);camera.updateMatrixWorld(true);return(1-new T.Vector3(0,0,3.39).project(camera).y)*h*.5;};if(rearY(look)>h-128){let lo=look,hi=0;for(let i=0;i<18;i++){const m=(lo+hi)/2;if(rearY(m)>h-128)lo=m;else hi=m;}look=hi;}rearY(look);
 for(const pulse of[false,true]){camera.fov=pulse?29.52:30;camera.updateProjectionMatrix();let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;const transform=new T.Matrix4().compose(new T.Vector3(3.9,.075,3.15),new T.Quaternion().setFromEuler(new T.Euler(0,Math.PI+.035,0)),new T.Vector3(.432,.72,.72));for(const p of points){const v=p.clone().applyMatrix4(transform).project(camera);minX=Math.min(minX,(1+v.x)*w/2);maxX=Math.max(maxX,(1+v.x)*w/2);minY=Math.min(minY,(1-v.y)*h/2);maxY=Math.max(maxY,(1-v.y)*h/2);}results.push({w,h,look,pulse,projected:{minX,maxX,minY,maxY},rightClippedPixels:Math.max(0,maxX-w)});}
}
const receipt={scope:'Read-only actual troop first-mesh vertices with world instancing scale/yaw, exact resize camera, max formation x3.9/rearZ3.15; no browser or runtime changes.',source:'delivery/playable/troop.glb',vertices:points.length,results};fs.writeFileSync('builds/portrait-troop-camera-measurement.json',JSON.stringify(receipt,null,2));if(process.argv[1]?.endsWith('measure_portrait_camera.mjs'))console.log(JSON.stringify(receipt,null,2));
export {points};
