// Read-only measurements of the retained original Iron Front GLB. Does not modify assets/gameplay.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),require=createRequire(path.resolve(here,'../asset-viewer/package.json')),T=require('three');
const bytes=fs.readFileSync(path.join(root,'delivery/playable/forge-tyrant.glb')),length=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+length)),binary=bytes.subarray(28+length);
const nodes=json.nodes.map(n=>{const o=new T.Group();o.name=n.name??'';if(n.mesh!==undefined)for(const p of json.meshes[n.mesh].primitives){const a=json.accessors[p.attributes.POSITION],v=json.bufferViews[a.bufferView],values=new Float32Array(a.count*3),stride=v.byteStride??12,offset=(v.byteOffset??0)+(a.byteOffset??0);for(let i=0;i<a.count;i++)for(let axis=0;axis<3;axis++)values[i*3+axis]=binary.readFloatLE(offset+i*stride+axis*4);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(values,3));g.computeBoundingBox();const mesh=new T.Mesh(g,new T.MeshBasicMaterial());mesh.name=o.name+'_Geometry';o.add(mesh);}if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);return o;});
for(let i=0;i<nodes.length;i++)for(const c of json.nodes[i].children??[])nodes[i].add(nodes[c]);const boss=new T.Group(),model=new T.Group();model.rotation.y=Math.PI;boss.scale.setScalar(1.4);boss.add(model);for(const n of json.scenes[json.scene??0].nodes)model.add(nodes[n]);
const definitions={cannonL:'Barrel_L',cannonR:'Barrel_R',jetL:'Pod_L',jetR:'Pod_R',legL:'Leg_L',legR:'Leg_R'};
const round=x=>Math.round(x*1e6)/1e6,vec=v=>v.toArray().map(round);
function measure(name){const node=boss.getObjectByName(name);boss.updateMatrixWorld(true);const box=new T.Box3().setFromObject(node,true);return{node:name,pivot:vec(node.getWorldPosition(new T.Vector3())),center:vec(box.getCenter(new T.Vector3())),min:vec(box.min),max:vec(box.max),halfSize:vec(box.getSize(new T.Vector3()).multiplyScalar(.5))};}
const neutral=Object.fromEntries(Object.entries(definitions).map(([id,name])=>[id,measure(name)]));
const envelopes=Object.fromEntries(Object.keys(definitions).map(id=>[id,{centerMin:new T.Vector3(Infinity,Infinity,Infinity),centerMax:new T.Vector3(-Infinity,-Infinity,-Infinity),bounds:new T.Box3(),maxCenterShift:0}]));
const original=new Map();model.traverse(n=>original.set(n,n.quaternion.clone()));let samples=0;
// These samples cover current render limits; not evidence the C++ currently owns this pose.
for(const pitch of [-.18,0,.18])for(const bank of [-.22,0,.22])for(const yaw of [-.32,0,.32])for(const armPitch of [-.3,-.20,.22,.35])for(const legSwing of [-.16,0,.16]){
 for(const [n,q] of original)n.quaternion.copy(q);boss.rotation.set(pitch,yaw,bank);
 for(const side of ['L','R']){boss.getObjectByName('Arm_'+side).rotation.x+=armPitch;boss.getObjectByName('Leg_'+side).rotation.x+=legSwing;boss.getObjectByName('Knee_'+side).rotation.x+=Math.max(0,legSwing)*.75;}
 for(const [id,name] of Object.entries(definitions)){const value=measure(name),e=envelopes[id],center=new T.Vector3(...value.center);e.centerMin.min(center);e.centerMax.max(center);e.bounds.union(new T.Box3(new T.Vector3(...value.min),new T.Vector3(...value.max)));e.maxCenterShift=Math.max(e.maxCenterShift,center.distanceTo(new T.Vector3(...neutral[id].center)));}samples++;
}
const poseEnvelope=Object.fromEntries(Object.entries(envelopes).map(([id,e])=>[id,{centerMin:vec(e.centerMin),centerMax:vec(e.centerMax),geometryMin:vec(e.bounds.min),geometryMax:vec(e.bounds.max),maxCenterShift:round(e.maxCenterShift)}]));
for(const [n,q] of original)n.quaternion.copy(q);boss.rotation.set(0,0,0);boss.updateMatrixWorld(true);
const bind=Object.fromEntries(['Torso','Arm_L','Arm_R','Barrel_L','Barrel_R','Pod_L','Pod_R','Leg_L','Leg_R','Knee_L','Knee_R','Foot_L','Foot_R'].map(name=>{const n=model.getObjectByName(name);return[name,{parent:n.parent?.name,translation:vec(n.position),quaternion:n.quaternion.toArray().map(round)}];}));
const result={source:'delivery/playable/forge-tyrant.glb',coordinateSystem:'metres; world X lateral, Y up, world Z toward commander; simulation Z is negative world Z; root offset excluded',scale:1.4,neutral,core:{anchor:[0,4.312,.847],recommendedDiskRadius:.47,note:'source furnace outer radius .31 before normalized model scale; exact visible glow measured separately from merged torso geometry'},poseEnvelope,samples,bind,note:'Measured actual mesh bounds and current cosmetic render limits. No gameplay hit regions or 3D friendly collision exist yet; wide swept pose envelopes are unsuitable as permanent hurtboxes.'};
fs.writeFileSync(path.join(root,'builds/boss-hit-region-measurements.json'),JSON.stringify(result,null,2));for(const [id,r] of Object.entries(neutral))console.log(id,'center',r.center,'halfSize',r.halfSize,'max cosmetic shift',poseEnvelope[id].maxCenterShift);console.log(samples+' bounded pose samples measured');
