// Original GLB is read only. Three.js independently supplies the bind/pose oracle.
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';import{createRequire}from'node:module';import{createHash}from'node:crypto';
import './measure_boss_core.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const require=createRequire(path.join(root,'tools/asset-viewer/package.json')),T=require('three');
const bytes=fs.readFileSync(path.join(root,'delivery/playable/forge-tyrant.glb')),length=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+length)),binary=bytes.subarray(28+length);
const names=['Root','Torso','Arm_L','Arm_R','Barrel_L','Barrel_R','Pod_L','Pod_R','Leg_L','Leg_R','Knee_L','Knee_R','Foot_L','Foot_R'];
const nodes=json.nodes.map(n=>{const o=new T.Group();o.name=n.name??'';if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);if(n.mesh!==undefined)for(const p of json.meshes[n.mesh].primitives){const a=json.accessors[p.attributes.POSITION],v=json.bufferViews[a.bufferView],stride=v.byteStride??12,offset=(v.byteOffset??0)+(a.byteOffset??0),values=new Float32Array(a.count*3);for(let i=0;i<a.count;i++)for(let axis=0;axis<3;axis++)values[i*3+axis]=binary.readFloatLE(offset+i*stride+axis*4);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(values,3));g.computeBoundingBox();const mesh=new T.Mesh(g);mesh.name=o.name+'_Geometry';o.add(mesh);}return o;});
for(let i=0;i<nodes.length;i++)for(const c of json.nodes[i].children??[])nodes[i].add(nodes[c]);
const actor=new T.Group(),model=new T.Group();actor.scale.setScalar(1.4);model.rotation.y=Math.PI;actor.add(model);for(const n of json.scenes[json.scene??0].nodes)model.add(nodes[n]);actor.updateMatrixWorld(true);
const joint=names.map(n=>model.getObjectByName(n));
for(const n of joint){if(!n)throw Error('Missing measured joint');if(n.quaternion.angleTo(new T.Quaternion())>1e-9)throw Error('Nonidentity bind quaternion needs explicit implementation');if(n.scale.distanceTo(new T.Vector3(1,1,1))>1e-9)throw Error('Nonunit bind scale');}
const binds=joint.map((n,i)=>({parent:i===0?-1:names.indexOf(n.parent.name),position:n.position.toArray()}));
const components=[['Barrel_L',0],['Barrel_R',1],['Pod_L',2],['Pod_R',3],['Leg_L',4],['Knee_L',4],['Foot_L',4],['Leg_R',5],['Knee_R',5],['Foot_R',5]];
const data=components.map(([name,region])=>{const n=model.getObjectByName(name),mesh=model.getObjectByName(name+'_MobileMesh');const box=new T.Box3().setFromObject(mesh,true).applyMatrix4(n.matrixWorld.clone().invert());return{joint:names.indexOf(name),region,center:box.getCenter(new T.Vector3()).toArray(),half:box.getSize(new T.Vector3()).multiplyScalar(.5).toArray(),name};});
const core=JSON.parse(fs.readFileSync(path.join(root,'builds/boss-core-luminous-measurement.json'),'utf8'));
const vec=v=>'{'+v.map(x=>Number(x).toPrecision(17)).join(',')+'}';
const header=`#pragma once\n// Measured from retained original GLB; generated by prepare_boss_pose_fixture.mjs.\n// SHA256 ${createHash('sha256').update(bytes).digest('hex')}\nnamespace mech::boss_pose::model_data {\nstruct Bind { int parent; Vec3 position; };\nstruct Component { int joint,region; Vec3 center,half; };\ninline constexpr std::array<Bind,14> Bindings{{\n${binds.map(b=>`{${b.parent},${vec(b.position)}}`).join(',\n')}\n}};\ninline constexpr std::array<Component,11> Components{{\n${data.map(b=>`{${b.joint},${b.region},${vec(b.center)},${vec(b.half)}}`).join(',\n')},\n{1,6,${vec(core.localCenter)},${vec(core.localHalf)}}\n}};\n}\n`;
fs.writeFileSync(path.join(root,'game/Mechalord/Source/Mechalord/BossPoseModel.h'),header);
const lines=[];let count=0;
function addPose(p){
 for(const n of joint)n.rotation.set(0,0,0);actor.position.fromArray(p.position);actor.rotation.set(...p.rootEuler);
 for(let i=0;i<2;i++){const side=i?'R':'L';model.getObjectByName('Arm_'+side).rotation.set(p.armPitch[i],0,p.armRoll[i]);model.getObjectByName('Leg_'+side).rotation.x=p.legPitch[i];model.getObjectByName('Knee_'+side).rotation.x=p.kneePitch[i];model.getObjectByName('Barrel_'+side).rotation.z=p.barrelSpin[i];}
 actor.updateMatrixWorld(true);lines.push([...p.position,...p.rootEuler,...p.armPitch,...p.armRoll,...p.legPitch,...p.kneePitch,...p.barrelSpin,p.clock??0].join(' '));
 for(const c of data){const n=joint[c.joint],center=new T.Vector3(...c.center).applyMatrix4(n.matrixWorld),q=n.getWorldQuaternion(new T.Quaternion());lines.push([...center.toArray(),...q.toArray(),...c.half.map(v=>v*1.4)].join(' '));}
 const torso=joint[1],heart=new T.Vector3(...core.localCenter).applyMatrix4(torso.matrixWorld);lines.push([...heart.toArray(),...torso.getWorldQuaternion(new T.Quaternion()).toArray(),...core.localHalf.map(v=>v*1.4)].join(' '));count++;
}
for(const pitch of[-.18,0,.18])for(const bank of[-.22,0,.22])for(const yaw of[-.32,0,.32])for(const armPitch of[-.30,-.20,.22,.35])for(const legPitch of[-.16,0,.16])addPose({position:[.7,.8,-11],rootEuler:[pitch,yaw,bank],armPitch:[armPitch,armPitch],armRoll:[0,0],legPitch:[legPitch,legPitch],kneePitch:[Math.max(0,legPitch)*.75,Math.max(0,legPitch)*.75],barrelSpin:[0,0]});
for(let i=0;i<64;i++)addPose({position:[Math.sin(i)*2,.8+i*.015,-10-i*.05],rootEuler:[Math.sin(i*.37)*.18,Math.cos(i*.23)*.32,Math.sin(i*.51)*.22],armPitch:[Math.sin(i*.13)*.3,Math.cos(i*.17)*.35],armRoll:i%2?[-.18,.18]:[.07,-.11],legPitch:[Math.sin(i*.19)*.16,Math.cos(i*.31)*.16],kneePitch:[Math.abs(Math.sin(i*.11))*.12,Math.abs(Math.cos(i*.47))*.12],barrelSpin:[i*.57,-i*.39],clock:i/30});
fs.mkdirSync(path.join(root,'builds'),{recursive:true});fs.writeFileSync(path.join(root,'builds/boss-pose-oracle.txt'),count+'\n'+lines.join('\n')+'\n');
fs.writeFileSync(path.join(root,'builds/boss-pose-model-receipt.json'),JSON.stringify({source:'delivery/playable/forge-tyrant.glb',sha256:createHash('sha256').update(bytes).digest('hex'),scale:1.4,binds,components:data,core:{joint:'Torso',...core},samples:count},null,2)+'\n');
console.log('Prepared '+count+' independent Three.js poses,11 source-aligned component volumes and exact bind data.');
