// Independent integration checks against real Three adapters. Browser appearance remains separate.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const b=await esbuild.build({entryPoints:[path.join(here,file)],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'unbroken-visual-inline.cjs'));return m.exports;}
const {LaserClashVisuals}=await code('laser-clash-visuals.ts'),{RelicEffects}=await code('relic-effects.ts'),{CombatVisuals,CombatMissiles,CommanderPowerVisuals}=await code('combat-visuals.ts'),{createPickup,disposePickup}=await code('arsenal-visuals.ts');
let passed=0,failed=0;const checks=[];function test(name,run){try{run();passed++;checks.push({name,pass:true});console.log('PASS '+name);}catch(error){failed++;checks.push({name,pass:false,error:error.message});console.error('FAIL '+name+' '+error.stack);}}
const scene=new T.Scene(),hero=new T.Group();scene.add(hero);const clash=new LaserClashVisuals(scene),relic=new RelicEffects(scene,hero),fx=new CombatVisuals(scene),missiles=new CombatMissiles(scene),power=new CommanderPowerVisuals(scene);
const event={id:1,kind:'empPulse',value:1,x:0,z:0,entityId:0,variant:0,size:26},s={x:0,phase:'run',relic:0,ability:0,relics:[{activeTime:3},{activeTime:0},{activeTime:4}],bossY:0,bossX:0,bossZ:12,targets:[],effects:[],empStunTime:0,escortShield:0,powerTime:0},view={armyRadius:2.4,armyCenterX:0,armyCenterZ:1.5,visible:true};
const contact={active:true,progress:.53,time:2,x:.4,y:2.7,z:7,heroX:0,heroY:1.42,heroZ:1.3,enemyX:1,enemyY:5,enemyZ:13,result:'none'};
const matrix=(mesh,index=0)=>{const m=new T.Matrix4();mesh.getMatrixAt(index,m);return m;};
test('all simultaneous relic timers drive their own visuals and retired dome remains hidden',()=>{relic.update(s,view,0);assert(relic.shield.root.visible&&relic.overdrive.visible);assert(!relic.dome.visible&&!relic.rim.visible);relic.update({...s,relics:[{activeTime:0},{activeTime:0},{activeTime:2}]},view,0);assert(!relic.shield.root.visible&&relic.overdrive.visible);});
test('metal shield hits recoil one panel and leave bounded scorch tint while paused frames freeze',()=>{relic.update(s,view,.1);const before=[...relic.shield.panels.instanceMatrix.array];relic.trigger({...event,id:2,kind:'shieldHit',x:1,value:10});relic.update(s,view,0);assert.notDeepEqual([...relic.shield.panels.instanceMatrix.array],before);const after=[...relic.shield.panels.instanceMatrix.array];relic.update(s,{...view,paused:true},1);assert.deepEqual([...relic.shield.panels.instanceMatrix.array],after);assert(relic.shield.panels.geometry.attributes.color.count>1000);});
test('EMP has physical-thickness jagged full-platform ring and upright ion forks, then expires',()=>{relic.trigger(event);relic.update(s,view,0);assert.equal(relic.stats.empArcSegments,144);for(let i=0;i<4;i++)relic.update(s,view,.1);assert(relic.wave.scale.x>20);assert(relic.stats.empArcSegments<=256);for(let i=0;i<4;i++)relic.update(s,view,.1);assert.equal(relic.stats.empArcSegments,0);});
test('laser clash appears only from authoritative active state and uses actual world contact',()=>{clash.update(undefined,0);assert(!clash.root.visible);clash.update(contact,0);assert(clash.root.visible);assert.deepEqual(clash.stats.contact,[.4,2.7,-7]);assert.equal(clash.stats.arcs,60);assert.equal(clash.stats.sparks,48);assert.equal(clash.stats.rings,5);clash.update({...contact,active:false},.1);assert(!clash.root.visible&&clash.stats.arcs===0);});
test('clash source clipping preserves full .80m beam width and exact elevated endpoint',()=>{missiles.update([],[],{depthScale:1,bossPhase:true,bossY:0,overdrive:false,weapon:1,dt:0,emitters:{core:new T.Vector3(1,5,-13)},lasers:[{id:1,x:1,y:5,z:13,endX:.4,endY:2.7,endZ:7,width:.8,time:1}]});const m=matrix(missiles.beamShells),a=new T.Vector3(0,0,-.5).applyMatrix4(m),b=new T.Vector3(0,0,.5).applyMatrix4(m);assert(a.distanceTo(new T.Vector3(1,5,-13))<1e-5);assert(b.distanceTo(new T.Vector3(.4,2.7,-7))<1e-5);assert(Math.abs(new T.Vector3().setFromMatrixScale(m).x-.8)<1e-6);});
test('dynamic clash contact follows changes, freezes exactly, bounds all repeated resources and reset',()=>{const count=clash.root.children.length,geometries=new Set(clash.root.children.map(m=>m.geometry));clash.update(contact,.04);const positions=[...clash.arcs.instanceMatrix.array],clock=clash.stats.clock;for(let i=0;i<100;i++)clash.update(contact,0);assert.deepEqual([...clash.arcs.instanceMatrix.array],positions);assert.equal(clash.stats.clock,clock);for(let i=0;i<1000;i++){clash.update({...contact,z:5+(i%20)*.05,progress:i%100/100},.016);assert(clash.stats.arcs<=160&&clash.stats.sparks<=48);if(i%31===0)clash.reset();}assert.equal(clash.root.children.length,count);assert.deepEqual(new Set(clash.root.children.map(m=>m.geometry)),geometries);clash.reset();assert(!clash.root.visible&&clash.stats.arcs===0);});
test('Arc Storm layered branch trunk has real endpoint bloom and no proximity-generated links',()=>{power.update([],0);assert.equal(power.stats.arcs,0);assert(power.trigger({...event,id:7,kind:'chainHit',x:0,y:1.5,z:0,endX:2,endY:1.4,endZ:9}));power.update([],0);assert(power.stats.arcs>=30);assert.equal(power.muzzles.count,2);const end=new T.Vector3().setFromMatrixPosition(matrix(power.muzzles,1));assert(end.distanceTo(new T.Vector3(2,1.4,-9))<1e-5);});
test('repair cartridge has green cross and only positive actual healing emits a one-second rising plus',()=>{const p=createPickup('health');assert.equal(p.name,'PowerPickup_health');p.updateWorldMatrix(true,true);const box=new T.Box3().setFromObject(p);assert(box.getSize(new T.Vector3()).x>.8);disposePickup(p);assert(!fx.healthPickup(hero,0));assert.equal(fx.repairPulses.length,0);assert(fx.healthPickup(hero,20));fx.update(0);assert.equal(fx.repairCrosses.count,1);const y=new T.Vector3().setFromMatrixPosition(matrix(fx.repairCrosses)).y;fx.update(.1);assert(new T.Vector3().setFromMatrixPosition(matrix(fx.repairCrosses)).y>y);const frozen=[...fx.repairCrosses.instanceMatrix.array];fx.update(0);assert.deepEqual([...fx.repairCrosses.instanceMatrix.array],frozen);for(let i=0;i<11;i++)fx.update(.1);assert.equal(fx.repairCrosses.count,0);});
test('missile hot flame shader and soft smoke have actual turbulence rather than hard dot geometry',()=>{assert.equal(missiles.trails.geometry.type,'PlaneGeometry');assert(missiles.trails.material.fragmentShader.includes('noise('));assert(missiles.hotTrails.material.fragmentShader.includes('float hot='));const shader={uniforms:{},vertexShader:'#include <common>\n#include <begin_vertex>',fragmentShader:'#include <common>\n#include <color_fragment>'};missiles.exhaust.material.onBeforeCompile(shader);assert(shader.uniforms.uRocketClock);assert(shader.fragmentShader.includes('float turbulence'));assert(!shader.fragmentShader.includes('\\n'));});
test('freeze marks only actually stopped near enemies while slow marks all visible active enemy timers',()=>{const targets=[{id:1,kind:'enemy',hp:10,x:-1,z:10,variant:0},{id:2,kind:'enemy',hp:10,x:1,z:22,variant:0},{id:3,kind:'enemy',hp:0,x:0,z:8,variant:1},{id:4,kind:'crate',hp:10,x:0,z:4}];relic.update({...s,timePower:'freeze',timePowerTime:2,targets},view,0);assert.equal(relic.stats.timeMarkers,1);assert.equal(relic.stats.frostCrystals,4);relic.update({...s,timePower:'slow',timePowerTime:2,targets},view,0);assert.equal(relic.stats.timeMarkers,2);assert.equal(relic.stats.frostCrystals,0);relic.update({...s,timePower:'slow',timePowerTime:0,targets},view,0);assert.equal(relic.stats.timeMarkers,0);});
test('shield break is five armor fragments and no invented unit death or delayed explosion',()=>{fx.reset();fx.shieldBreak(2,1.2,-8);fx.update(0);assert.equal(fx.stats().debris,5);assert.equal(fx.stats().sparks,7);assert.equal(fx.stats().queuedBursts,0);assert.equal(fx.stats().bossFragments,0);});
test('all new resources dispose exactly once and leave the accepted hero intact',()=>{const owned=new Set();scene.traverse(m=>{if(m.geometry)owned.add(m.geometry);if(m.material)owned.add(m.material);});let disposed=0;owned.forEach(r=>r.addEventListener('dispose',()=>disposed++));clash.dispose();relic.dispose();fx.dispose();missiles.dispose();power.dispose();assert.equal(disposed,owned.size);assert.deepEqual(scene.children,[hero]);clash.dispose();assert.equal(disposed,owned.size);});
const receipt={scope:'CPU actual Three materials, geometry, authoritative endpoints, timers, pause and ownership; visual browser review and phone GPU performance separately required',passed,failed,checks,generatedAt:new Date().toISOString()};fs.writeFileSync(path.resolve(here,'../../builds/unbroken-presentation-checks.json'),JSON.stringify(receipt,null,2));if(failed)process.exitCode=1;
