// Actual current WASM/browser adapter, driven through normal public controls.
import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),binary=path.join(root,'delivery/playable/assault.wasm'),bytes=fs.readFileSync(binary);let cache;
globalThis.fetch=async(r,o)=>{assert.match(String(r),/assault\.wasm$/);cache=o?.cache;return new Response(bytes);};
const{AssaultCore}=await import('./assault-core.ts');const core=new AssaultCore();await core.load();
const results=[],winningRuns=[];const snap=()=>core.snapshot(),persist=s=>{const{effects,...rest}=s;return rest;};
function test(name,fn){try{fn();results.push({name,status:'pass'});console.log('PASS '+name);}catch(e){results.push({name,status:'fail',error:e.message});console.error('FAIL '+name+' — '+e.message);}}
function start(r=0,l=0,rank=0){core.start(r,l,rank);return snap();}
function advance(seconds,input=0,hz=60,observe){let s=snap();for(let i=0;i<Math.round(seconds*hz);i++){const b=s;core.step(1/hz,typeof input==='function'?input(s):input);s=snap();observe?.(s,b);}return s;}
// Snapshot-only automated feasibility route, not a first-time-player study.
function route(s){
 if(s.phase==='boss'){
  const shots=s.enemyShots.filter(p=>p.z<5.5).map(p=>({x:p.x-p.dx*p.z/p.dz,size:p.radius+.5}));const desired=s.bossX;
  return[desired,-2.8,2.8,-1.5,1.5,0].filter(x=>!shots.some(p=>Math.abs(x-p.x)<p.size)).sort((a,b)=>Math.abs(a-desired)-Math.abs(b-desired))[0]??desired;
 }
 const pickup=s.pickups.filter(p=>p.z<6).sort((a,b)=>a.z-b.z)[0];
 const goals=s.targets.filter(t=>t.z>1&&t.z<29&&(t.kind==='crate'||t.kind==='gate'||t.kind==='orb'||t.kind==='enemy'&&t.variant>0&&t.z<14)).sort((a,b)=>a.z-b.z);
 let desired=pickup?.x??goals[0]?.x??0;
 function choice(first){const pair=s.targets.filter(t=>t.kind==='gate'&&Math.abs(t.z-first.z)<.02);pair.sort((a,b)=>(b.op?s.army*(b.value-1):b.value)-(a.op?s.army*(a.value-1):a.value));return pair[0]?.x??desired;}
 if(goals[0]?.kind==='gate')desired=choice(goals[0]);
 const close=s.targets.filter(t=>t.kind==='gate'&&t.z>0&&t.z<3.5).sort((a,b)=>a.z-b.z)[0];if(close)desired=choice(close);
 const hazard=s.targets.find(t=>t.kind==='hazard'&&t.z<3&&Math.abs(t.x-desired)<t.size+.5);return hazard?(hazard.x>0?-3:3):desired;
}
function run(r=0,l=0,{controls=route,ability=true,rank=0,seconds=180,observe,stop}={}){
 start(r,l,rank);let s=snap();for(let i=0;i<seconds*60&&['run','boss','destroying'].includes(s.phase);i++){
  if(ability&&s.energy>=100&&s.ability===0&&s.phase!=='destroying'&&(r===2||s.phase==='boss'||s.targets.some(t=>t.kind==='enemy'&&t.z<12)))core.activate();const b=s;core.step(1/60,controls(s));s=snap();observe?.(s,b);if(stop?.(s))break;
 }return s;
}
function boss(r=0,l=0){const s=run(r,l,{stop:s=>s.phase==='boss'});assert.equal(s.phase,'boss');return s;}
function charged(r=0){const s=run(r,0,{ability:false,stop:s=>s.energy>=100});assert.equal(s.energy,100);return s;}
test('browser loads actual current WASM without cache and unexpected imports',()=>{assert.equal(cache,'no-store');assert.ok(core.api.memory instanceof WebAssembly.Memory);for(const i of WebAssembly.Module.imports(new WebAssembly.Module(bytes))){assert.equal(i.kind,'function');assert.equal(i.module,'wasi_snapshot_preview1');assert.ok(['fd_close','fd_seek','fd_write'].includes(i.name));}});
test('three stages reset baseline progression, pickups and far boss pose',()=>{for(let l=0;l<3;l++){const s=start(0,l);assert.equal(s.duration,55+l*5);assert.ok(Math.abs(s.travelGoal-s.duration*3.7)<.001);assert.equal(s.army,8);assert.equal(s.commanderHp,100);assert.equal(s.commanderMaxHp,100);assert.equal(s.rank,0);assert.equal(s.weaponPower,'none');assert.equal(s.powerTime,0);assert.equal(s.rankReward,0);assert.equal(s.pickups.length,0);assert.equal(s.bossZ,40);assert.equal(s.bossPhase,1);assert.equal(s.travelDistance,0);assert.equal(s.time,0);}});
test('saved rank bonuses are bounded, explicit and grant real weapon head starts',()=>{const names=['none','cannons','guided','railburst'];for(let rank=0;rank<4;rank++){const s=start(0,0,rank);assert.equal(s.rank,rank);assert.equal(s.army,8+rank*2);assert.equal(s.commanderMaxHp,100+rank*5);assert.equal(s.weaponPower,names[rank]);assert.equal(s.powerTime,rank?6:0);}const s=start(0,0,99);assert.equal(s.rank,5);assert.equal(s.army,18);});
test('steering stays bounded and speed-limited with invalid input handled',()=>{start();assert.ok(advance(1/60,100).x<=.15001);assert.equal(advance(2,100).x,3);assert.equal(advance(2,-100).x,-3);core.step(NaN,NaN);assert.equal(snap().x,-3);});
test('all threats and gate props enter from beyond the viewport with long lead-in',()=>{let observed=0;start();const initial=snap();assert.ok(initial.targets.every(t=>t.z>=40));run(0,0,{observe:(s,b)=>{const ids=new Set(b.targets.map(t=>t.id));for(const t of s.targets)if(!ids.has(t.id)){assert.ok(t.z>=39.8,`Target${t.id} popped at${t.z}`);observed++;}}});assert.ok(observed>200);});
test('forward travel is continuous during fights and nearby crates',()=>{let contact=0,nearCrates=0;run(0,2,{observe:(s,b)=>{if(b.phase==='run'){assert.ok(Math.abs(s.travelDistance-Math.min(s.travelGoal,b.travelDistance+3.7/60))<.001);}contact+=s.effects.filter(e=>e.kind==='contact').length;nearCrates+=s.targets.filter(t=>t.kind==='crate'&&t.z<4).length;}});assert.ok(contact>0&&nearCrates>0);});
test('ordinary projectiles stay strictly straight even near moving targets',()=>{let checked=0;run(0,0,{observe:s=>{for(const p of s.shots)if(p.kind!=='missile'){assert.equal(p.dx,0);assert.ok(p.dz>0);checked++;}}});assert.ok(checked>1000);});
test('gate choices collect one alternative once through actual arithmetic',()=>{for(const lane of[-1.8,1.8]){const ids=start().targets.filter(t=>t.kind==='gate').map(t=>t.id);let count=0;advance(13,lane,60,s=>{count+=s.effects.filter(e=>e.kind==='gate'&&ids.includes(e.entityId)).length;});assert.equal(count,1);}});
test('a gate improves through actual forward shot damage before crossing',()=>{const g=start().targets.find(t=>t.kind==='gate');let improved=false,hit=false;advance(12,-1.8,60,s=>{const t=s.targets.find(t=>t.id===g.id);improved ||= !!t&&t.hp<g.hp&&t.value>g.value;hit ||= s.effects.some(e=>e.kind==='hit'&&e.entityId===g.id);});assert.ok(improved&&hit);});
test('every removed enemy has an explicit actual ram death or retirement event',()=>{let checked=0;for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{const live=new Set(s.targets.map(t=>t.id));for(const t of b.targets.filter(t=>t.kind==='enemy'))if(!live.has(t.id)){const e=s.effects.find(e=>e.entityId===t.id&&(e.kind==='kill'||e.kind==='retreat'));assert.ok(e,`Silent removal${t.id} in${s.phase}`);if(e.kind==='retreat')assert.equal(e.value,0);checked++;}}});assert.ok(checked>500);});
test('contact survivors disengage sideways rather than walking through the commander',()=>{let contact=0,sideways=0,passes=0;run(0,2,{ability:false,observe:(s,b)=>{contact+=s.effects.filter(e=>e.kind==='contact').length;for(const t of s.targets.filter(t=>t.kind==='enemy'&&t.op===2)){const old=b.targets.find(q=>q.id===t.id);if(old&&Math.abs(t.x-old.x)>.01)sideways++;}passes+=s.effects.filter(e=>e.kind==='pass').length;}});assert.ok(contact>0&&sideways>0&&passes>0);});
test('boss transition does not wait for stragglers and preserves a visible exit',()=>{for(let l=0;l<3;l++){let before;const s=run(0,l,{observe:(s,b)=>{if(s.phase==='boss')before=b;},stop:s=>s.phase==='boss'});assert.equal(s.phase,'boss');assert.ok(Math.abs(s.time-s.duration)<.04);assert.equal(s.travelDistance,s.travelGoal);assert.equal(s.army,before.army);assert.ok(s.targets.filter(t=>t.kind==='enemy').every(t=>t.op===2));const retired=advance(1.5,s=>s.bossX);assert.ok(!retired.targets.some(t=>t.kind==='enemy'));}});
test('orb and elite deaths drop physical pickups with accurate source metadata',()=>{let orb=false,elite=false;const kinds=new Set();run(0,2,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='drop')){const death=s.effects.find(q=>q.kind==='kill'&&q.entityId===e.entityId);assert.ok(death);orb ||= death.variant===-3;elite ||= death.variant===1||death.variant===2;kinds.add(e.value);}}});assert.ok(orb&&elite);assert.deepEqual([...kinds].sort(),[1,2,3]);});
test('collecting a pickup requires steering into its physical radius',()=>{let collected=0,missed=0;run(0,2,{observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='pickup')){const old=b.pickups.find(p=>p.id===e.entityId);assert.ok(old);assert.ok(Math.abs(old.x-s.x)<=old.radius+.151);assert.ok(s.powerTime>=9.99);assert.equal(s.weaponPower,['none','guided','cannons','railburst'][e.value]);collected++;}missed+=s.effects.filter(e=>e.kind==='missed'&&e.variant===-4).length;}});assert.ok(collected>8&&missed>0);});
test('guided missiles steer while cannon and rail powers remain ballistic',()=>{let guided=false,cannon=false,rail=false;run(0,2,{observe:s=>{for(const p of s.shots){guided ||= p.kind==='missile'&&Math.abs(p.dx)>.1;cannon ||= p.kind==='cannon'&&p.dx===0;rail ||= p.kind==='rail'&&p.dx===0;}}});assert.ok(guided&&cannon&&rail);});
test('temporary powers expire and head starts are not permanent upgrades',()=>{for(let rank=1;rank<4;rank++){start(0,0,rank);const s=advance(7,3);assert.equal(s.weaponPower,'none');assert.equal(s.powerTime,0);assert.equal(s.weapon,1);}});
test('weapon tier XP is earned only from destroyed crates',()=>{let gains=0;run(0,0,{observe:(s,b)=>{if(s.weaponXP!==b.weaponXP||s.weapon!==b.weapon){assert.ok(s.effects.some(e=>e.kind==='kill'&&e.variant===-1));gains++;}}});assert.ok(gains>=5);});
test('all elite roles have meaningfully more health than common troops',()=>{let tested=0;run(0,2,{observe:s=>{const elite=s.targets.filter(t=>t.kind==='enemy'&&t.variant>0);for(const e of elite){const normal=s.targets.find(t=>t.kind==='enemy'&&t.variant===0&&Math.abs(t.z-e.z)<.2);if(normal){assert.ok(e.maxHp>=normal.maxHp*2.7);tested++;}}}});assert.ok(tested>20);});
test('earned relics activate once, expire and prevent charge regeneration while active',()=>{for(let r=0;r<3;r++){start(r);assert.equal(core.activate(),false);charged(r);assert.ok(core.activate());assert.equal(core.activate(),false);advance(2,route,60,s=>{assert.ok(s.ability>0);assert.equal(s.energy,0);});assert.equal(advance(5,route).ability,0);}});
test('Shield blocks actual army damage and EMP damages local enemies',()=>{let blocks=0;run(0,2,{observe:s=>{blocks+=s.effects.filter(e=>e.kind==='block').length;if(s.ability>0)assert.ok(!s.effects.some(e=>e.kind==='damage'));}});assert.ok(blocks>0);let s=charged(1);for(let i=0;i<1200&&!s.targets.some(t=>t.kind==='enemy'&&t.z<13&&Math.abs(t.x-s.x)<3.2);i++){core.step(1/60,route(s));s=snap();}const near=s.targets.filter(t=>t.kind==='enemy'&&t.z<13&&Math.abs(t.x-s.x)<3.2);assert.ok(near.length);assert.ok(core.activate());const after=snap();assert.ok(near.some(t=>!after.targets.some(q=>q.id===t.id&&q.hp>=t.hp)));});
test('boss jets in from above the horizon before beginning attacks',()=>{const b=boss(0,0);assert.equal(b.bossZ,40);let earlyShot=false;const mid=advance(2,0,60,s=>{earlyShot ||= s.enemyShots.length>0;assert.equal(s.bossAction,'advance');});assert.ok(mid.bossZ>19&&mid.bossZ<22);assert.equal(earlyShot,false);const arrived=advance(1,0);assert.ok(arrived.bossZ<=12.01);});
test('bosses move laterally, advance and hover with actual hit position',()=>{boss(0,2);const xs=[],zs=[],ys=[];let hit=false;advance(16,s=>s.bossX,60,s=>{xs.push(s.bossX);zs.push(s.bossZ);ys.push(s.bossY);hit ||= s.effects.some(e=>e.kind==='hit'&&e.variant===3&&Math.abs(e.z-s.bossZ)<.1);});assert.ok(Math.max(...xs)-Math.min(...xs)>3);assert.ok(Math.min(...zs)<9);assert.ok(Math.max(...ys)-Math.min(...ys)>.3);assert.ok(hit);});
test('three distinct boss attack patterns follow readable weapon windups',()=>{const patterns=new Set();let told=0;run(0,2,{observe:s=>{if(s.bossAction==='windup'&&s.bossAttack>0&&s.bossAttack<1)told++;for(const e of s.effects.filter(e=>e.kind==='bossShot'))patterns.add(e.value);}});assert.deepEqual([...patterns].sort(),[0,1,2]);assert.ok(told>100);});
test('second-phase battleizer begins at half health exactly once',()=>{for(let l=0;l<3;l++){let phaseEvents=0,phase2=false;run(0,l,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='bossPhase')){phaseEvents++;assert.equal(e.value,2);assert.ok(s.bossHp<=s.bossMax*.5+.01);}phase2 ||= s.bossPhase===2;}});assert.ok(phase2);assert.equal(phaseEvents,1);}});
test('all boss projectile families travel and can cause actual damage',()=>{const kinds=new Set();let moved=false,hits=0;boss(0,2);advance(25,3,60,(s,b)=>{for(const p of s.enemyShots){kinds.add(p.kind);const old=b.enemyShots.find(q=>q.id===p.id);if(old&&p.z<old.z)moved=true;}hits+=s.effects.filter(e=>e.kind==='damage').length;});assert.deepEqual([...kinds].sort(),['orb','rocket','shell']);assert.ok(moved&&hits>0);});
function positions(s){const count=Math.min(24,s.army-1),columns=Math.min(4,count),limit=Math.max(.3,3.9-(columns-1)*.35),center=Math.max(-limit,Math.min(limit,s.x));return Array.from({length:count},(_,i)=>{const row=Math.floor(i/columns),width=Math.min(columns,count-row*columns);return{x:center+(i%columns-(width-1)/2)*.70,z:-(.75+row*.48),index:i};});}
test('troop-owned shots originate from the same formation without adding fire budget',()=>{start();const s=advance(.3,1.8);assert.equal(s.shots.length,5);assert.equal(s.shots.filter(p=>p.owner==='commander').length,2);assert.equal(s.shots.filter(p=>p.owner==='troop').length,3);for(const p of s.shots.filter(p=>p.owner==='troop')){assert.ok(positions(s).some(a=>Math.abs(a.x-p.x)<.001&&p.z-a.z>=0&&p.z-a.z<.55));assert.equal(p.dx,0);assert.ok(p.z>-5);}let rear=false;run(0,2,{observe:s=>{rear ||= s.shots.some(p=>p.owner==='troop'&&p.z<-2);}});assert.ok(rear);});
test('hostile shots hit actual side soldiers behind the commander plane',()=>{let hits=0,side=0;boss(0,2);advance(28,s=>s.bossX,60,(s,b)=>{if(s.army<25)return;for(const e of s.effects.filter(e=>e.kind==='damage'&&e.z<0)){const slot=positions({...b,x:s.x}).find(p=>p.index+1===e.entityId);assert.ok(slot);assert.ok(Math.hypot(slot.x-e.x,slot.z-e.z)<.002);hits++;side+=Math.abs(e.x-s.x)>.6;}});assert.ok(hits>3&&side>0);});
test('enemy bodies resolve side formation contact before they can overlap troop rows',()=>{let sides=0,clashes=0;run(0,2,{ability:false,observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='contact')){const old=b.targets.find(t=>t.id===e.entityId);assert.ok(old);const after=s.targets.find(t=>t.id===e.entityId);assert.ok(!after||after.op===2);assert.ok(s.effects.some(q=>q.entityId===e.entityId&&(q.kind==='hit'||q.kind==='kill')));clashes++;if(e.z<0&&Math.abs(e.x-s.x)>.5)sides++;}}});assert.ok(clashes>10&&sides>0);});
test('rollers break once on a real formation impact, including side soldiers',()=>{let breaks=0,side=0;run(0,2,{ability:false,controls:s=>s.phase==='boss'?route(s):0,observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='hazardBreak')){assert.equal(e.variant,-6);assert.ok(!s.targets.some(t=>t.id===e.entityId));assert.ok(b.targets.some(t=>t.id===e.entityId&&t.kind==='hazard'));assert.ok(s.effects.some(q=>q.kind==='damage'||q.kind==='block'||q.kind==='commanderHit'));breaks++;side+=Math.abs(e.x-s.x)>.5;}}});assert.ok(breaks>0&&side>0);});
test('commander HP is separate, loses health when exposed and dies exactly once',()=>{let wounds=0,deaths=0,exposed=false;const end=run(0,2,{ability:false,controls:()=>0,observe:s=>{exposed ||= s.army===1;for(const e of s.effects){if(e.kind==='commanderHit'){wounds++;assert.ok(s.commanderHp<100);assert.ok(!s.effects.some(q=>q.kind==='damage'));}if(e.kind==='commanderDeath')deaths++;}}});assert.ok(exposed&&wounds>0);assert.equal(deaths,1);assert.equal(end.phase,'lost');assert.equal(end.commanderHp,0);assert.equal(end.army,0);assert.deepEqual(persist(advance(2)),persist(end));assert.equal(start().commanderHp,100);});
test('boss death preserves a two-and-a-half-second wreck sequence before winning',()=>{const d=run(2,0,{stop:s=>s.phase==='destroying'});assert.equal(d.phase,'destroying');assert.equal(d.bossHp,0);assert.ok(d.effects.some(e=>e.kind==='bossDeath'));assert.ok(!d.effects.some(e=>e.kind==='win'));assert.equal(core.activate(),false);assert.equal(advance(2).phase,'destroying');const end=advance(.5);assert.equal(end.phase,'won');assert.equal(end.deathProgress,1);assert.equal(end.rankReward,1);assert.ok(end.effects.some(e=>e.kind==='win'));assert.ok(Math.abs(end.time-d.time-2.5)<.001);});
test('all nine baseline-rank level and relic routes remain beatable free',()=>{for(let l=0;l<3;l++)for(let r=0;r<3;r++){const powers=new Set();let contact=0;const s=run(r,l,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='pickup'))powers.add(e.value);contact+=s.effects.filter(e=>e.kind==='contact').length;}});assert.equal(s.phase,'won',`Level${l}/relic${r}: ${s.phase} time${s.time}`);assert.ok(s.army>0);assert.equal(s.rank,0);assert.equal(s.rankReward,1);assert.deepEqual([...powers].sort(),[1,2,3]);winningRuns.push({level:l,relic:r,time:s.time,army:s.army,weapon:s.weapon,kills:s.kills,powers:[...powers],contactAttacks:contact});}});
test('poor play loses rather than being protected by continuous traversal',()=>{for(let l=0;l<3;l++){const s=run(0,l,{controls:()=>0,ability:false});assert.equal(s.phase,'lost');assert.equal(s.army,0);assert.deepEqual(persist(advance(3,-3)),persist(s));}});
test('pause freezes travel, pickups, power timers and boss destruction',()=>{run(0,0,{stop:s=>s.pickups.length>0});core.pause(true);const b=persist(snap());assert.deepEqual(persist(advance(5,-3)),b);core.pause(false);assert.ok(advance(.5,0).time>b.time);run(2,0,{stop:s=>s.phase==='destroying'});core.pause(true);const d=persist(snap());assert.deepEqual(persist(advance(5)),d);core.pause(false);assert.equal(advance(2.5).phase,'won');});
test('fixed-step outcomes agree at30,60 and120Hz',()=>{for(let l=0;l<3;l++){const replay=hz=>{start(0,l);return persist(advance(30,-1.8,hz));};const b=replay(60);assert.deepEqual(replay(30),b);assert.deepEqual(replay(120),b);}});
test('authoritative formation excludes killed slots and restores only after casualty cooldown',()=>{let gaps=0,restored=0;const absent=new Map();run(0,2,{observe:s=>{assert.ok(s.formation.length<=24);const expected=positions(s);for(const unit of s.formation){const match=expected.find(p=>p.index===unit.index);assert.ok(match);assert.ok(Math.hypot(unit.x-match.x,unit.z-match.z)<.002);}if(s.army<25)return;const live=new Set(s.formation.map(p=>p.index));for(let i=0;i<24;i++){if(!live.has(i)&&!absent.has(i)){absent.set(i,s.time);gaps++;}else if(live.has(i)&&absent.has(i)){assert.ok(s.time-absent.get(i)>=.65);absent.delete(i);restored++;}}}});assert.ok(gaps>8&&restored>8);});
test('side-edge body and roller contacts remain identical at30,60 and120Hz',()=>{for(const lane of[-2.8,2.8]){function replay(hz){start(0,2,2);const events=[];const s=advance(45,lane,hz,s=>{for(const e of s.effects.filter(q=>q.kind==='contact'||q.kind==='hazardBreak'))events.push(e);});return{state:persist(s),events};}const baseline=replay(60);assert.ok(baseline.events.some(e=>e.kind==='contact'));assert.ok(baseline.events.some(e=>e.kind==='hazardBreak'));assert.deepEqual(replay(30),baseline);assert.deepEqual(replay(120),baseline);}});
test('Overdrive genuinely increases boss damage over the same controlled firing window',()=>{function damage(active){const b=run(2,0,{ability:false,stop:s=>s.phase==='boss'});assert.equal(b.phase,'boss');const begin=advance(3.5,s=>s.bossX);assert.equal(begin.energy,100);if(active)assert.ok(core.activate());const end=advance(2.5,s=>s.bossX);return begin.bossHp-end.bossHp;}assert.ok(damage(true)>damage(false)*1.2);});
test('all pooled simulation values remain finite and bounded',()=>{for(let l=0;l<3;l++)run(0,l,{observe:s=>{assert.ok(s.targets.length<=256&&s.shots.length<=256&&s.enemyShots.length<=96&&s.pickups.length<=24&&s.effects.length<=192);for(const k of['time','x','powerTime','bossX','bossY','bossZ','travelDistance'])assert.ok(Number.isFinite(s[k]));for(const p of s.shots)assert.ok(Number.isFinite(p.dx)&&p.dz>0&&p.z<=28);}});});
test('effects drain once and250 retries clear all rank/power/pickup state',()=>{const reset=persist(start());core.step(.25,0);const a=snap(),b=snap();assert.equal(b.effects.length,0);assert.deepEqual(persist(a),persist(b));const memory=core.api.memory.buffer.byteLength;for(let i=0;i<250;i++){start(i%3,i%3,i%4);advance(2,1.8);core.pause(true);assert.deepEqual(persist(start()),reset);assert.equal(core.api.memory.buffer.byteLength,memory);core.step(1/60,0);assert.ok(snap().time>0);}});
const report={schema:4,scope:'Actual continuous-travel Assault browser adapter/current WASM. Automated normal controls; no Unreal, physical-device or first-time-player validation.',binary,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),memoryBytes:core.api.memory.buffer.byteLength,testedAt:new Date().toISOString(),winningRuns,tests:results.length,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results};fs.mkdirSync(path.join(root,'builds'),{recursive:true});fs.writeFileSync(path.join(root,'builds/rebuild-test-results.json'),JSON.stringify(report,null,2));console.log(`${report.passed}/${report.tests} passed.`);if(report.failed)process.exitCode=1;
