// Actual current WASM/browser adapter, driven through normal public controls.
import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),binary=path.join(root,'delivery/playable/assault.wasm'),bytes=fs.readFileSync(binary);let cache;
globalThis.fetch=async(r,o)=>{assert.match(String(r),/assault\.wasm$/);cache=o?.cache;return new Response(bytes);};
const{AssaultCore}=await import('./assault-core.ts');const core=new AssaultCore();await core.load();const otherCore=new AssaultCore();await otherCore.load();
const geometry={frames:0,bodySamples:0,rollerSamples:0,formationPairs:0,silentOverlapCount:0},results=[],winningRuns=[];const snap=()=>core.snapshot(),persist=s=>{const{effects,...rest}=s;return rest;};
function test(name,fn){try{fn();results.push({name,status:'pass'});console.log('PASS '+name);}catch(e){results.push({name,status:'fail',error:e.message});console.error('FAIL '+name+' — '+e.message);}}
function start(r=0,l=0,rank=0){core.start(r,l,rank);return snap();}
function advance(seconds,input=0,hz=60,observe){let s=snap();for(let i=0;i<Math.round(seconds*hz);i++){const b=s;core.step(1/hz,typeof input==='function'?input(s):input);s=snap();observe?.(s,b);}return s;}
// Snapshot-only automated feasibility route, not a first-time-player study.
function route(s){
 if(s.phase==='boss'){
  const shots=s.enemyShots.filter(p=>p.z<5.5).map(p=>({x:p.x-p.dx*p.z/p.dz,size:p.radius+.5}));const desired=s.bossX;
  if(s.lasers.length||s.bossPattern==='laser'&&s.bossAttack>.3)return s.bossLane>0?-3:3;
  return[desired,-2.8,2.8,-1.5,1.5,0].filter(x=>!shots.some(p=>Math.abs(x-p.x)<p.size)).sort((a,b)=>Math.abs(a-desired)-Math.abs(b-desired))[0]??desired;
 }
 const pickup=s.pickups.filter(p=>p.z<6).sort((a,b)=>a.z-b.z)[0];
 const goals=s.targets.filter(t=>t.z>1&&t.z<29&&(t.kind==='crate'||t.kind==='gate'||t.kind==='orb'||t.kind==='enemy'&&t.variant>0&&t.z<14)).sort((a,b)=>a.z-b.z);
 let desired=pickup?.x??goals[0]?.x??0;
 function choice(first){const pair=s.targets.filter(t=>t.kind==='gate'&&Math.abs(t.z-first.z)<.02);pair.sort((a,b)=>(b.op?s.army*(b.value-1):b.value)-(a.op?s.army*(a.value-1):a.value));return pair[0]?.x??desired;}
 if(goals[0]?.kind==='gate')desired=choice(goals[0]);
 const close=s.targets.filter(t=>t.kind==='gate'&&t.z>0&&t.z<3.5).sort((a,b)=>a.z-b.z)[0];if(close)desired=choice(close);
 const hazard=s.targets.find(t=>t.kind==='hazard'&&t.z<3&&Math.abs(t.x-desired)<t.size+.5);return hazard?(hazard.x>0?-3:3):desired;
}
function run(r=0,l=0,{controls=route,ability=true,rank=0,seconds=180,observe,stop}={}){
 start(r,l,rank);let s=snap();for(let i=0;i<seconds*60&&['run','boss','destroying'].includes(s.phase);i++){
  if(ability&&s.energy>=100&&s.ability===0&&s.phase!=='destroying'&&(r===2||s.phase==='boss'||s.targets.some(t=>t.kind==='enemy'&&t.z<12)))core.activate();const b=s;core.step(1/60,controls(s));s=snap();observe?.(s,b);if(stop?.(s))break;
 }return s;
}
function boss(r=0,l=0){const s=run(r,l,{stop:s=>s.phase==='boss'});assert.equal(s.phase,'boss');return s;}
function charged(r=0){const s=run(r,0,{ability:false,stop:s=>s.energy>=100});assert.equal(s.energy,100);return s;}
test('browser loads actual current WASM without cache and unexpected imports',()=>{assert.equal(cache,'no-store');assert.ok(core.api.memory instanceof WebAssembly.Memory);for(const i of WebAssembly.Module.imports(new WebAssembly.Module(bytes))){assert.equal(i.kind,'function');assert.equal(i.module,'wasi_snapshot_preview1');assert.ok(['fd_close','fd_seek','fd_write'].includes(i.name));}});
test('three stages reset baseline progression, pickups and far boss pose',()=>{for(let l=0;l<3;l++){const s=start(0,l);assert.equal(s.duration,l===0?63:55+l*5);assert.ok(Math.abs(s.travelGoal-s.duration*3.7)<.001);assert.equal(s.army,8);assert.equal(s.commanderHp,100);assert.equal(s.commanderMaxHp,100);assert.equal(s.rank,0);assert.equal(s.weaponPower,'none');assert.equal(s.powerTime,0);assert.equal(s.rankReward,0);assert.equal(s.pickups.length,0);assert.equal(s.bossZ,40);assert.equal(s.bossPhase,1);assert.equal(s.travelDistance,0);assert.equal(s.time,0);}});
test('saved rank bonuses are bounded, explicit and grant real weapon head starts',()=>{const names=['none','cannons','guided','railburst'];for(let rank=0;rank<4;rank++){const s=start(0,0,rank);assert.equal(s.rank,rank);assert.equal(s.army,8+rank*2);assert.equal(s.commanderMaxHp,100+rank*5);assert.equal(s.weaponPower,names[rank]);assert.equal(s.powerTime,0);assert.equal(s.weaponPermanent,rank>0);assert.equal(s.starterWeapon,names[rank]);}const s=start(0,0,99);assert.equal(s.rank,5);assert.equal(s.army,18);});
test('steering stays bounded and speed-limited with invalid input handled',()=>{start();assert.ok(advance(1/60,100).x<=.15001);assert.equal(advance(2,100).x,3);assert.equal(advance(2,-100).x,-3);core.step(NaN,NaN);assert.equal(snap().x,-3);});
test('all threats and gate props enter from beyond the viewport with long lead-in',()=>{for(let level=0;level<3;level++){let observed=0;const initial=start(0,level);assert.ok(initial.targets.every(t=>t.z>=40));run(0,level,{observe:(s,b)=>{const ids=new Set(b.targets.map(t=>t.id));for(const t of s.targets)if(!ids.has(t.id)){assert.ok(t.z>=39.8,`Target${t.id} popped at${t.z}`);observed++;}}});assert.ok(observed>(level===0?20:100),`Stage${level} had no substantial approach`);}});
test('forward travel is continuous during fights and nearby crates',()=>{let contact=0,nearCrates=0;run(0,2,{observe:(s,b)=>{if(b.phase==='run'){assert.ok(s.travelDistance>b.travelDistance || s.travelDistance===s.travelGoal);}contact+=s.effects.filter(e=>e.kind==='contact').length;nearCrates+=s.targets.filter(t=>t.kind==='crate'&&t.z<4).length;}});assert.ok(contact>0&&nearCrates>0);});
test('ordinary projectiles stay strictly straight even near moving targets',()=>{let checked=0;run(0,0,{observe:s=>{for(const p of s.shots)if(p.kind!=='missile'){assert.equal(p.dx,0);assert.ok(p.dz>0);checked++;}}});assert.ok(checked>1000);});
test('gate choices collect one alternative once through actual arithmetic',()=>{for(const lane of[-1.8,1.8]){const ids=start().targets.filter(t=>t.kind==='gate').map(t=>t.id);let count=0;advance(13,lane,60,s=>{count+=s.effects.filter(e=>e.kind==='gate'&&ids.includes(e.entityId)).length;});assert.equal(count,1);}});
test('legacy arithmetic gates improve through forward shot damage before crossing',()=>{const g=start(0,1).targets.find(t=>t.kind==='gate');let improved=false,hit=false;advance(12,-1.8,60,s=>{const t=s.targets.find(t=>t.id===g.id);improved ||= !!t&&t.hp<g.hp&&t.value>g.value;hit ||= s.effects.some(e=>e.kind==='hit'&&e.entityId===g.id);});assert.ok(improved&&hit);});
test('every removed enemy has an explicit actual ram death or retirement event',()=>{let checked=0;for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{const live=new Set(s.targets.map(t=>t.id));for(const t of b.targets.filter(t=>t.kind==='enemy'))if(!live.has(t.id)){const e=s.effects.find(e=>e.entityId===t.id&&(e.kind==='kill'||e.kind==='retreat'));assert.ok(e,`Silent removal${t.id} in${s.phase}`);if(e.kind==='retreat')assert.equal(e.value,0);checked++;}}});assert.ok(checked>200);});
test('contact survivors disengage sideways rather than walking through the commander',()=>{let contact=0,sideways=0,passes=0;run(0,2,{ability:false,controls:s=>s.phase==='boss'?route(s):0,observe:(s,b)=>{contact+=s.effects.filter(e=>e.kind==='contact').length;for(const t of s.targets.filter(t=>t.kind==='enemy'&&t.op===2)){const old=b.targets.find(q=>q.id===t.id);if(old&&Math.abs(t.x-old.x)>.01)sideways++;}passes+=s.effects.filter(e=>e.kind==='pass').length;}});assert.ok(contact>0&&sideways>0);});
test('boss transition does not wait for stragglers and preserves a visible exit',()=>{for(let l=0;l<3;l++){let before;const s=run(0,l,{observe:(s,b)=>{if(s.phase==='boss')before=b;},stop:s=>s.phase==='boss'});assert.equal(s.phase,'boss');assert.ok(s.time>s.duration-12&&s.time<s.duration+18);assert.equal(s.travelDistance,s.travelGoal);assert.equal(s.army,before.army);assert.ok(s.targets.filter(t=>t.kind==='enemy').every(t=>t.op===2));const retired=advance(1.5,s=>s.bossX);assert.ok(!retired.targets.some(t=>t.kind==='enemy'));}});
test('orb and elite deaths drop physical pickups with accurate source metadata',()=>{let orb=false,elite=false;const kinds=new Set();run(0,2,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='drop')){const death=s.effects.find(q=>q.kind==='kill'&&q.entityId===e.entityId);assert.ok(death);orb ||= death.variant===-3;elite ||= death.variant===1||death.variant===2;kinds.add(e.value);}}});assert.ok(orb&&elite);assert.deepEqual([...kinds].sort(),[1,2,3,4,5,6]);});
test('collecting a pickup requires steering into its physical radius',()=>{let collected=0,missed=0;run(0,2,{observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='pickup')){const old=b.pickups.find(p=>p.id===e.entityId);assert.ok(old);assert.ok(Math.abs(old.x-s.x)<=old.radius+.151);if(e.value<=3){assert.ok(s.powerTime>=9.99);assert.equal(s.weaponPower,['none','guided','cannons','railburst'][e.value]);}else{assert.ok(s.timePowerTime>=(e.value===4?2.99:4.99));assert.equal(s.timePower,['none','freeze','slow','haste'][e.value-3]);}collected++;}missed+=s.effects.filter(e=>e.kind==='missed'&&e.variant===-4).length;}});assert.ok(collected>8&&missed>0);});
test('guided missiles steer while cannon and rail powers remain ballistic',()=>{let guided=false,cannon=false,rail=false;run(0,2,{observe:s=>{for(const p of s.shots){guided ||= p.kind==='missile'&&Math.abs(p.dx)>.1;cannon ||= p.kind==='cannon'&&p.dx===0;rail ||= p.kind==='rail'&&p.dx===0;}}});assert.ok(guided&&cannon&&rail);});
test('earned starter weapons remain permanent beyond the former six-second drop',()=>{for(let rank=1;rank<4;rank++){start(0,0,rank);const s=advance(7,3);assert.equal(s.weaponPower,['none','cannons','guided','railburst'][rank]);assert.equal(s.weaponPermanent,true);assert.equal(s.powerTime,0);assert.equal(s.weapon,1);}});
test('legacy weapon tier XP is earned only from destroyed crates',()=>{let gains=0;run(0,1,{observe:(s,b)=>{if(s.weaponXP!==b.weaponXP||s.weapon!==b.weapon){assert.ok(s.effects.some(e=>e.kind==='kill'&&e.variant===-1));gains++;}}});assert.ok(gains>=5);});
test('Reactor Siege offers fixed gate rewards and an early earned tier upgrade',()=>{const initial=start().targets.filter(t=>t.kind==='gate');let upgrade=null,gateCollected=false;advance(18,-1.8,60,s=>{for(const t of s.targets.filter(t=>initial.some(g=>g.id===t.id))){const old=initial.find(g=>g.id===t.id);assert.equal(t.hp,0);assert.equal(t.value,old.value);}gateCollected ||= s.effects.some(e=>e.kind==='gate');if(s.weapon>1)upgrade??=s.time;});assert.ok(gateCollected);assert.ok(upgrade!==null&&upgrade<18,'Aligned fresh commander did not earn the early crate tier');});
test('charge comes from actual removed HP and kill rewards, including overkill',()=>{let frames=0,kills=0,thinKills=0;for(const rank of[0,2,3]){let b=start(2,0,rank);for(let f=0;f<15*60&&b.phase==='run';f++){core.step(1/60,-1.8);const s=snap();let removed=0,bonus=0;for(const t of b.targets){const after=s.targets.find(q=>q.id===t.id),killed=s.effects.some(e=>e.kind==='kill'&&e.entityId===t.id);if(after)removed+=Math.max(0,t.hp-after.hp);else if(killed)removed+=t.hp;if(killed){bonus+=t.kind==='crate'?8:t.role==='carrier'?8:t.variant>0?4:2;kills++;if(t.hp>0&&t.hp<1.5)thinKills++;}}bonus+=5*s.effects.filter(e=>e.kind==='gate').length+10*s.effects.filter(e=>e.kind==='pickup').length;const expected=Math.min(100,b.energy+removed*.07+bonus);assert.ok(Math.abs(s.energy-expected)<.00012,`Actual HP charge mismatch rank${rank} at${s.time}: ${s.energy} vs${expected}`);frames++;b=s;}}assert.ok(frames>2000&&kills>10&&thinKills>0,'No measured low-HP kills exercised overkill accounting');});
test('all elite roles have meaningfully more health than common troops',()=>{let tested=0;run(0,2,{observe:s=>{const elite=s.targets.filter(t=>t.kind==='enemy'&&t.variant>0);for(const e of elite){const normal=s.targets.find(t=>t.kind==='enemy'&&t.variant===0&&Math.abs(t.z-e.z)<.2);if(normal){assert.ok(e.maxHp>=normal.maxHp*2.7);tested++;}}}});assert.ok(tested>20);});
test('earned relics activate once, expire and prevent charge regeneration while active',()=>{for(let r=0;r<3;r++){start(r);assert.equal(core.activate(),false);charged(r);assert.ok(core.activate());assert.equal(core.activate(),false);advance(2,route,60,s=>{assert.ok(s.ability>0);assert.equal(s.energy,0);});assert.equal(advance(5,route).ability,0);}});
test('Shield blocks actual army damage and EMP damages local enemies',()=>{let blocks=0;run(0,2,{observe:s=>{blocks+=s.effects.filter(e=>e.kind==='block').length;if(s.ability>0)assert.ok(!s.effects.some(e=>e.kind==='damage'));}});assert.ok(blocks>0);let s=charged(1);for(let i=0;i<1200&&!s.targets.some(t=>t.kind==='enemy'&&t.z<13&&Math.abs(t.x-s.x)<3.2);i++){core.step(1/60,route(s));s=snap();}const near=s.targets.filter(t=>t.kind==='enemy'&&t.z<13&&Math.abs(t.x-s.x)<3.2);assert.ok(near.length);assert.ok(core.activate());const after=snap();assert.ok(near.some(t=>!after.targets.some(q=>q.id===t.id&&q.hp>=t.hp)));});
test('boss jets in from the horizon before attacks, respecting earned time powers',()=>{let s=boss(0,0);assert.equal(s.bossZ,40);let frames=0;while(s.bossZ>12.01&&frames++<720){const b=s;core.step(1/60,0);s=snap();assert.ok(s.bossZ<=b.bossZ);assert.equal(s.bossAction,'advance');assert.equal(s.enemyShots.length,0);}assert.ok(frames>100&&frames<720);assert.ok(s.bossZ<=12.01);});
test('bosses move laterally, advance and hover with actual hit position',()=>{boss(0,2);const xs=[],zs=[],ys=[];let hit=false;advance(16,s=>s.bossX,60,s=>{xs.push(s.bossX);zs.push(s.bossZ);ys.push(s.bossY);hit ||= s.effects.some(e=>e.kind==='hit'&&(e.variant===3||e.variant===4)&&Math.abs(e.z-s.bossZ)<.1);});assert.ok(Math.max(...xs)-Math.min(...xs)>3);assert.ok(Math.min(...zs)<9);assert.ok(Math.max(...ys)-Math.min(...ys)>.3);assert.ok(hit);});
test('four boss attack patterns follow readable cues across stages and parts',()=>{const patterns=new Set();let told=0;for(let l=0;l<3;l++)run(0,l,{observe:s=>{if(s.bossAction==='windup'&&s.bossAttack>0&&s.bossAttack<1)told++;for(const e of s.effects.filter(e=>e.kind==='bossShot'))patterns.add(e.value);}});assert.deepEqual([...patterns].sort(),[0,1,2,3]);assert.ok(told>100);});
test('second-phase battleizer begins at half health exactly once',()=>{for(let l=0;l<3;l++){let phaseEvents=0,phase2=false;run(0,l,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='bossPhase')){phaseEvents++;assert.equal(e.value,2);assert.ok(s.bossHp<=s.bossMax*.5+.01);}phase2 ||= s.bossPhase===2;}});assert.ok(phase2);assert.equal(phaseEvents,1);}});
test('all boss projectile families travel through actual world positions',()=>{const kinds=new Set();let moved=false;for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{for(const p of s.enemyShots){kinds.add(p.kind);const old=b.enemyShots.find(q=>q.id===p.id);if(old&&p.z<old.z)moved=true;}}});assert.deepEqual([...kinds].sort(),['orb','rocket','shell']);assert.ok(moved);});
function positions(s){return s.formation;}
test('hostile projectiles retain actual weapon sources and immutable measured launches',()=>{const seen=new Set();let checked=0,anchored=0;const offsets={armL:[1.72480,-2.09960,3.74926],armR:[-1.72480,-2.09960,3.74926],shoulderL:[1.432465,-.641911,5.367958],shoulderR:[-1.432465,-.641911,5.367958],core:[0,-.847,4.312]},bits={armL:1,armR:2,shoulderL:4,shoulderR:8};for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{for(const p of s.enemyShots){seen.add(p.emitter);assert.ok([p.launchX,p.launchZ,p.launchY].every(Number.isFinite));const old=b.enemyShots.find(q=>q.id===p.id);if(old){assert.equal(p.emitter,old.emitter);assert.equal(p.launchX,old.launchX);assert.equal(p.launchZ,old.launchZ);assert.equal(p.launchY,old.launchY);checked++;continue;}if(p.emitter==='gunner'){assert.ok(p.sourceId>0);assert.ok(Math.abs(p.launchY-1.65)<.000001);}else{assert.equal(p.sourceId,0);assert.ok(offsets[p.emitter]);if(b.phase==='boss')assert.equal(b.bossPartsMask&(bits[p.emitter]??0),0,'Shot emitted by an already broken part');const o=offsets[p.emitter];assert.ok(Math.abs(p.launchX-s.bossX-o[0])<.0001);assert.ok(Math.abs(p.launchZ-s.bossZ-o[1])<.0001);assert.ok(Math.abs(p.launchY-s.bossY-o[2])<.0001);if(p.kind==='rocket')assert.ok(p.emitter.startsWith('shoulder'));if(p.kind==='shell')assert.ok(p.emitter.startsWith('arm'));anchored++;}}}});assert.deepEqual([...seen].sort(),['armL','armR','core','gunner','shoulderL','shoulderR']);assert.ok(checked>100&&anchored>15);});
test('booster bursts brake during committed aim and disabled parts cannot move the boss',()=>{let fast=0,held=0,ground=0,arrivalSteps=0;for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{if(b.phase!=='boss'||s.phase!=='boss')return;const dx=Math.abs(s.bossX-b.bossX),dz=Math.abs(s.bossZ-b.bossZ);assert.ok(dx<=6/60+.0001);if(s.bossAction==='advance'&&s.bossZ>12.01){assert.ok(dz<=14.5/60+.0001);assert.ok(Math.abs(s.bossY-b.bossY)<.12,'Abrupt booster arrival height jump');arrivalSteps++;return;}const bothHeld=['windup','fire'].includes(s.bossAction)&&['windup','fire'].includes(b.bossAction);if(bothHeld||b.lasers.length){assert.equal(s.bossX,b.bossX);assert.equal(s.bossZ,b.bossZ);if(s.bossAction==='windup'&&b.bossAction==='windup')assert.equal(s.bossLane,b.bossLane);held++;}if((b.bossPartsMask&48)===48){assert.equal(s.bossX,b.bossX);assert.equal(s.bossZ,b.bossZ);ground++;}else if((b.bossPartsMask&12)===12)assert.ok(dx<=1.25/60+.0001);else if(dx>3/60)fast++;}});assert.ok(fast>20&&held>100&&ground>100&&arrivalSteps>200);});
test('new boss mobility, source tags and locked aim agree across frame rates and pause',()=>{function replay(hz){start(0,0,2);const births=[];const seen=new Set();const end=advance(82,0,hz,s=>{for(const p of s.enemyShots)if(!seen.has(p.id)){seen.add(p.id);births.push([p.id,p.emitter,p.launchX,p.launchZ,p.launchY]);}});return{state:persist(end),births};}const baseline=replay(60);assert.ok(baseline.births.some(p=>p[1].startsWith('arm')));assert.deepEqual(replay(30),baseline);assert.deepEqual(replay(120),baseline);boss(0,0);advance(3.3,0);core.pause(true);const held=persist(snap());assert.deepEqual(persist(advance(1,3)),held);core.pause(false);assert.ok(advance(.1,3).time>held.time);});
test('troop-owned shots originate from the same formation without adding fire budget',()=>{for(let level=0;level<3;level++){start(0,level);const s=advance(level===0?.35:.3,1.8);assert.equal(s.shots.length,level===0?4:5);assert.equal(s.shots.filter(p=>p.owner==='commander').length,2);assert.equal(s.shots.filter(p=>p.owner==='troop').length,level===0?2:3);for(const p of s.shots.filter(p=>p.owner==='troop')){assert.ok(positions(s).some(a=>Math.abs(a.x-p.x)<.001&&p.z-a.z>=0&&p.z-a.z<.55));assert.equal(p.dx,0);assert.ok(p.z>-5);}}let rear=false;run(0,2,{observe:s=>{rear ||= s.shots.some(p=>p.owner==='troop'&&p.z<-2);}});assert.ok(rear);});
test('hostile shots hit actual side soldiers behind the commander plane',()=>{let hits=0,side=0;boss(0,2);advance(28,s=>s.bossX,60,(s,b)=>{if(s.army<25)return;for(const e of s.effects.filter(e=>e.kind==='damage'&&e.z<0)){const shift=Math.max(-2.805,Math.min(2.805,s.x))-Math.max(-2.805,Math.min(2.805,b.x));const slot=b.formation.map(p=>({...p,x:p.x+shift})).find(p=>p.index+1===e.entityId);assert.ok(slot);assert.ok(Math.hypot(slot.x-e.x,slot.z-e.z)<.002);hits++;side+=Math.abs(e.x-s.x)>.6;}});assert.ok(hits>3&&side>0);});
test('enemy bodies resolve side formation contact before they can overlap troop rows',()=>{let sides=0,clashes=0;run(0,2,{ability:false,controls:()=>-2.8,observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='contact')){const old=b.targets.find(t=>t.id===e.entityId);assert.ok(old);const after=s.targets.find(t=>t.id===e.entityId);assert.ok(!after||after.op===2);assert.ok(s.effects.some(q=>q.entityId===e.entityId&&(q.kind==='hit'||q.kind==='kill')));clashes++;if(s.effects.some(d=>d.kind==='damage'&&d.z<0&&Math.abs(d.x-s.x)>.5))sides++;}}});assert.ok(clashes>0&&sides>0);});
test('rollers break once on a real formation impact, including side soldiers',()=>{let breaks=0,side=0;run(0,2,{ability:false,controls:s=>s.phase==='boss'?route(s):0,observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='hazardBreak')){assert.equal(e.variant,-6);assert.ok(!s.targets.some(t=>t.id===e.entityId));assert.ok(b.targets.some(t=>t.id===e.entityId&&t.kind==='hazard'));assert.ok(s.effects.some(q=>q.kind==='damage'||q.kind==='block'||q.kind==='commanderHit'));breaks++;side+=Math.abs(e.x-s.x)>.5;}}});assert.ok(breaks>0&&side>0);});
test('commander HP is separate, loses health when exposed and dies exactly once',()=>{let wounds=0,deaths=0,exposed=false;const end=run(0,2,{ability:false,controls:()=>0,observe:s=>{exposed ||= s.army===1;for(const e of s.effects){if(e.kind==='commanderHit'){wounds++;assert.ok(s.commanderHp<100);assert.ok(s.commanderHp<100);}if(e.kind==='commanderDeath')deaths++;}}});assert.ok(exposed&&wounds>0);assert.equal(deaths,1);assert.equal(end.phase,'lost');assert.equal(end.commanderHp,0);assert.equal(end.army,0);assert.deepEqual(persist(advance(2)),persist(end));assert.equal(start().commanderHp,100);});
test('boss death preserves a two-and-a-half-second wreck sequence before winning',()=>{const d=run(2,0,{stop:s=>s.phase==='destroying'});assert.equal(d.phase,'destroying');assert.equal(d.bossHp,0);assert.ok(d.effects.some(e=>e.kind==='bossDeath'));assert.ok(!d.effects.some(e=>e.kind==='win'));assert.equal(core.activate(),false);assert.equal(advance(2).phase,'destroying');const end=advance(.5);assert.equal(end.phase,'won');assert.equal(end.deathProgress,1);assert.equal(end.rankReward,1);assert.ok(end.effects.some(e=>e.kind==='win'));assert.ok(Math.abs(end.time-d.time-2.5)<.001);});
test('all nine baseline-rank level and relic routes remain beatable free',()=>{for(let l=0;l<3;l++)for(let r=0;r<3;r++){const powers=new Set();let contact=0;const s=run(r,l,{observe:s=>{for(const e of s.effects.filter(e=>e.kind==='pickup'))powers.add(e.value);contact+=s.effects.filter(e=>e.kind==='contact').length;}});assert.equal(s.phase,'won',`Level${l}/relic${r}: ${s.phase} time${s.time}`);assert.ok(s.army>0);assert.equal(s.rank,0);assert.equal(s.rankReward,1);assert.ok(powers.size>0);winningRuns.push({level:l,relic:r,time:s.time,army:s.army,weapon:s.weapon,kills:s.kills,commanderHp:s.commanderHp,bossArmorRebuilds:s.bossRevives,commanderReviveUsed:s.reviveUsed,powers:[...powers],contactAttacks:contact});}});
test('poor play loses rather than being protected by continuous traversal',()=>{for(let l=0;l<3;l++){const s=run(0,l,{controls:()=>0,ability:false});assert.equal(s.phase,'lost');assert.equal(s.army,0);assert.deepEqual(persist(advance(3,-3)),persist(s));}});
test('pause freezes travel, pickups, power timers and boss destruction',()=>{run(0,0,{stop:s=>s.pickups.length>0});core.pause(true);const b=persist(snap());assert.deepEqual(persist(advance(5,-3)),b);core.pause(false);assert.ok(advance(.5,0).time>b.time);run(2,0,{stop:s=>s.phase==='destroying'});core.pause(true);const d=persist(snap());assert.deepEqual(persist(advance(5)),d);core.pause(false);assert.equal(advance(2.5).phase,'won');});
test('fixed-step outcomes agree at30,60 and120Hz',()=>{for(let l=0;l<3;l++){const replay=hz=>{start(0,l);return persist(advance(30,-1.8,hz));};const b=replay(60);assert.deepEqual(replay(30),b);assert.deepEqual(replay(120),b);}});
test('casualty slots stay permanently absent and return only through real recruitment',()=>{let deaths=0,growth=0,aboveCap=0;for(let l=0;l<3;l++)run(0,l,{observe:(s,b)=>{const before=new Set(b.formation.map(p=>p.index)),after=new Set(s.formation.map(p=>p.index));for(const p of b.formation)if(!after.has(p.index)){assert.ok(s.effects.some(e=>e.kind==='troopDeath'&&e.entityId===p.index+1)||s.effects.some(e=>e.kind==='commanderDeath'));deaths++;aboveCap+=s.army>24;}for(const p of s.formation)if(!before.has(p.index)){assert.ok(s.effects.some(e=>e.kind==='recruit'));growth++;}if(b.phase==='boss')assert.ok(s.formation.length<=b.formation.length);}});assert.ok(deaths>12&&growth>12&&aboveCap>8);});
test('side-edge body and roller contacts remain identical at30,60 and120Hz',()=>{for(const lane of[-2.8,2.8]){function replay(hz){start(0,2,2);const events=[];const s=advance(45,lane,hz,s=>{for(const e of s.effects.filter(q=>q.kind==='contact'||q.kind==='hazardBreak'))events.push(e);});return{state:persist(s),events};}const baseline=replay(60);assert.ok(baseline.events.length>0);assert.ok(baseline.events.some(e=>e.kind==='hazardBreak'));assert.deepEqual(replay(30),baseline);assert.deepEqual(replay(120),baseline);}});
test('Overdrive boosts actual exposed-core hit damage while armor remains bounded',()=>{function damage(active){const begin=run(2,0,{ability:false,stop:s=>s.phase==='boss'&&s.bossState==='exposed'});assert.equal(begin.bossState,'exposed');assert.equal(begin.energy,100);if(active)assert.ok(core.activate());let peak=0;advance(2.5,s=>s.bossX,60,s=>{for(const e of s.effects.filter(e=>e.kind==='hit'&&e.variant===4))peak=Math.max(peak,e.value);});return peak;}assert.ok(damage(true)>damage(false)*1.2);});
function collectTime(kind){const s=run(0,2,{controls:s=>{const p=s.pickups.filter(p=>p.kind===kind&&p.z<12).sort((a,b)=>a.z-b.z)[0];return p?.x??route(s);},stop:s=>s.timePower===kind});assert.equal(s.timePower,kind);return s;}
test('freeze pickups hold near-field machines while ordinary friendly fire continues',()=>{let held=0,fired=0,casts=0;for(let l=0;l<3;l++)run(0,l,{controls:s=>{const p=s.pickups.filter(p=>p.kind==='freeze'&&p.z<15).sort((a,b)=>a.z-b.z)[0],orb=s.targets.find(t=>t.kind==='orb'&&t.value===4&&t.z<29);return p?.x??orb?.x??(s.phase==='boss'?route(s):0);},observe:(s,b)=>{casts+=s.effects.filter(e=>e.kind==='pickup'&&e.value===4).length;if(s.timePower!=='freeze'||b.timePower!=='freeze')return;for(const t of b.targets.filter(t=>t.kind==='enemy'&&t.z<18&&t.op===0)){const n=s.targets.find(q=>q.id===t.id);if(n&&Math.abs(n.z-t.z)<.001)held++;}for(const p of s.enemyShots){assert.equal(p.dx,0);assert.equal(p.dz,0);}fired+=s.shots.length;}});assert.ok(casts>0&&held>0&&fired>0);});
test('slow and risky haste independently scale traversal and expire without altering weapons',()=>{for(const [kind,scale]of[['slow',.5],['haste',1.35]]){const before=collectTime(kind);assert.ok(before.timePowerTime>4.99);const s=advance(.2,before.x);assert.ok(Math.abs(s.travelDistance-before.travelDistance-.2*3.7*scale)<.002);assert.equal(s.timePower,kind);let replaced=false;const end=advance(5.2,3,60,s=>{replaced ||= s.effects.some(e=>e.kind==='pickup'&&e.value>=4);});if(!replaced){assert.equal(end.timePower,'none');assert.equal(end.timePowerTime,0);}else assert.ok(end.timePowerTime<=5);}assert.equal(start().timePower,'none');assert.equal(snap().timePowerTime,0);});
test('haste is a voluntary side-lane pickup and genuinely increases earned rewards',()=>{let offered=0,reward=0;run(0,2,{controls:s=>s.pickups.find(p=>p.kind==='haste'&&p.z<12)?.x??route(s),observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='drop'&&e.value===6)){assert.ok(Math.abs(e.x)>2.6);offered++;}if(b.timePower==='haste'&&s.timePower==='haste')for(const e of s.effects.filter(e=>e.kind==='kill'&&e.variant===0)){assert.equal(e.value,15);reward++;}}});assert.ok(offered>0&&reward>0);});
test('commander suffers real chip damage with troops alive, Shield blocks it and recruitment never heals',()=>{let chips=0;run(0,2,{observe:(s,b)=>{if(s.ability>0)assert.ok(!s.effects.some(e=>e.kind==='commanderHit'));if(s.effects.some(e=>e.kind==='commanderHit')&&s.army>1){assert.ok(s.commanderHp<b.commanderHp);chips++;}if(s.effects.some(e=>e.kind==='recruit'))assert.ok(s.commanderHp<=b.commanderHp);}});assert.ok(chips>0);});
test('armor breaks into a real timed core objective and strong weapons cannot instantly skip guns',()=>{for(const rank of[0,2,3]){let arrival=0,expose=0,tells=0,coreHits=0;const s=run(2,0,{rank,observe:(s,b)=>{if(s.phase==='boss'&&b.phase==='run')arrival=s.time;if(s.effects.some(e=>e.kind==='coreExpose')){expose ||= s.time;assert.equal(s.bossArmor,0);if(s.bossState==='destroying'){assert.equal(s.bossCoreHp,0);assert.ok(s.effects.some(e=>e.kind==='bossDeath'));}else{assert.equal(s.bossState,'exposed');assert.ok(s.bossCoreHp>0);assert.ok(s.bossCoreTime>4.9&&s.bossCoreTime<=5);}}tells+=s.effects.filter(e=>e.kind==='bossShot').length;coreHits+=s.effects.filter(e=>e.kind==='hit'&&e.variant===4).length;}});assert.equal(s.phase,'won');assert.ok(expose-arrival>10);assert.ok(tells>=3&&coreHits>5);}});
test('missing a core window repairs armor once, then repeated finite openings preserve wounds',()=>{let s=run(0,0,{stop:s=>s.phase==='boss'&&s.bossState==='exposed'});assert.equal(s.bossState,'exposed');const wound=s.bossCoreHp;let revival=0;for(let i=0;i<12*60&&s.bossState!=='armored';i++){if(s.energy>=100)core.activate();core.step(1/60,s.bossX>0?-3:3);s=snap();revival+=s.effects.filter(e=>e.kind==='bossRevive').length;}assert.equal(revival,1);assert.equal(s.bossRevives,1);assert.equal(s.bossState,'armored');assert.ok(s.bossArmor>0&&s.bossCoreHp<=wound);let exposed=0,previousCore=s.bossCoreHp;for(let i=0;i<100*60&&['boss','destroying'].includes(s.phase);i++){if(s.energy>=100&&s.ability===0)core.activate();core.step(1/60,route(s));s=snap();revival+=s.effects.filter(e=>e.kind==='bossRevive').length;exposed+=s.effects.filter(e=>e.kind==='coreExpose').length;assert.ok(s.bossCoreHp<=previousCore+.001);previousCore=s.bossCoreHp;}assert.equal(revival,1);assert.ok(exposed>=1);assert.equal(s.phase,'won');assert.equal(s.bossCoreHp,0);});
test('weapon powers, time powers and relics coexist with independent timers',()=>{const before=run(0,2,{ability:false,stop:s=>s.weaponPower!=='none'&&s.timePower!=='none'&&s.energy>=100});assert.ok(before.weaponPower!=='none'&&before.timePower!=='none');assert.ok(core.activate());const s=advance(.1,before.x);assert.ok(s.ability>0&&s.powerTime>0&&s.timePowerTime>0);assert.equal(s.relic,0);const reset=start();assert.equal(reset.timePower,'none');assert.equal(reset.timePowerTime,0);assert.equal(reset.bossRevives,0);assert.equal(reset.bossState,'armored');assert.equal(reset.bossCoreTime,0);});
test('concurrent WASM instances isolate troops, pickups, boss state and pause',()=>{start();otherCore.start(2,2,3);const before=persist(otherCore.snapshot());advance(15,route);assert.deepEqual(persist(otherCore.snapshot()),before);core.pause(true);const own=persist(snap());otherCore.step(.25,3);assert.ok(otherCore.snapshot().time>.2);assert.deepEqual(persist(snap()),own);assert.notEqual(otherCore.api.memory.buffer,core.api.memory.buffer);core.pause(false);start();});
test('temporary weapon pickups override then restore the earned permanent starter',()=>{const before=run(0,0,{rank:2,ability:false,stop:s=>s.effects.some(e=>e.kind==='pickup'&&e.value<=3&&e.value!==1)});assert.equal(before.starterWeapon,'guided');assert.ok(before.powerTime>0&&!before.weaponPermanent);let restored=false;advance(14,s=>s.pickups.some(p=>p.z<6)?(s.pickups[0].x>0?-3:3):3,60,s=>{if(s.powerTime===0){assert.equal(s.weaponPower,'guided');assert.ok(s.weaponPermanent);restored=true;}});assert.ok(restored);});
test('sequential cannon, booster and leg breaks persist through the single armor rebuild',()=>{let order=[],jetFrames=0,ground;const end=run(0,0,{observe:(s,b)=>{for(const e of s.effects.filter(e=>e.kind==='bossPartBreak'))order.push(e.value);assert.equal(s.bossPartsMask|b.bossPartsMask,s.bossPartsMask);if((s.bossPartsMask&12)===12&&(s.bossPartsMask&48)!==48){assert.ok(Math.abs(s.bossY-.02)<.001);jetFrames++;assert.ok(s.bossPattern!=='rockets'||s.bossAction==='fire');}if((b.bossPartsMask&48)===48&&s.phase==='boss'){ground??={x:s.bossX,z:s.bossZ};assert.equal(s.bossX,ground.x);assert.equal(s.bossZ,ground.z);assert.ok(Math.abs(s.bossY+2.55)<.001);}}});assert.equal(end.phase,'won');assert.deepEqual(order,[1,2,3,4,5,6]);assert.equal(end.bossPartsMask,63);assert.ok(jetFrames>0);});
test('guided hostile rockets steer briefly and then commit to dodgable straight travel',()=>{let steering=0,committed=0,misses=0;run(0,0,{observe:(s,b)=>{for(const p of s.enemyShots.filter(p=>p.kind==='rocket')){const old=b.enemyShots.find(q=>q.id===p.id);if(!old)continue;if(p.guided&&old.guided&&Math.abs(p.dx-old.dx)>.0001)steering++;if(!p.guided&&!old.guided&&s.timePower===b.timePower&&s.ability===0&&b.ability===0){assert.ok(Math.abs(p.dx-old.dx)<.001);assert.ok(Math.abs(p.dz-old.dz)<.001);committed++;}}for(const p of b.enemyShots)if(p.z<0&&!s.enemyShots.some(q=>q.id===p.id)&&!s.effects.some(e=>e.kind==='damage'||e.kind==='commanderHit'))misses++;}});assert.ok(steering>0&&committed>10&&misses>0);});
test('lasers charge at the boss, use fixed actual endpoints and reward a late dodge',()=>{let tells=0,beams=0,safe=0;run(2,2,{observe:(s,b)=>{if(s.bossPattern==='laser'&&s.bossAction==='windup'&&s.bossAttack>0&&s.bossAttack<1)tells++;for(const l of s.lasers){assert.ok(l.width>0&&l.width<.5&&l.time<=.51&&l.endZ===-5);const old=b.lasers.find(p=>p.id===l.id);if(old){assert.equal(l.x,old.x);assert.equal(l.z,old.z);assert.equal(l.endX,old.endX);beams++;}if(s.ability===0&&!s.effects.some(e=>e.kind==='commanderHit'||e.kind==='damage'))safe++;}}});assert.ok(tells>50&&beams>10&&safe>10);});
function wounded(){let s=boss(2,2);for(let i=0;i<30*60&&s.phase==='boss'&&!s.canHeal;i++){core.step(1/60,0);s=snap();}assert.ok(s.canHeal);return s;}
test('manual commander healing consumes real troops, visible sacrifice slots and finite charges',()=>{const before=wounded();assert.equal(before.healCost,20);assert.ok(before.healAmount>=10&&before.healAmount<=25);assert.ok(core.heal());const after=snap();assert.equal(after.army,before.army-20);assert.equal(after.commanderHp,Math.min(before.commanderMaxHp,before.commanderHp+25));assert.equal(after.healUsesRemaining,1);assert.ok(after.effects.some(e=>e.kind==='heal'));assert.ok(after.effects.some(e=>e.kind==='troopSacrifice'));assert.ok(!after.effects.some(e=>e.kind==='troopDeath'));assert.equal(core.heal(),false);assert.equal(snap().army,after.army);core.pause(true);assert.equal(core.heal(),false);core.pause(false);});
function lastStand(){for(let level=0;level<3;level++){let s=run(2,level,{ability:false,stop:s=>s.phase==='boss'});for(let i=0;i<70*60&&s.phase==='boss';i++){core.step(1/60,0);s=snap();}if(s.phase==='lastStand')return s;}throw new Error('No public-control LastStand route reached.');}
test('fatal laser damage with surviving troops freezes for an explicit one-time revival choice',()=>{const before=lastStand();assert.ok(before.army>=31);assert.equal(before.commanderHp,0);assert.ok(before.reviveAvailable&&!before.reviveUsed);const frozen=persist(snap());assert.deepEqual(persist(advance(3,3)),frozen);assert.equal(core.activate(),false);assert.equal(core.heal(),false);assert.ok(core.revive());const s=snap();assert.equal(s.army,before.army-30);assert.equal(s.commanderHp,50);assert.ok(s.reviveUsed&&!s.reviveAvailable&&s.reviveProtection>1.4);assert.equal(s.phase,'boss');assert.ok(s.effects.some(e=>e.kind==='revive'));assert.ok(s.effects.some(e=>e.kind==='troopSacrifice'));assert.equal(core.revive(),false);assert.equal(core.declineRevive(),false);const safe=advance(1,3);assert.equal(safe.commanderHp,50);assert.equal(safe.army,s.army);const restored=start();assert.ok(!restored.reviveUsed);assert.equal(restored.healUsesRemaining,2);assert.equal(core.revive(),false);});
test('declining revival loses once without spending troops or silently resuming combat',()=>{lastStand();assert.ok(core.declineRevive());const s=snap();assert.equal(s.phase,'lost');assert.equal(s.army,0);assert.equal(s.commanderHp,0);assert.ok(s.effects.some(e=>e.kind==='commanderDeath'));assert.equal(core.declineRevive(),false);assert.equal(core.revive(),false);assert.deepEqual(persist(advance(3)),persist(s));});
test('measured enemy and roller envelopes never silently pass through the live formation',()=>{let bodies=0,rollers=0;for(const lane of[-2.8,0,2.8])run(2,2,{ability:false,controls:s=>s.phase==='boss'?route(s):lane,observe:s=>{if(s.phase!=='run')return;geometry.frames++;const units=[{x:s.x,z:0,r:.4},...s.formation.map(p=>({...p,r:.36}))];for(const t of s.targets){if(t.kind==='enemy'&&t.op===0){bodies++;geometry.bodySamples++;geometry.formationPairs+=units.length;const overlap=units.filter(p=>Math.abs(p.x-t.x)<t.size+p.r-.001&&Math.abs(p.z-t.z)<t.depth+p.r-.001).length;geometry.silentOverlapCount+=overlap;assert.equal(overlap,0);}if(t.kind==='hazard'){rollers++;geometry.rollerSamples++;geometry.formationPairs+=units.length;const overlap=units.filter(p=>Math.abs(p.x-t.x)<t.size*1.048+p.r-.001&&Math.abs(p.z-t.z)<.8+p.r-.001).length;geometry.silentOverlapCount+=overlap;assert.equal(overlap,0);}}}});assert.ok(bodies>500&&rollers>100);});
test('all pooled simulation values remain finite and bounded',()=>{for(let l=0;l<3;l++)run(0,l,{observe:s=>{assert.ok(s.targets.length<=256&&s.shots.length<=256&&s.enemyShots.length<=96&&s.pickups.length<=24&&s.effects.length<=192);for(const k of['time','x','powerTime','bossX','bossY','bossZ','travelDistance'])assert.ok(Number.isFinite(s[k]));for(const p of s.shots)assert.ok(Number.isFinite(p.dx)&&p.dz>0&&p.z<=28);}});});
test('effects drain once and250 retries clear all rank/power/pickup state',()=>{const reset=persist(start());core.step(.25,0);const a=snap(),b=snap();assert.equal(b.effects.length,0);assert.deepEqual(persist(a),persist(b));const memory=core.api.memory.buffer.byteLength;for(let i=0;i<250;i++){start(i%3,i%3,i%4);advance(2,1.8);core.pause(true);assert.deepEqual(persist(start()),reset);assert.equal(core.api.memory.buffer.byteLength,memory);core.step(1/60,0);assert.ok(snap().time>0);}});
const report={schema:4,scope:'Actual continuous-travel Assault browser adapter/current WASM. Automated normal controls; no Unreal, physical-device or first-time-player validation.',binary,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),memoryBytes:core.api.memory.buffer.byteLength,testedAt:new Date().toISOString(),winningRuns,geometry,tests:results.length,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results};fs.mkdirSync(path.join(root,'builds'),{recursive:true});fs.writeFileSync(path.join(root,'builds/rebuild-test-results.json'),JSON.stringify(report,null,2));console.log(`${report.passed}/${report.tests} passed.`);if(report.failed)process.exitCode=1;
