import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import Module from 'node:module';import {pathToFileURL} from 'node:url';import {points} from './measure_portrait_camera.mjs';
const deps=path.resolve('tools/asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const b=await esbuild.build({entryPoints:['tools/playable-preview/'+file],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[deps+'/node_modules'],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'framing-inline.cjs'));return m.exports;}
const {FormationFraming,commanderAnimationBounds}=await code('portrait-framing.ts'),{Battlefield}=await code('world.ts'),bounds=new T.Box3().setFromPoints(points),results=[];
// Parse retained geometry, skin and animation; skip texture upload in this CPU projection audit.
const {GLTFLoader}=await import(pathToFileURL(path.join(deps,'node_modules/three/examples/jsm/loaders/GLTFLoader.js')));const bytes=fs.readFileSync('delivery/playable/commander.glb'),jsonSize=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+jsonSize)),binary=bytes.subarray(28+jsonSize);json.materials=(json.materials??[]).map(()=>({}));json.images=[];json.textures=[];const encoded=Buffer.from(JSON.stringify(json)),padded=Buffer.concat([encoded,Buffer.alloc((4-encoded.length%4)%4,32)]),glb=Buffer.alloc(28+padded.length+binary.length);glb.writeUInt32LE(0x46546c67,0);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(padded.length,12);glb.writeUInt32LE(0x4e4f534a,16);padded.copy(glb,20);glb.writeUInt32LE(binary.length,20+padded.length);glb.writeUInt32LE(0x004e4942,24+padded.length);binary.copy(glb,28+padded.length);const hero=await new GLTFLoader().parseAsync(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.byteLength),'');
const commanderBounds=commanderAnimationBounds(hero.scene,hero.animations),sampled=[];
const transformedParent=new T.Group(),sibling=new T.Group();transformedParent.position.set(9,3,-7);transformedParent.rotation.set(.1,.3,.2);transformedParent.scale.set(1.2,.9,.8);hero.scene.position.set(.2,.1,-3.7);hero.scene.rotation.y=Math.PI;hero.scene.scale.setScalar(.95);transformedParent.add(hero.scene,sibling);transformedParent.updateMatrixWorld(true);const parentOrder=[...transformedParent.children],rootPosition=hero.scene.position.toArray(),rootRotation=hero.scene.quaternion.toArray(),rootScale=hero.scene.scale.toArray(),parentIndependent=commanderAnimationBounds(hero.scene,hero.animations);assert(parentIndependent.min.distanceTo(commanderBounds.min)<1e-8);assert(parentIndependent.max.distanceTo(commanderBounds.max)<1e-8);assert.deepEqual(transformedParent.children,parentOrder);assert.deepEqual(hero.scene.position.toArray(),rootPosition);assert.deepEqual(hero.scene.quaternion.toArray(),rootRotation);assert.deepEqual(hero.scene.scale.toArray(),rootScale);hero.scene.removeFromParent();hero.scene.position.set(0,0,0);hero.scene.quaternion.identity();hero.scene.scale.setScalar(1);
const mixer=new T.AnimationMixer(hero.scene);
for(const clip of hero.animations.filter(c=>['Run','Idle'].includes(c.name))){mixer.stopAllAction();mixer.clipAction(clip).reset().play();for(let frame=0;frame<8;frame++){mixer.setTime(clip.duration*(frame+.5)/8);hero.scene.updateMatrixWorld(true);hero.scene.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update();});const vertices=[];hero.scene.traverse(o=>{if(o.isMesh)for(let i=0;i<o.geometry.attributes.position.count;i++)vertices.push(o.getVertexPosition(i,new T.Vector3()).applyMatrix4(o.matrixWorld));});sampled.push({clip:clip.name,frame,vertices});}}
mixer.stopAllAction();const point=new T.Vector3(),matrix=new T.Matrix4(),position=new T.Vector3(),rotation=new T.Quaternion(),euler=new T.Euler(),troopScale=new T.Vector3(.432,.72,.72),heroScale=new T.Vector3(1.43,1.43,1.43);
const formation=x=>Array.from({length:24},(_,i)=>({index:i,x:T.MathUtils.clamp(x,-2.805,2.805)+(i%4-1.5)*.73,z:-(.75+Math.floor(i/4)*.48)}));
function setup(w,h){const camera=new T.PerspectiveCamera(30,w/h,.1,180),actor=Object.create(Battlefield.prototype);Object.assign(actor,{camera,canvas:{clientWidth:w,clientHeight:h},renderer:{setSize(){}}});actor.resize();const fit=new FormationFraming();fit.setBounds(bounds);fit.setCommanderBounds(commanderBounds);return {camera,fit,look:actor.cameraLookZ,distance:(5.05/Math.min(.45,camera.aspect))/Math.tan(T.MathUtils.degToRad(15))};}
function cameraBase(c,fov){c.camera.position.set(0,c.distance*.58,c.look+c.distance*.815);c.camera.lookAt(0,.1,c.look);c.camera.fov=fov;c.camera.updateProjectionMatrix();}
function margin(vertices,transform,camera,width){let minimum=Infinity;for(const p of vertices){point.copy(p).applyMatrix4(transform).project(camera);const px=(1+point.x)*width/2;minimum=Math.min(minimum,px,width-px);}return minimum;}
for(const[w,h]of[[420,933],[425,798],[375,667],[412,915],[352,782],[560,850]])for(const side of[-1,1]){
 const c=setup(w,h);let maxPan=0,minTroop=Infinity,minHero=Infinity;
 // Real maximum 5m/s steering followed by abrupt review/retry seek at the edge.
 for(let frame=0;frame<90;frame++){const x=side*Math.min(3,frame*5/60),f=formation(x);cameraBase(c,29.52);const pan=c.fit.update(c.camera,f,1/60,w,x);maxPan=Math.max(maxPan,Math.abs(pan));assert(Math.abs(pan)<=c.fit.maxPan);c.camera.position.x=pan;c.camera.lookAt(pan,.1,c.look);c.camera.position.x-=side*.225;c.camera.position.y+=.225;c.camera.updateMatrixWorld(true);const edge=f[side>0?23:20];matrix.compose(position.set(edge.x,.105,-edge.z),rotation.setFromEuler(euler.set(0,Math.PI+side*.265,-side*.12)),troopScale);minTroop=Math.min(minTroop,margin(points,matrix,c.camera,w));matrix.compose(position.set(x,.055,0),rotation.setFromEuler(euler.set(.085,Math.PI+side*.20,-side*.148)),heroScale);minHero=Math.min(minHero,margin(sampled[frame%sampled.length].vertices,matrix,c.camera,w));}
 for(const reviving of[false,true])for(const shakeY of[-.225,.225]){c.fit.reset();cameraBase(c,reviving?27.27:29.52);const f=formation(side*3),pan=c.fit.update(c.camera,f,0,w,side*3,reviving);maxPan=Math.max(maxPan,Math.abs(pan));c.camera.position.x=pan;c.camera.lookAt(pan,.1,c.look);c.camera.position.x-=side*.225;c.camera.position.y+=shakeY;c.camera.updateMatrixWorld(true);
  for(const index of[side>0?3:0,side>0?23:20]){const troop=f[index];for(const phase of[-1,1]){matrix.compose(position.set(troop.x,.105,-troop.z),rotation.setFromEuler(euler.set(0,Math.PI+side*.23+phase*.035,-side*.12)),troopScale);minTroop=Math.min(minTroop,margin(points,matrix,c.camera,w));}}
  for(const sample of sampled){matrix.compose(position.set(side*3,.055,0),rotation.setFromEuler(euler.set(reviving?.75:.085,Math.PI+side*.20,-side*.148)),heroScale);minHero=Math.min(minHero,margin(sample.vertices,matrix,c.camera,w));}
  const frozen=c.fit.pan;c.fit.update(c.camera,[],0,w,-side*3);assert.equal(c.fit.pan,frozen);assert.equal(c.camera.fov,reviving?27.27:29.52);
 }
 assert(minTroop>=2,`Troop clipped ${w}x${h} side${side}: ${minTroop}px`);assert(minHero>=2,`Commander clipped ${w}x${h} side${side}: ${minHero}px`);results.push({w,h,side,maxPanMetres:maxPan,minTroopVertexMarginPixels:minTroop,minCommanderVertexMarginPixels:minHero});
}
const receipt={scope:'Actual retained troop and skinned commander vertices in both Run and Idle, half-step animation samples, exact runtime resize, both edges, new yaw/bank poses, .225m X/Y shake, upgrade and revival zoom, instant dt0 replay reset and preserved paused camera. CPU geometry proof; browser follows separately.',troopVertices:points.length,commanderVertices:sampled[0].vertices.length,commanderAnimationSamples:sampled.length,transformedParentIsolation:true,commanderEnvelope:{min:commanderBounds.min.toArray(),max:commanderBounds.max.toArray()},results,passed:true,generatedAt:new Date().toISOString()};fs.writeFileSync('builds/portrait-framing-checks.json',JSON.stringify(receipt,null,2));console.log('PASS 12 portrait/desktop edge cases including 425x798, full strafe, actual animated commander, revival zoom, shake, instant reset and pause.');console.log(JSON.stringify(results,null,2));
