import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import Module,{createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const deps=path.resolve('tools/asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const b=await esbuild.build({entryPoints:['tools/playable-preview/'+file],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[deps+'/node_modules'],write:false}),m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'commander-motion-test.cjs'));return m.exports;}
const {CommanderLocomotion}=await code('commander-locomotion.ts'),{commanderAnimationBounds}=await code('portrait-framing.ts');
const {GLTFLoader}=await import(pathToFileURL(path.join(deps,'node_modules/three/examples/jsm/loaders/GLTFLoader.js')));
async function load(file){const bytes=fs.readFileSync(file),n=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+n)),binary=bytes.subarray(28+n);json.materials=(json.materials??[]).map(()=>({}));json.images=[];json.textures=[];const encoded=Buffer.from(JSON.stringify(json)),padded=Buffer.concat([encoded,Buffer.alloc((4-encoded.length%4)%4,32)]),glb=Buffer.alloc(28+padded.length+binary.length);glb.writeUInt32LE(0x46546c67,0);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(padded.length,12);glb.writeUInt32LE(0x4e4f534a,16);padded.copy(glb,20);glb.writeUInt32LE(binary.length,20+padded.length);glb.writeUInt32LE(0x004e4942,24+padded.length);binary.copy(glb,28+padded.length);return new GLTFLoader().parseAsync(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.byteLength),'');}

const gltf=await load('delivery/playable/commander.glb'),model=gltf.scene,envelope=commanderAnimationBounds(model,gltf.animations),motion=new CommanderLocomotion(model,gltf.animations);let body;model.traverse(o=>{if(!body&&o.isSkinnedMesh)body=o;});
const rest=body.geometry.attributes.position,neutral={dt:1/60,forward:false,lateralVelocity:0,active:true,held:false,recoil:0};
function vertices(){model.updateWorldMatrix(true,true);model.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update();});const values=new Float32Array(rest.count*3),point=new T.Vector3();for(let i=0;i<rest.count;i++){body.getVertexPosition(i,point);values[i*3]=point.x;values[i*3+1]=point.y;values[i*3+2]=point.z;}return values;}
function difference(a,b,select=()=>true){let maximum=0;for(let i=0;i<rest.count;i++)if(select(i))maximum=Math.max(maximum,Math.hypot(a[i*3]-b[i*3],a[i*3+1]-b[i*3+1],a[i*3+2]-b[i*3+2]));return maximum;}
let passed=0,failed=0;const checks=[],measurements={};function test(name,fn){try{fn();passed++;checks.push({name,pass:true});console.log('PASS '+name);}catch(e){failed++;checks.push({name,pass:false,error:e.message});console.error('FAIL '+name+' '+e.stack);}}
const poseBox=new T.Box3(),point=new T.Vector3();let envelopeOverflow=0;
function recordBounds(v){for(let i=0;i<v.length;i+=3){point.set(v[i],v[i+1],v[i+2]);poseBox.expandByPoint(point);envelopeOverflow=Math.max(envelopeOverflow,envelope.distanceToPoint(point));}}
test('ordinary locomotion drives the actual retained skin rather than merely changing the parent transform',()=>{motion.reset();const originalRoot=model.matrix.toArray(),a=vertices();for(let i=0;i<18;i++)motion.update({...neutral,forward:true});const b=vertices();measurements.legMotion=difference(a,b,i=>rest.getY(i)<.8&&Math.abs(rest.getX(i))>.17);measurements.armMotion=difference(a,b,i=>rest.getY(i)>.8&&rest.getY(i)<1.5&&Math.abs(rest.getX(i))>.5);assert(measurements.legMotion>.08);assert(measurements.armMotion>.035);assert.deepEqual(model.matrix.toArray(),originalRoot);assert(motion.stats.walkingWeight>.95);recordBounds(b);});
test('left and right commands alter real leg placement with identical camera and root transforms',()=>{const frames=[];for(const direction of[-1,1]){motion.reset();for(let i=0;i<24;i++)motion.update({...neutral,lateralVelocity:direction*5});frames.push(vertices());recordBounds(frames.at(-1));assert(Math.abs(motion.stats.strafe)>.98);}measurements.lateralLegMotion=difference(frames[0],frames[1],i=>rest.getY(i)<.85&&Math.abs(rest.getX(i))>.17);assert(measurements.lateralLegMotion>.07);});
test('zero dt freezes actual skin matrices, pose phase and blend even when controls change',()=>{const a=vertices(),stats=JSON.stringify(motion.stats);for(let i=0;i<100;i++)motion.update({...neutral,dt:0,forward:true,lateralVelocity:-5,recoil:1});assert.deepEqual(vertices(),a);assert.equal(JSON.stringify(motion.stats),stats);});
test('held combat settles without accumulating additive rotations and idle remains bounded',()=>{for(let i=0;i<300;i++)motion.update({...neutral,held:true,lateralVelocity:5});assert(motion.stats.walkingWeight<1e-12);assert(Math.abs(motion.stats.strafe)<1e-12);const start=vertices();for(let i=0;i<1200;i++){motion.update({...neutral,held:true,lateralVelocity:-5});if(i%60===0)recordBounds(vertices());}measurements.heldIdleDrift=difference(start,vertices());assert(measurements.heldIdleDrift<.04);assert(motion.stats.walkingWeight<1e-12);});
test('repeated reset restores the same actual Idle skin and does not compound old recoil or strafing',()=>{motion.reset();const expected=vertices();for(let run=0;run<20;run++){for(let i=0;i<20;i++)motion.update({...neutral,forward:true,lateralVelocity:run%2?5:-5,recoil:1});motion.reset();assert.deepEqual(vertices(),expected);}assert.equal(motion.stats.walkingWeight,0);assert.equal(motion.stats.strafe,0);});
test('full Run, left/right side gait and maximum recoil remain inside the published camera envelope',()=>{for(const direction of[-1,0,1]){motion.reset();for(let frame=0;frame<150;frame++){motion.update({...neutral,forward:direction===0,lateralVelocity:direction*5,recoil:frame%30<15?1:0});if(frame%6===0)recordBounds(vertices());}}measurements.envelopeOverflowMetres=envelopeOverflow;assert(envelopeOverflow<=.002,`Commander exceeds published framing envelope by ${envelopeOverflow.toFixed(4)}m`);});
fs.writeFileSync('builds/commander-locomotion-checks.json',JSON.stringify({scope:'Actual retained commander GLB skin vertex regression for ordinary locomotion adapter. CPU checks are not proof of normal-game WebGL appearance.',passed,failed,checks,measurements,observedBounds:{min:poseBox.min.toArray(),max:poseBox.max.toArray()},publishedEnvelope:{min:envelope.min.toArray(),max:envelope.max.toArray()},generatedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({passed,failed,measurements},null,2));if(failed)process.exitCode=1;
