#include <array>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <set>
#define private public
#include "AssaultSimulation.h"
#undef private
#include "CampaignEncounters.h"
using namespace mech::assault;
static int Checks=0;
static void Check(bool V,const char* Text){if(!V){std::fprintf(stderr,"FAIL %s\n",Text);std::exit(1);}++Checks;}
static void Empty(Battle& B){for(auto& T:B.targets)T.active=false;B.spawned=~uint64_t(0);B.ConsumeEffects();}
static void Boss(Battle& B){B.Start(Relic::Shield,5);B.phase=Phase::Boss;B.actIndex=2;B.travelDistance=B.travelGoal;B.bossZ=12;B.bossX=0;B.bossY=.85;Empty(B);mech::boss_pose::Pose P;P.position={0,.85,-12};B.bossFrame=B.previousBossFrame=mech::boss_pose::BuildFrame(P,0);B.poseDriver.Reset(P);}
int main(){
 {Battle B;B.Start(Relic::Shield,5);Check(B.duration==198&&std::abs(B.travelGoal-732.6)<1e-8,"single march has one 198-second travel objective");Check(B.actIndex==0&&B.StageLevel()==0&&B.StageProgress()==0,"campaign begins in zone zero");Check(!B.ChooseReward(0),"no reward before final boss");}
 {Battle B;B.Start(Relic::Shield,5);Empty(B);B.Recruit(24);B.commanderHp=73;B.weapon=3;B.weaponPower=WeaponPower::Cannons;B.powerTime=9;B.relicTime={2,1.2,3};B.relicEnergy={25,34,45};B.combatPower=CombatPower::Salvo;B.combatPowerTime=.8;B.DropPickup(1.8,10,PickupKind::Health,99);B.SpawnEnemyShot(-1.8,18,0,7,.2,5,ProjectileKind::Shell,false);B.Fire();
  const int Army=B.army,Shots=B.ShotCount(),Hostile=B.EnemyShotCount(),Pickups=B.PickupCount(),Id=B.nextShotId,Epoch=B.bossEpoch;const auto Timers=B.relicTime;
  for(int Zone:{1,2}){B.ConsumeEffects();B.travelDistance=mech::campaign::ZoneBounds[Zone]*3.7;B.UpdateZone();Check(B.phase==Phase::Run&&B.actIndex==Zone&&B.StageLevel()==(Zone==1?3:4),"zone crossing remains live traversal");Check(B.army==Army&&B.commanderHp==73&&B.weapon==3&&B.powerTime==9&&B.relicTime==Timers&&B.combatPowerTime==.8,"zone crossing preserves resources and active powers");Check(B.ShotCount()==Shots&&B.EnemyShotCount()==Hostile&&B.PickupCount()==Pickups&&B.nextShotId==Id&&B.bossEpoch==Epoch,"zone crossing preserves live objects and IDs");Check(B.effectCount==1&&B.effects[0].kind==EffectKind::ActStart&&B.effects[0].value==Zone,"one zone presentation event without boss or reward");Check(B.StageProgress()==0&&std::abs(B.travelGoal-732.6)<1e-8,"zone-local progress resets but global goal does not");B.UpdateZone();Check(B.effectCount==1,"zone event does not repeat");}
 }
 {std::array<int,3> Rollers{},Engineers{},Batteries{},Health{},Gates{};double Previous=-1;for(const auto& E:mech::campaign::IronMarch){Check(E.at>=Previous,"campaign timeline is chronologically authored");Previous=E.at;const int Z=E.at<62?0:E.at<128?1:2;Rollers[Z]+=E.kind==mech::campaign::Kind::Roller;Engineers[Z]+=E.kind==mech::campaign::Kind::Archetype&&E.variant==4;Batteries[Z]+=E.kind==mech::campaign::Kind::Battery;Health[Z]+=E.kind==mech::campaign::Kind::Health;Gates[Z]+=E.kind==mech::campaign::Kind::Gate;}Check(Rollers[0]>=3&&Engineers[1]>=2&&Batteries[2]>0&&Health[2]>=2&&Gates[2]>=2,"zones have distinct dodge, support-crossfire and fortified recovery beats");}
 for(int Bonus:{0,1}){Battle B;B.Start(Relic::StormBattery,5);Empty(B);B.rewardEndurance=Bonus;B.relicEnergy[2]=100;B.ActivateRelic(Relic::StormBattery);std::set<int> Rockets;int Normal=0;double NormalDamage=-1;for(int I=0;I<420;++I){for(auto& S:B.shots)if(S.active){if(S.battery){Rockets.insert(S.id);Check(S.kind==FriendlyKind::Salvo&&S.y>0&&std::isfinite(S.dy),"battery emits real 3D salvo rounds");}else {++Normal;NormalDamage=S.damage;}S.active=false;}B.Advance(1./60,0);B.ConsumeEffects();}Check(int(Rockets.size())==(Bonus?22:18),"finite paired rocket budget follows actual power duration");Check(Normal>0&&NormalDamage==1.5,"ordinary bullet damage has no old Overdrive multiplier");Check(B.relicTime[2]==0,"battery timer expires");}
 {Battle A,B;A.Start(Relic::StormBattery,5);B.Start(Relic::StormBattery,5);Empty(A);Empty(B);B.relicEnergy[2]=100;B.ActivateRelic(Relic::StormBattery);int CountA=0,CountB=0;for(int I=0;I<180;++I){for(auto& S:A.shots)if(S.active){++CountA;S.active=false;}for(auto& S:B.shots)if(S.active){CountB+=!S.battery;S.active=false;}A.Advance(1./60,0);B.Advance(1./60,0);A.ConsumeEffects();B.ConsumeEffects();}Check(CountA==CountB,"battery does not speed up ordinary fire cadence");}
 {Battle B;B.Start(Relic::StormBattery,5);Empty(B);B.relicEnergy[2]=100;Check(B.ActivateRelic(Relic::StormBattery)&&B.barragePairs==1,"battery deploys first real pair on activation");auto Shots=B.shots;const auto T=B.relicTime;B.paused=true;B.Advance(1,3);Check(B.relicTime==T&&B.barragePairs==1&&B.shots[0].z==Shots[0].z,"pause holds battery and projectiles");B.Start(Relic::StormBattery,5);Check(B.barragePairs==0&&B.barrageClock==0&&B.ShotCount()==0&&!B.RelicActive(Relic::StormBattery),"retry clears battery state");}
 {double Baseline=0;for(int Hz:{60,30,120}){Battle B;B.Start(Relic::StormBattery,5);Empty(B);B.relicEnergy[2]=100;B.ActivateRelic(Relic::StormBattery);for(int I=0;I<Hz*2;++I){B.Advance(1./Hz,1.5);B.ConsumeEffects();}double Sum=B.barragePairs+B.relicTime[2]+B.x;for(const auto& S:B.shots)if(S.active)Sum+=S.x+S.y+S.z+S.id;if(Hz==60)Baseline=Sum;else Check(std::abs(Sum-Baseline)<1e-8,"battery timing and trajectories agree across presentation frame rates");}}
 {Battle B;Boss(B);B.relicEnergy[2]=100;B.ActivateRelic(Relic::StormBattery);for(const auto& S:B.shots)if(S.active){Check(S.spatial&&S.epoch==B.bossEpoch&&S.aimRegion<2,"battery boss round commits valid initial part and epoch");Check(std::abs(std::abs(S.x)-.68)<1e-8&&S.y==2.11&&S.z==.92,"battery launches at physical shoulder tips");}const int Epoch=B.shots[0].epoch,Region=B.shots[0].aimRegion;B.bossEpoch++;B.MoveShots(.016);Check(B.shots[0].epoch==Epoch&&B.shots[0].aimRegion==Region,"battery never retargets a new boss stage in flight");}
 {Battle B;Boss(B);B.bossPartsMask=15;for(int I=0;I<4;++I)B.regionHp[I]=0;B.UpdateBossHealth();B.bossY=B.GroundY();B.bossAge=9;B.bossClock=.2;B.SyncPosePosition();B.previousBossFrame=B.bossFrame;const double BeforeX=B.bossX,BeforeZ=B.bossZ;B.BossStep(1./60);B.UpdatePose(1./60);Check(B.bossY<.05&&std::abs(B.bossX-BeforeX)>.025&&std::abs(B.bossZ-BeforeZ)>.025,"boosterless Tyrant makes faster real grounded lateral and depth steps");Check(B.bossAction!=BossAction::Evade&&B.bossEvadeTime==0&&std::abs(B.bossFrame.pose.legPitch[0])>0,"grounded movement has real leg pose without jet evade");B.bossLaneLocked=true;B.bossClock=2;const double X=B.bossX,Z=B.bossZ;B.BossStep(1./60);Check(B.bossX==X&&B.bossZ==Z,"grounded Tyrant plants for committed attack");}
 {Battle B;Boss(B);B.BeginBossDeath();for(int I=0;I<151;++I)B.Advance(1./60,0);Check(B.phase==Phase::Reward&&B.actIndex==2,"only final boss destruction reaches reward");const double Distance=B.travelDistance;Check(B.ChooseReward(2)&&B.phase==Phase::Won&&B.travelDistance==Distance,"one final imprint ends the assault");Check(!B.ChooseReward(1),"final imprint cannot be claimed twice");}
 std::printf("%d single-siege mechanics checks passed.\n",Checks);
}
