import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import Module,{createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function source(file){const b=await esbuild.build({entryPoints:[path.join(here,file)],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'unbroken-render-check.cjs'));return m.exports;}
const {EnemyArchetypes,enemyDesigns}=await source('enemy-archetypes.ts'),{BossRigAdapter}=await source('boss-rig-adapter.ts'),{RevivalScene}=await source('revival-scene.ts');
const scene=new T.Scene(),enemies=new EnemyArchetypes(scene);let passed=0,failed=0;const checks=[];
function test(name,fn){try{fn();passed++;checks.push({name,passed:true});console.log('PASS '+name);}catch(e){failed++;checks.push({name,passed:false,error:e.message});console.error('FAIL '+name+' '+e.message);}}
const target=n=>({id:n,archetype:n,x:0,z:10,stunTime:0,hit:0,shieldHp:3,shieldMax:3,blockFlash:0,skillState:0,aimX:0,fireState:'idle'});
test('four distinct original silhouettes fit their authored neutral collision footprint',()=>{for(let kind=1;kind<=4;kind++){enemies.begin();enemies.add(target(kind),0,0,0,0);enemies.end();const bounds=new T.Box3(),matrix=new T.Matrix4();for(const d of enemies.designs)for(const b of d.batches)if(b.mesh.count){b.mesh.getMatrixAt(0,matrix);bounds.union(b.mesh.geometry.boundingBox.clone().applyMatrix4(matrix));}const size=bounds.getSize(new T.Vector3()),design=enemyDesigns[kind-1];assert(size.x<=design.width+.0001,`${design.name} width${size.x}`);assert(size.z<=design.depth+.0001,`${design.name} depth${size.z}`);assert(size.y>1);assert(Number.isFinite(size.x));}assert(new Set(enemies.stats.triangles).size===4);});
test('posed muzzle follows actual yaw, recoil and hover, and remains attached to a real weapon',()=>{for(let kind=1;kind<=4;kind++){const t=target(kind);enemies.begin();enemies.add(t,1,0,0,0);const a=enemies.muzzle(t);enemies.begin();enemies.add({...t,x:2,z:12,fireState:'fire'},1,0,0,.35);const b=enemies.muzzle(t);assert(Math.abs(b.x-a.x-2)>.005);assert(b.z<-10);assert(b.y>.5&&b.y<3);}});
test('three-hit enemy shield visibly disappears only at zero guard',()=>{enemies.begin();enemies.add(target(1),0,0,0,0);enemies.end();const mesh=enemies.designs[0].batches.find(b=>b.joint==='shield').mesh,m=new T.Matrix4();mesh.getMatrixAt(0,m);assert(Math.abs(m.determinant())>.01);enemies.begin();enemies.add({...target(1),shieldHp:0},0,0,0,0);enemies.end();mesh.getMatrixAt(0,m);assert(Math.abs(m.determinant())<1e-9);});
test('joint animation rotates about hips and bounded pools do not allocate per frame',()=>{const geometries=enemies.root.children.map(m=>m.geometry);for(let frame=0;frame<600;frame++){enemies.begin();for(let i=0;i<120;i++)enemies.add({...target(i%4+1),id:i+1,x:(i%5)-2},frame/60,2,3,.1);enemies.end();assert(enemies.root.children.every(m=>m.count<=24));}assert.deepEqual(enemies.root.children.map(m=>m.geometry),geometries);assert.equal(enemies.stats.textures,1);});
const rootBoss=new T.Group(),arm=new T.Group();arm.name='Arm_L';const mesh=new T.Mesh(new T.BoxGeometry(.5,.5,.5),new T.MeshStandardMaterial({color:0x572b22}));arm.add(mesh);rootBoss.add(arm);scene.add(rootBoss);const original=mesh.material,adapter=new BossRigAdapter(rootBoss,scene),region={id:'cannonL',x:1,y:2,z:10,radiusX:.5,radiusY:.5,radiusZ:.5,quaternion:[0,0,0,1],hp:100,maxHp:100,vulnerable:true};
test('entire real boss component flashes on confirmed damaging hit and resets its own materials',()=>{adapter.updateRegions([region],true,[],0,0);const idle=mesh.material.emissiveIntensity;adapter.notifyHit('cannonL',12);adapter.updateRegions([region],true,[],0,.016);assert(mesh.material.emissiveIntensity>idle*3);adapter.updateRegions([region],true,[],0,0);const held=mesh.material.emissiveIntensity;adapter.updateRegions([region],true,[],0,0);assert.equal(mesh.material.emissiveIntensity,held);for(let i=0;i<20;i++)adapter.updateRegions([region],true,[],0,.016);assert(mesh.material.emissiveIntensity<.3);adapter.reset();assert.equal(mesh.material.emissiveIntensity,original.emissiveIntensity);});
test('confirmed reactor damage washes the entire measured oval face with correct posed depth offset',()=>{adapter.reset();const quaternion=new T.Quaternion().setFromEuler(new T.Euler(.11,Math.PI+.20,-.07)).toArray(),core={...region,id:'core',x:.4,y:4.7,z:11,radiusX:.349,radiusY:.506,radiusZ:.100,quaternion};adapter.updateRegions([core],true,[],0,0);assert(!adapter.reactorFlash.visible);adapter.notifyHit('core',0);adapter.updateRegions([core],true,[],0,0);assert(!adapter.reactorFlash.visible);adapter.notifyHit('core',12);adapter.updateRegions([core],true,[],0,.016);const flash=adapter.reactorFlash;assert(flash.visible);assert.equal(flash.geometry.type,'CircleGeometry');assert.deepEqual(flash.scale.toArray(),[core.radiusX,core.radiusY,1]);assert(flash.quaternion.angleTo(new T.Quaternion(...quaternion))<1e-7);const normal=new T.Vector3(0,0,-1).applyQuaternion(flash.quaternion),expected=new T.Vector3(core.x,core.y,-core.z).addScaledVector(normal,core.radiusZ+.012);assert(flash.position.distanceTo(expected)<1e-10);assert.equal(flash.geometry.parameters.radius,1);assert(flash.material.opacity>.4&&flash.material.opacity<=.5);assert(flash.material.depthTest&&!flash.material.depthWrite&&flash.material.polygonOffset);const opacity=flash.material.opacity,position=flash.position.toArray();for(let i=0;i<30;i++)adapter.updateRegions([core],true,[],0,0);assert.equal(flash.material.opacity,opacity);assert.deepEqual(flash.position.toArray(),position);for(let i=0;i<20;i++)adapter.updateRegions([core],true,[],0,.016);assert(!flash.visible);adapter.notifyHit('core',5);adapter.updateRegions([{...core,vulnerable:false}],true,[],0,0);assert(!flash.visible);adapter.updateRegions([core],false,[],0,0);assert(!flash.visible);adapter.reset();assert(!flash.visible&&flash.material.opacity===0);});
test('blocked boss hits do not flash false damage and disposal restores original material',()=>{adapter.reset();adapter.notifyHit('cannonL',0);adapter.updateRegions([region],true,[],0,.016);assert(mesh.material.emissiveIntensity<.3);adapter.dispose();assert.equal(mesh.material,original);});
const revival=new RevivalScene(scene);
test('revival geometry uses actual 1.5-second timer and remains stable while paused',()=>{revival.update(1.5,1);assert(revival.root.visible);const before=revival.root.children.map(m=>m.isInstancedMesh?Array.from(m.instanceMatrix.array):m.matrix.toArray());revival.update(1.5,1);assert.deepEqual(revival.root.children.map(m=>m.isInstancedMesh?Array.from(m.instanceMatrix.array):m.matrix.toArray()),before);revival.update(.5,1);assert(revival.cameraStrength>0);revival.update(0,1);assert(!revival.root.visible);assert.equal(revival.cameraStrength,0);revival.dispose();});
const stats=enemies.stats;enemies.dispose();test('model cleanup releases only owned batches and textures',()=>assert(!scene.children.includes(enemies.root)));
fs.writeFileSync(path.join(root,'builds/unbroken-models-review.json'),JSON.stringify({scope:'CPU real mesh bounds, posed emitters, shields, material flashes, revival timeline and bounded repeated allocations; rendered appearance checked separately',passed,failed,stats,checks,generatedAt:new Date().toISOString()},null,2));if(failed)process.exitCode=1;
