import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import Module,{createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const root=process.cwd(),deps=path.resolve('tools/asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
const bundle=await esbuild.build({entryPoints:['tools/playable-preview/animated-troop-crowd.ts'],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[deps+'/node_modules'],write:false}),module=new Module('crowd-test');module.paths=Module._nodeModulePaths(deps);module._compile(bundle.outputFiles[0].text,path.join(deps,'crowd-test.cjs'));const {AnimatedTroopCrowd}=module.exports;
const {GLTFLoader}=await import(pathToFileURL(path.join(deps,'node_modules/three/examples/jsm/loaders/GLTFLoader.js')));
async function load(file){const bytes=fs.readFileSync(file),n=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+n)),binary=bytes.subarray(28+n);json.materials=(json.materials??[]).map(()=>({}));json.images=[];json.textures=[];const encoded=Buffer.from(JSON.stringify(json)),padded=Buffer.concat([encoded,Buffer.alloc((4-encoded.length%4)%4,32)]),glb=Buffer.alloc(28+padded.length+binary.length);glb.writeUInt32LE(0x46546c67,0);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(padded.length,12);glb.writeUInt32LE(0x4e4f534a,16);padded.copy(glb,20);glb.writeUInt32LE(binary.length,20+padded.length);glb.writeUInt32LE(0x004e4942,24+padded.length);binary.copy(glb,28+padded.length);return new GLTFLoader().parseAsync(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.byteLength),'');}
const [troop,commander]=await Promise.all([load('delivery/playable/troop.glb'),load('delivery/playable/commander.glb')]);let troopMesh;troop.scene.updateMatrixWorld(true);troop.scene.traverse(o=>{if(!troopMesh&&o.isMesh)troopMesh=o;});const geometry=troopMesh.geometry.clone().applyMatrix4(troopMesh.matrixWorld),sourcePosition=[...geometry.attributes.position.array],sourceUV=[...geometry.attributes.uv.array],scene=new T.Scene(),started=performance.now(),crowd=new AnimatedTroopCrowd(scene,geometry,troopMesh.material,commander.scene,commander.animations),bakeMilliseconds=performance.now()-started;
let passed=0,failed=0;const checks=[];function test(name,fn){try{fn();passed++;checks.push({name,pass:true});console.log('PASS '+name);}catch(error){failed++;checks.push({name,pass:false,error:error.message});console.error('FAIL '+name+' '+error.stack);}}
const formation=Array.from({length:24},(_,index)=>({index,x:(index%4-1.5)*.73,z:-(.75+Math.floor(index/4)*.48)})),motion={dt:1/60,time:0,marching:true,strafe:0};
test('accepted troop topology, UVs, and source assets are preserved; weights match the retained commander surface',()=>{assert.deepEqual([...crowd.mesh.geometry.attributes.position.array],sourcePosition);assert.deepEqual([...crowd.mesh.geometry.attributes.uv.array],sourceUV);assert.deepEqual([...geometry.attributes.position.array],sourcePosition);assert.equal(crowd.stats.vertices,4582);assert.equal(crowd.stats.frames,84);assert(crowd.transfer.maxDistance<.13);assert(crowd.transfer.meanDistance<.03);assert(crowd.bounds.max.y>1.8);assert(commander.scene.children.length>0);});
let legMotion=0,armMotion=0;
test('real retained skin gait moves legs and arms independently, not a rigid mesh bob',()=>{const p=geometry.attributes.position;for(let i=0;i<p.count;i++){const a=crowd.vertexAt(i,6,0,1),b=crowd.vertexAt(i,18,0,1),distance=a.distanceTo(b);if(p.getY(i)<.75&&Math.abs(p.getX(i))>.17)legMotion=Math.max(legMotion,distance);if(p.getY(i)>.8&&p.getY(i)<1.5&&Math.abs(p.getX(i))>.5)armMotion=Math.max(armMotion,distance);}assert(legMotion>.12,`Leg motion ${legMotion}`);assert(armMotion>.06,`Arm motion ${armMotion}`);});
let lateralLegMotion=0;
test('left and right gait banks contain different actual leg placement, not merely a rotated forward Run',()=>{const p=geometry.attributes.position;for(let i=0;i<p.count;i++){if(p.getY(i)>.75||Math.abs(p.getX(i))<.17)continue;const left=crowd.vertexAt(i,6,0,1,new T.Vector3(),-1),right=crowd.vertexAt(i,6,0,1,new T.Vector3(),1);lateralLegMotion=Math.max(lateralLegMotion,Math.abs(left.x-right.x));}assert(lateralLegMotion>.15,`Lateral foot separation ${lateralLegMotion}`);const shader={uniforms:{},vertexShader:'#include <common>\n#include <begin_vertex>',fragmentShader:''};crowd.mesh.material.onBeforeCompile(shader);assert(shader.vertexShader.includes('running=mix(running,sidestep,abs(crowdPose.w))'));});
test('marching enables pose deformation on all real units with staggered phases',()=>{crowd.update(formation,motion);assert.equal(crowd.mesh.count,24);assert.equal(crowd.stats.poses,24);const poses=crowd.mesh.geometry.attributes.crowdPose;assert(poses.getZ(0)>.99);assert.notEqual(poses.getX(0),poses.getX(1));assert.equal(scene.children.length,1);});
test('sideways movement independently triggers real gait; stationarity blends into armed Idle',()=>{crowd.reset();for(let i=0;i<25;i++)crowd.update(formation.map(p=>({...p,x:p.x+i*.05})),{...motion,marching:false,strafe:1});const pose=crowd.mesh.geometry.attributes.crowdPose;assert(pose.getZ(0)>.95);const x=pose.getX(0);crowd.update(formation.map(p=>({...p,x:p.x+1.25})),{...motion,marching:false,strafe:1});assert.notEqual(pose.getX(0),x);const held=formation.map(p=>({...p,x:p.x+1.25}));for(let i=0;i<90;i++)crowd.update(held,{...motion,marching:false,strafe:0});assert(pose.getZ(0)<.001);});
test('pause freezes every per-instance matrix and pose frame',()=>{crowd.update(formation,motion);const matrices=[...crowd.mesh.instanceMatrix.array],poses=[...crowd.mesh.geometry.attributes.crowdPose.array];for(let i=0;i<100;i++)crowd.update(formation,{...motion,dt:0});assert.deepEqual([...crowd.mesh.instanceMatrix.array],matrices);assert.deepEqual([...crowd.mesh.geometry.attributes.crowdPose.array],poses);});
test('held clashes, rewards and revival freeze gait frames, blends and stance despite elapsed render time',()=>{crowd.reset();crowd.update(formation,motion);const matrices=[...crowd.mesh.instanceMatrix.array],poses=[...crowd.mesh.geometry.attributes.crowdPose.array];for(let i=0;i<80;i++)crowd.update(formation,{...motion,dt:.05,time:i*.05,marching:false,strafe:1,held:true});assert.deepEqual([...crowd.mesh.instanceMatrix.array],matrices);assert.deepEqual([...crowd.mesh.geometry.attributes.crowdPose.array],poses);});
test('casualties remove real displayed slots and retain survivor animation without cosmetic respawning',()=>{crowd.update(formation,motion);const survivor=crowd.poses.get(0),rearSurvivor=crowd.poses.get(23);crowd.update(formation.filter(p=>p.index!==5),{...motion,dt:0});assert(!crowd.poses.has(5));assert.equal(crowd.poses.get(23),rearSurvivor);assert.equal(crowd.mesh.count,23);crowd.update(formation.slice(0,7),{...motion,dt:0});assert.equal(crowd.mesh.count,7);assert.equal(crowd.stats.poses,7);assert.equal(crowd.poses.get(0),survivor);assert(!crowd.poses.has(23));crowd.update([],{...motion,dt:0});assert.equal(crowd.mesh.count,0);assert.equal(crowd.stats.poses,0);});
test('shadow and lit shaders read the same real animation atlas; normals deform with the surface',()=>{const shader=()=>({uniforms:{},vertexShader:'#include <common>\n#include <beginnormal_vertex>\n#include <begin_vertex>',fragmentShader:''}),lit=shader(),depth=shader(),distance=shader();crowd.mesh.material.onBeforeCompile(lit);crowd.mesh.customDepthMaterial.onBeforeCompile(depth);crowd.mesh.customDistanceMaterial.onBeforeCompile(distance);for(const s of [lit,depth,distance]){assert(s.vertexShader.includes('transformed=crowdDeform(crowdPositions)'));assert.equal(s.uniforms.crowdPositions.value,crowd.positionTexture);assert(!s.vertexShader.includes('\\n'));}assert(lit.vertexShader.includes('objectNormal=normalize(crowdDeform(crowdNormals))'));assert.equal(crowd.positionTexture.type,T.HalfFloatType);});
test('baked foot surfaces never sink beneath the road and remain inside published camera bounds',()=>{for(const strafe of[-1,0,1])for(let frame=0;frame<24;frame++){let minimum=Infinity;for(let i=0;i<4582;i++){const p=crowd.vertexAt(i,frame,0,1,new T.Vector3(),strafe);minimum=Math.min(minimum,p.y);assert(crowd.bounds.containsPoint(p));}assert(minimum>=-.00001);assert(minimum<.08);}});
test('3000 updates/retries retain one fixed instanced geometry, two pose textures, and bounded slots',()=>{const geo=crowd.mesh.geometry,pos=crowd.positionTexture,norm=crowd.normalTexture,huge=Array.from({length:120},(_,index)=>({index,x:index%4,z:-1}));for(let i=0;i<3000;i++){crowd.update(huge,motion);assert(crowd.stats.poses<=64);assert.equal(crowd.mesh.count,64);if(i%15===0)crowd.reset();}assert.equal(crowd.mesh.geometry,geo);assert.equal(crowd.positionTexture,pos);assert.equal(crowd.normalTexture,norm);assert(crowd.stats.atlasBytes<6.5*1024*1024);assert.equal(scene.children.length,1);});
test('cleanup releases only owned crowd resources and leaves original troop assets untouched',()=>{const owned=[crowd.mesh.geometry,crowd.mesh.material,crowd.mesh.customDepthMaterial,crowd.mesh.customDistanceMaterial,crowd.positionTexture,crowd.normalTexture];let disposed=0,originalDisposed=0;owned.forEach(o=>o.addEventListener('dispose',()=>disposed++));geometry.addEventListener('dispose',()=>originalDisposed++);troopMesh.material.addEventListener('dispose',()=>originalDisposed++);crowd.dispose();crowd.dispose();assert.equal(disposed,6);assert.equal(originalDisposed,0);assert.equal(scene.children.length,0);});
fs.writeFileSync('builds/animated-troop-crowd-checks.json',JSON.stringify({scope:'CPU verification on exact retained troop and commander GLBs: transferred skin weights, baked real Run/Idle deformation, shader injection, shadows, pooling, casualty counts, pause, ownership. Normal playable WebGL validation remains mandatory and is not proven by these checks.',passed,failed,checks,transfer:crowd.transfer,stats:crowd.stats,bakeMilliseconds,legMotionMetres:legMotion,armMotionMetres:armMotion,lateralLegMotionMetres:lateralLegMotion,generatedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({passed,failed,transfer:crowd.transfer,stats:crowd.stats,bakeMilliseconds,legMotion,armMotion,lateralLegMotion},null,2));if(failed)process.exitCode=1;
