/** Actual exported GLB checks; CPU geometry/scene receipts, not device performance. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import Module,{createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),deps=path.join(root,'tools/asset-viewer'),require=createRequire(path.join(deps,'package.json'));
const T=require('three'),esbuild=require('esbuild');
const build=async(name)=>{const b=await esbuild.build({entryPoints:[path.join(here,name+'.ts')],bundle:true,platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module(name);m._compile(b.outputFiles[0].text,path.join(deps,name+'-checks-inline.cjs'));return m.exports;};
const {ReforgedRig,ReforgedCrowd,compactReforgedAsset,compactRigidParts}=await build('reforged-rigs');
const {friendlyProjectilePose,combatImpactPoint,CombatVisuals}=await build('combat-visuals');
const {GLTFLoader}=await import('../asset-viewer/node_modules/three/examples/jsm/loaders/GLTFLoader.js');
const sources={};for(const name of ['RelicMarshal','GearlingSentinel','RustCrawler','ArcWarden','ForgeColossus','RelicGate']){const bytes=await fs.readFile(path.join(root,'assets/exports/reforged',name+'.glb'));sources[name]=(await new Promise((resolve,reject)=>new GLTFLoader().parse(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'',resolve,reject))).scene;}
const manifest=JSON.parse(await fs.readFile(path.join(root,'assets/exports/reforged/manifest.json'),'utf8'));
let passed=0,failed=0;function test(name,f){try{f();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+'\n'+e.stack);}}
function triangles(root){let n=0;root.traverse(o=>{if(o.isMesh)n+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});return n;}
const near=(a,b,eps=1e-6)=>assert(Math.abs(a-b)<eps,`${a} != ${b}`);
const state={phase:'run',x:0,bossX:1,bossZ:12,bossY:.6,bossPartsMask:0,bossLane:0,bossAction:'idle',bossPattern:'heavy',bossState:'armored',bossAttack:.7,weaponPower:'none',shots:[],formation:[]};
for(const [name,source] of Object.entries(sources).filter(([name])=>name!=='RelicGate'))test(name+' preserves every exported triangle and source pivot while reducing material draw batches',()=>{const clone=source.clone(true),before=new T.Box3().setFromObject(clone),count=triangles(clone);compactReforgedAsset(clone,name);assert.equal(triangles(clone),count);assert.equal(count,manifest.assets[name].triangles);const after=new T.Box3().setFromObject(clone);for(const axis of ['x','y','z']){near(after.min[axis],before.min[axis]);near(after.max[axis],before.max[axis]);}let meshes=0;clone.traverse(o=>{if(o.isMesh){meshes++;assert(o.geometry.getAttribute('color'));assert(!Array.isArray(o.material));}});assert.equal(meshes,manifest.assets[name].parts.length);for(const part of manifest.assets[name].parts){const p=clone.getObjectByName(part.id);assert(p);const world=p.getWorldPosition(new T.Vector3());part.pivotM.forEach((v,i)=>near(world.getComponent(i),v));}});
test('native paired gate frames retain open passage and readable choice width',()=>{const gate=compactRigidParts(sources.RelicGate.clone(true),['arch']);assert.equal(triangles(gate),manifest.assets.RelicGate.triangles);gate.scale.set(.405*(1.2+.1)/1.55,2.24/4.95,.32);gate.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(gate);assert(bounds.max.x-bounds.min.x<3.6);let closest=Infinity;gate.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,v=new T.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);if(v.y<1.6)closest=Math.min(closest,Math.abs(v.x));}});assert(closest>1.12,`Native frame intrudes into gate choice: ${closest}`);});
const hero=compactReforgedAsset(sources.RelicMarshal.clone(true),'RelicMarshal'),heroRig=new ReforgedRig(hero,'RelicMarshal');
test('physical commander muzzle matches export; source front reverses only with actor facing',()=>{hero.rotation.y=0;hero.updateMatrixWorld(true);assert.deepEqual(heroRig.muzzleWorld().toArray(),[-.64,1.43,.685]);hero.rotation.y=Math.PI;hero.updateMatrixWorld(true);near(heroRig.muzzleWorld().z,-.685);near(heroRig.muzzleWorld().x,.64);});
test('commander run, recoil, hit and last stand are joint poses, not showcase motion; pause is exact',()=>{heroRig.update(state,.1,'commander',true,0,0);const thigh=hero.getObjectByName('ThighL'),rest=thigh.quaternion.clone();heroRig.update(state,.1,'commander',true,.4,1);assert(!rest.equals(thigh.quaternion));const flash=hero.getObjectByName('ReforgedMuzzleFlash');assert(flash.visible);const p=heroRig.muzzleWorld().clone(),q=hero.getObjectByName('ForearmR').quaternion.clone();heroRig.update(state,0,'commander',true,.4,1);assert(q.equals(hero.getObjectByName('ForearmR').quaternion));assert(p.distanceTo(heroRig.muzzleWorld())<1e-8);heroRig.update({...state,phase:'lastStand'},.1,'commander',false);assert(hero.getObjectByName('ThighL').rotation.x>.5);heroRig.reset();assert(!flash.visible);});
const boss=compactReforgedAsset(sources.ForgeColossus.clone(true),'ForgeColossus'),bossRig=new ReforgedRig(boss,'ForgeColossus');
test('new boss aliases preserve actual cannon and jet geometry and do not add chest or face overlays',()=>{for(const [alias,id] of [['Barrel_L','Cannon_L'],['Barrel_R','Cannon_R'],['Pod_L','Jet_L'],['Pod_R','Jet_R']])assert.equal(boss.getObjectByName(id).parent.name,alias);assert(!boss.getObjectByName('BossCoreShutters'));assert(!boss.getObjectByName('BossFaceRefinement'));near(bossRig.reactorWorld().y,4.01);near(bossRig.reactorWorld().z,.74);});
test('reactor charge remains after cannon removal; jets follow actual airborne state and part mask',()=>{bossRig.syncParts(3);bossRig.update({...state,phase:'boss',bossPattern:'laser',bossAction:'windup'},.1,'boss');assert(boss.getObjectByName('ReforgedReactorCharge').visible);assert(boss.getObjectByName('ReforgedJetFlame').visible);bossRig.syncParts(15);bossRig.update({...state,phase:'boss',bossPartsMask:15,bossY:0},.1,'boss');assert(!boss.getObjectByName('ReforgedJetFlame').visible);assert(!boss.getObjectByName('RocketPod_L').visible);bossRig.reset();assert(boss.getObjectByName('Barrel_L').visible);assert(boss.getObjectByName('RocketPod_L').visible);});
test('detaching new parts captures full rigid geometry and preserves final torso wreck',()=>{const scene=new T.Scene(),fx=new CombatVisuals(scene);scene.add(boss);bossRig.reset();for(const part of ['cannonL','cannonR','boosterL','boosterR','legL','legR'])assert(fx.bossPartBreak(boss,part));assert.equal(fx.stats().bossFragments,6);assert(fx.bossDeath(boss));assert(fx.stats().bossFragments>6);assert(fx.stats().bossFragments<=24);fx.reset();bossRig.reset();assert(boss.getObjectByName('Leg_L').visible);fx.dispose();});
test('legless boss settles on measured retained new hull rather than old model offset',()=>{bossRig.syncParts(63);const y=bossRig.groundedY(1,63);boss.position.y=y;boss.updateMatrixWorld(true);let low=Infinity;boss.traverse(o=>{if(!o.isMesh||o.name.startsWith('Reforged'))return;for(let p=o;p&&p!==boss;p=p.parent)if(!p.visible)return;o.geometry.computeBoundingBox();const b=o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld);low=Math.min(low,b.min.y);});near(low,.10);assert(y<-2);boss.position.y=0;bossRig.reset();});
for(const name of ['GearlingSentinel','RustCrawler'])test(name+' crowd keeps full silhouette, authoritative positions and bounded part/material batches',()=>{const scene=new T.Scene(),crowd=new ReforgedCrowd(scene,sources[name],name,name==='GearlingSentinel'?24:200),count=scene.children.length;let tris=0;for(const m of scene.children)tris+=(m.geometry.index?.count??m.geometry.attributes.position.count)/3;assert.equal(tris,manifest.assets[name].triangles);crowd.begin();for(let i=0;i<250;i++)crowd.add(i*.1,2,.4,Math.PI);crowd.end();assert.equal(crowd.stats().units,crowd.capacity);assert.equal(count,manifest.assets[name].parts.length);assert(crowd.stats().scaledBounds[0]<=(name==='GearlingSentinel'?.71:.87));const matrix=new T.Matrix4();scene.children[0].getMatrixAt(0,matrix);assert(matrix.elements.every(Number.isFinite));for(let i=0;i<100;i++){crowd.begin();crowd.add(1.2,3.1,.4,Math.PI);crowd.end();crowd.reset();assert.equal(crowd.stats().units,0);assert.equal(scene.children.length,count);}crowd.dispose();assert.equal(scene.children.length,0);});
test('crawler cannon inherits its moving turret and pause preserves both part matrices',()=>{const scene=new T.Scene(),crowd=new ReforgedCrowd(scene,sources.RustCrawler,'RustCrawler',3),turret=scene.getObjectByName('RustCrawler_Turret_Batch'),cannon=scene.getObjectByName('RustCrawler_Cannon_Batch'),a=new T.Matrix4(),b=new T.Matrix4();crowd.begin();crowd.add(0,5,0,0);crowd.end();cannon.getMatrixAt(0,a);crowd.begin();crowd.add(0,5,1,0);crowd.end();cannon.getMatrixAt(0,b);assert(Math.abs(a.elements[0]-b.elements[0])>.0001);const tq=new T.Quaternion(),cq=new T.Quaternion();turret.getMatrixAt(0,a);a.decompose(new T.Vector3(),tq,new T.Vector3());b.decompose(new T.Vector3(),cq,new T.Vector3());assert(tq.angleTo(cq)<1e-5);crowd.begin();crowd.add(0,5,1,0);crowd.end();cannon.getMatrixAt(0,a);assert.deepEqual(a.elements,b.elements);crowd.dispose();});
test('new projectile profiles meet measured moving core heights without changing simulated X/Z',()=>{for(const kind of ['pulse','cannon','missile','rail'])for(const overdrive of [false,true]){const shot={x:.8,z:11.26,dx:0,dz:32,owner:'troop',kind},options={depthScale:1,bossPhase:true,bossZ:12,bossX:1,bossY:.8,bossImpactHeight:4.01,bossSurfaceOffset:.74,anchors:{troopHeight:.776,commanderHeight:1.8,commanderOriginZ:.65,eliteHeight:1.72,enemyHeight:.55},formation:[{index:0,x:.8,z:-.75}],weapon:1,overdrive};const pose=friendlyProjectilePose(shot,options);near(pose.position.x,shot.x);near(pose.position.z,-shot.z);near(pose.position.y,4.81);near(pose.direction.x,0);const impact=combatImpactPoint({x:.8,z:12,variant:3,entityId:0},options);near(impact.y,pose.position.y);near(impact.z,pose.position.z);}});
console.log(`${passed}/${passed+failed} new Reforged rig checks passed. Actual GLBs checked; WebGL/GPU performance is separate.`);if(failed)process.exit(1);
