// CPU verification of actual Three adapters; rendered appearance is reviewed separately.
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
const output=await esbuild.build({entryPoints:[path.join(here,'relic-effects.ts')],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});
const m=new Module('relic-effects');m.paths=Module._nodeModulePaths(deps);m._compile(output.outputFiles[0].text,path.join(deps,'relic-effects-inline.cjs'));const {RelicEffects}=m.exports;
const scene=new T.Scene(),hero=new T.Group();scene.add(hero);const fx=new RelicEffects(scene,hero);
const base={phase:'run',x:0,relic:0,ability:0,empPulseTime:0,empStunTime:0,escortShield:0,powerTime:0,bossX:0,bossY:0,bossZ:12,targets:[],effects:[]};
const view={armyRadius:2,armyCenterX:0,armyCenterZ:1.5,visible:true};let id=1,passed=0,failed=0;
const event=(kind,value=0,more={})=>({id:id++,kind,value,x:0,z:0,entityId:0,variant:0,size:1,...more});
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' — '+e.message);}}
test('whole-legion cover is nine machined metal plates and the old dome and rim remain disabled',()=>{fx.update({...base,relic:0,ability:4},view,0);assert(!fx.dome.visible&&!fx.rim.visible);assert(fx.shield.root.visible);assert.equal(fx.stats.shieldPanels,9);assert(fx.shield.panels.material.metalness>.6);assert(fx.shield.stats.frontZ<view.armyCenterZ-3);assert(fx.shield.stats.width>=view.armyRadius*2);fx.shield.panels.geometry.computeBoundingBox();assert(fx.shield.panels.geometry.boundingBox.max.y>1.7);});
test('no proximity-inferred ripples; revive block does not fake shield absorption',()=>{fx.trigger(event('block',20));fx.update({...base,relic:0,ability:4,enemyShots:[{x:0,z:0}]},view,.016);assert.equal(fx.stats.sparks,0);});
test('actual shieldHit produces one plate-local spark and duplicate IDs do not replay',()=>{const hit=event('shieldHit',9,{x:1,z:-1});fx.trigger(hit);fx.trigger(hit);fx.update({...base,relic:0,ability:4},view,0);assert.equal(fx.stats.sparks,1);const ripple=fx.root.children.find(c=>c.geometry?.type==='RingGeometry'&&c.visible);assert(ripple);assert(ripple.position.y>0);assert(ripple.material.opacity>.8);});
test('swept shield contact preserves actual projectile height and folded-wing contact depth',()=>{fx.reset();const hit=event('shieldHit',9,{x:2.1,y:2.32,z:1.81,variant:-6});fx.trigger(hit);fx.update({...base,relic:0,ability:4},view,0);const ripple=fx.root.children.find(c=>c.geometry?.type==='RingGeometry'&&c.visible);assert.equal(ripple.position.x,2.1);assert.equal(ripple.position.y,2.32);assert.equal(ripple.position.z,-1.825);fx.shield.panels.geometry.computeBoundingBox();assert(fx.shield.panels.geometry.boundingBox.max.y>2.90);});
test('all twelve impact slots share one uploaded geometry instead of growing GPU warm-up counts',()=>{const rings=fx.root.children.filter(c=>c.geometry?.type==='RingGeometry');assert.equal(rings.length,12);assert.equal(new Set(rings.map(c=>c.geometry)).size,1);});
test('first activation frame is visible at dt0 and reduced motion preserves confirmation',()=>{fx.reset();fx.trigger(event('relic',1));fx.trigger(event('empPulse',0,{size:26}));fx.update({...base,relic:1,ability:2,empPulseTime:.65},view,0);assert(fx.wave.visible);assert.equal(fx.stats.empLife,.65);assert.equal(fx.sceneImpact.exposureLift,.16);assert.equal(fx.sceneImpact.zoom,.016);fx.setReducedMotion(true);fx.update(base,view,0);assert.equal(fx.sceneImpact.zoom,0);assert(fx.sceneImpact.exposureLift>0&&fx.sceneImpact.exposureLift<.05);fx.setReducedMotion(false);});
test('observed real weapon upgrade has one bounded scene response, respects reduced motion and shares existing pickup pulse',()=>{fx.reset();assert(!fx.weaponUpgrade(1,1));assert(!fx.weaponUpgrade(0,2));assert(fx.weaponUpgrade(1,2));assert.equal(fx.sceneImpact.exposureLift,.16);assert(!fx.weaponUpgrade(1,2));assert(!fx.weaponUpgrade(2,3));fx.update(base,{...view,paused:true},1);assert.equal(fx.stats.pulseLife,.36);fx.setReducedMotion(true);fx.update(base,view,0);assert.equal(fx.sceneImpact.zoom,0);assert(fx.sceneImpact.exposureLift<.05);fx.reset();fx.trigger(event('pickup',2));const life=fx.stats.pulseLife;assert(!fx.weaponUpgrade(1,2));assert.equal(fx.stats.pulseLife,life);fx.setReducedMotion(false);});
test('pause freezes pulse, bolts, ripples, geometry and visual clock exactly',()=>{fx.trigger(event('empStun',0,{x:2,z:10,entityId:11}));fx.update(base,view,.016);const before=JSON.stringify({stats:fx.stats,impact:fx.sceneImpact,wave:fx.wave.matrix.toArray(),vertices:[...fx.lightning.geometry.attributes.position.array]});for(let i=0;i<120;i++)fx.update(base,{...view,paused:true},1/60);assert.equal(JSON.stringify({stats:fx.stats,impact:fx.sceneImpact,wave:fx.wave.matrix.toArray(),vertices:[...fx.lightning.geometry.attributes.position.array]}),before);});
test('EMP bolts require actual clear/stun/EMP-kill events and never arbitrary nearby enemies',()=>{fx.reset();fx.update({...base,targets:[{id:9,x:1,z:3,variant:1,stunTime:0}]},view,0);assert.equal(fx.stats.bolts,0);fx.trigger(event('empClear',0,{entityId:19,x:2,z:9}));fx.update(base,view,0);assert.equal(fx.stats.bolts,1);assert.equal(fx.lightning.geometry.drawRange.count,24);});
test('survivor stun indicators use exact per-target and boss timers',()=>{fx.update({...base,phase:'boss',empStunTime:2,targets:[{id:1,x:0,z:6,variant:1,stunTime:2},{id:2,x:2,z:7,variant:1,stunTime:0}]},view,0);assert.equal(fx.stats.stunned,2);fx.update(base,view,0);assert.equal(fx.stats.stunned,0);});
test('EMP wave expires at .65 seconds; EMP does not become a lingering shield',()=>{fx.reset();fx.trigger(event('empPulse'));for(let i=0;i<40;i++)fx.update({...base,relic:1,ability:2},view,1/60);assert(!fx.wave.visible);assert(!fx.dome.visible);assert.equal(fx.sceneImpact.exposureLift,0);});
test('Barrage deploys measured shoulder launchers with no body or floor Overdrive circles',()=>{fx.reset();fx.update({...base,x:2,relic:2,ability:5,shots:[]},view,0);assert(fx.battery.root.visible&&!fx.dome.visible);for(const [i,expected]of [[0,1.32],[1,2.68]]){const socket=fx.battery.stats.sockets[i];assert(Math.abs(socket[0]-expected)<1e-9);assert.equal(socket[1],2.11);assert.equal(socket[2],-.92);}assert(!fx.root.getObjectByName('OverdriveFloor_0'));assert(!fx.root.getObjectByName('Overdrive_UpperBodyArc_0'));fx.update({...base,relic:2,ability:0,shots:[]},view,0);assert(!fx.battery.root.visible);});
test('Barrage panels deploy and recoil only from actual new rockets, held combat retains them and retries clear launch history',()=>{fx.reset();const state={...base,x:0,relic:2,ability:5,shots:[]};fx.update(state,view,.1);assert(fx.battery.stats.deployment>.75);assert.equal(fx.battery.stats.launchFlashes,0);fx.update({...state,shots:[{id:400,x:-.68,y:2.11,z:1.3,kind:'salvo',owner:'commander'}]},view,.016);assert.equal(fx.battery.stats.launchFlashes,1);assert.equal(fx.battery.stats.trackedShots,1);const before=JSON.stringify(fx.battery.stats);fx.update(state,{...view,paused:true},.1);assert.equal(JSON.stringify(fx.battery.stats),before);fx.update({...state,clash:{active:true}},view,0);assert.equal(JSON.stringify(fx.battery.stats),before);fx.reset();assert.equal(fx.battery.stats.trackedShots,0);assert(!fx.battery.root.visible);});
test('escort shows finite defense only while budget and timer remain, not a full shield',()=>{fx.update({...base,escortShield:30,powerTime:12},view,0);assert(fx.escort.visible&&!fx.dome.visible);fx.update({...base,escortShield:0,powerTime:8},view,0);assert(!fx.escort.visible);fx.update({...base,escortShield:15,powerTime:0},view,0);assert(!fx.escort.visible);});
test('repeated activations stay within fixed pools and reset allocates no retained geometry',()=>{const count=()=>{let n=0;fx.root.traverse(()=>n++);return n;},before=count();for(let i=0;i<1000;i++){fx.trigger(event('shieldHit',5));fx.trigger(event('empClear',0,{x:1,z:7}));fx.trigger(event('relic',i%3));fx.update({...base,ability:4},view,1/60);if(i%17===0)fx.reset();assert(fx.stats.sparks<=12&&fx.stats.bolts<=32);}assert.equal(count(),before);fx.reset();assert.equal(fx.stats.sparks+fx.stats.bolts+fx.stats.stunned,0);assert.equal(fx.sceneImpact.exposureLift,0);});
test('dispose releases all owned geometry/materials exactly once and removes only owned root',()=>{const geometries=new Set(),materials=new Set();fx.root.traverse(c=>{if(c.geometry)geometries.add(c.geometry);if(c.material)materials.add(c.material);});let disposed=0;for(const g of geometries)g.addEventListener('dispose',()=>disposed++);for(const mat of materials)mat.addEventListener('dispose',()=>disposed++);fx.dispose();assert.equal(disposed,geometries.size+materials.size);fx.dispose();assert.equal(disposed,geometries.size+materials.size);assert(!scene.children.includes(fx.root));assert(scene.children.includes(hero));});
const receipt={scope:'CPU actual Three geometry/event/pause/resource checks; browser appearance and Android GPU performance separately required',passed,failed,capacity:{ripples:12,bolts:32,stunMarkers:48},firstFrame:'trigger then update(dt=0) retains full activation',generatedAt:new Date().toISOString()};fs.mkdirSync(path.resolve(here,'../../builds'),{recursive:true});fs.writeFileSync(path.resolve(here,'../../builds/relic-effects-checks.json'),JSON.stringify(receipt,null,2));console.log(`${passed}/${passed+failed} relic effect checks passed`);if(failed)process.exitCode=1;
