import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import Module from 'node:module';import {points} from './measure_portrait_camera.mjs';
const deps=path.resolve('tools/asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const b=await esbuild.build({entryPoints:['tools/playable-preview/'+file],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[deps+'/node_modules'],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'framing-inline.cjs'));return m.exports;}
const {FormationFraming}=await code('portrait-framing.ts'),{Battlefield}=await code('world.ts'),bounds=new T.Box3().setFromPoints(points),results=[];const point=new T.Vector3(),matrix=new T.Matrix4(),position=new T.Vector3(),rotation=new T.Quaternion(),euler=new T.Euler(),scale=new T.Vector3(.432,.72,.72);
for(const[w,h]of[[420,933],[412,915],[375,667],[352,782],[560,850]])for(const side of[-1,1]){
 const camera=new T.PerspectiveCamera(30,w/h,.1,180),actor=Object.create(Battlefield.prototype);Object.assign(actor,{camera,canvas:{clientWidth:w,clientHeight:h},renderer:{setSize(){}}});actor.resize();const look=actor.cameraLookZ,distance=(5.05/Math.min(.45,camera.aspect))/Math.tan(T.MathUtils.degToRad(15)),fit=new FormationFraming();fit.setBounds(bounds);let maxPan=0,minMargin=Infinity;
 for(let frame=0;frame<90;frame++){
  const x=side*Math.min(3,frame*5/60),formation=Array.from({length:24},(_,i)=>({index:i,x:T.MathUtils.clamp(x,-2.805,2.805)+(i%4-1.5)*.73,z:-(.75+Math.floor(i/4)*.48)}));
  camera.position.set(0,distance*.58,look+distance*.815);camera.lookAt(0,.1,look);camera.fov=29.52;camera.updateProjectionMatrix();const pan=fit.update(camera,formation,1/60,w);maxPan=Math.max(maxPan,Math.abs(pan));camera.position.x=pan;camera.lookAt(pan,.1,look);camera.position.x-=side*.12;camera.updateMatrixWorld(true);
  const edge=formation[side>0?23:20];position.set(edge.x,.075,-edge.z);rotation.setFromEuler(euler.set(0,Math.PI+side*.035,0));matrix.compose(position,rotation,scale);for(const p of points){point.copy(p).applyMatrix4(matrix).project(camera);const px=(1+point.x)*w/2;minMargin=Math.min(minMargin,px,w-px);}assert(Math.abs(pan)<=fit.maxPan);assert(camera.fov===29.52);
 }
 assert(minMargin>=2,`Clipped ${w}x${h} side${side}: ${minMargin}px`);const frozen=fit.pan;fit.update(camera,[],0,w);assert.equal(fit.pan,frozen);fit.reset();assert.equal(fit.pan,0);results.push({w,h,side,maxPanMetres:maxPan,minActualVertexMarginPixels:minMargin});
}
// Recruitment expands from a short formation into six rows at the edge.
const camera=new T.PerspectiveCamera(29.52,.45,.1,180),actor=Object.create(Battlefield.prototype);Object.assign(actor,{camera,canvas:{clientWidth:420,clientHeight:933},renderer:{setSize(){}}});actor.resize();const look=actor.cameraLookZ,d=(5.05/.45)/Math.tan(T.MathUtils.degToRad(15));camera.position.set(0,d*.58,look+d*.815);camera.lookAt(0,.1,look);camera.fov=29.52;camera.updateProjectionMatrix();const sudden=new FormationFraming();sudden.setBounds(bounds);const f=Array.from({length:24},(_,i)=>({index:i,x:2.805+(i%4-1.5)*.73,z:-(.75+Math.floor(i/4)*.48)}));const pan=sudden.update(camera,f,1/60,420);camera.position.x=pan;camera.lookAt(pan,.1,look);camera.updateMatrixWorld(true);position.set(3.9,.075,3.15);rotation.setFromEuler(euler.set(0,Math.PI+.035,0));matrix.compose(position,rotation,scale);let instantMargin=Infinity;for(const p of points){point.copy(p).applyMatrix4(matrix).project(camera);instantMargin=Math.min(instantMargin,420-(1+point.x)*210);}assert(instantMargin>=10);
fs.writeFileSync('builds/portrait-framing-checks.json',JSON.stringify({scope:'Actual retained troop vertex projections, exact runtime resize, both sides, 5m/s commands, maximum upgrade zoom and .12m shake; CPU geometry proof only.',results,instantRecruitMarginPixels:instantMargin,passed:true,generatedAt:new Date().toISOString()},null,2));console.log('PASS 10 portrait/desktop side cases, actual 4582 vertices, fast steering, instant recruitment, zoom/shake margins, dt0 freeze and reset.');console.log(JSON.stringify(results,null,2));
