import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import Module,{createRequire} from 'node:module';
const deps=path.resolve('tools/asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function source(file){const b=await esbuild.build({entryPoints:['tools/playable-preview/'+file],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[deps+'/node_modules'],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'runtime-presentations.cjs'));return m.exports;}
const {CoreAbsorption}=await source('core-absorption.ts'),{EnemySupportLinks}=await source('enemy-support-links.ts'),scene=new T.Scene(),core=new CoreAbsorption(scene),links=new EnemySupportLinks(scene),checks=[];let failed=0;
function check(name,fn){try{fn();checks.push({name,pass:true});console.log('PASS '+name);}catch(e){failed++;checks.push({name,pass:false,error:e.message});console.error('FAIL '+name+' '+e.stack);}}
check('chosen core starts at the measured boss core, reaches the commander, and finishes before next act',()=>{const a=new T.Vector3(1,5,-13),b=new T.Vector3(-2,1.7,0);core.begin('laser',a,b);assert.equal(core.timeRemaining,1.2);assert(core.root.children[0].position.distanceTo(a)<1e-9);for(let i=0;i<9;i++)core.update(.1);assert(core.root.children[0].position.distanceTo(a)>5);assert(core.root.visible);for(let i=0;i<4;i++)core.update(.1);assert.equal(core.timeRemaining,0);assert(!core.root.visible);assert(core.root.children[0].position.distanceTo(b)<1e-9);});
check('pause retains exact core travel and reset cancels absorption without creating resources',()=>{core.begin('vitality',new T.Vector3(1,4,-12),new T.Vector3(0,2,0));core.update(.1);const matrices=core.root.children.map(o=>o.isInstancedMesh?[...o.instanceMatrix.array]:[...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]),time=core.timeRemaining;for(let i=0;i<30;i++)core.update(0);assert.equal(core.timeRemaining,time);assert.deepEqual(core.root.children.map(o=>o.isInstancedMesh?[...o.instanceMatrix.array]:[...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]),matrices);const geometry=core.root.children.map(o=>o.geometry);core.reset();assert.equal(core.timeRemaining,0);assert(!core.root.visible);core.begin('endurance',new T.Vector3(),new T.Vector3(0,1.7,0));assert.deepEqual(core.root.children.map(o=>o.geometry),geometry);});
check('engineer link requires reported recipient endpoints and pulses toward actual healed enemy',()=>{const e={kind:'enemySupport',x:-2,y:1.7,z:12,endX:2,endY:1.5,endZ:10};links.trigger({...e,endX:undefined});links.update(0);assert.equal(links.mesh.count,0);links.trigger(e);links.update(0);assert.equal(links.mesh.count,8);const matrix=new T.Matrix4();links.mesh.getMatrixAt(0,matrix);assert(new T.Vector3().setFromMatrixPosition(matrix).distanceTo(new T.Vector3(-2,1.7,-12))<1e-6);links.update(.1);links.mesh.getMatrixAt(0,matrix);assert(new T.Vector3().setFromMatrixPosition(matrix).x>-2);const before=[...links.mesh.instanceMatrix.array];links.update(0);assert.deepEqual([...links.mesh.instanceMatrix.array],before);for(let i=0;i<6;i++)links.update(.1);assert.equal(links.mesh.count,0);});
check('repeated repair pulses are bounded and reset clears links before a new act',()=>{for(let i=0;i<100;i++)links.trigger({kind:'enemySupport',x:0,y:1,z:12,endX:1,endY:1,endZ:10});links.update(.01);assert.equal(links.mesh.count,64);links.reset();assert.equal(links.mesh.count,0);});
fs.writeFileSync('builds/runtime-presentations-checks.json',JSON.stringify({scope:'CPU timelines for actual world adapters; normal UI and GPU captures are separate evidence',checks,passed:checks.length-failed,failed,generatedAt:new Date().toISOString()},null,2));if(failed)process.exitCode=1;
