// Isolated opt-in renderer checks. Core hit regions are not integrated by this file.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
const build=await esbuild.build({entryPoints:[path.join(here,'boss-rig-adapter.ts')],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module('boss-adapter');m.paths=Module._nodeModulePaths(deps);m._compile(build.outputFiles[0].text,path.join(deps,'boss-rig-inline.cjs'));const {BossRigAdapter}=m.exports;
const b=fs.readFileSync(path.join(root,'delivery/playable/forge-tyrant.glb')),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));const nodes=j.nodes.map(n=>{const o=new T.Object3D();o.name=n.name??'';if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);return o;});for(let i=0;i<nodes.length;i++)for(const child of j.nodes[i].children??[])nodes[i].add(nodes[child]);const model=new T.Group();model.rotation.y=Math.PI;for(const n of j.scenes[j.scene??0].nodes)model.add(nodes[n]);const boss=new T.Group(),scene=new T.Scene();boss.add(model);scene.add(boss);const adapter=new BossRigAdapter(boss,scene);let passed=0,failed=0;
const pose={rootX:2,rootY:1.5,worldZ:-12,pitch:.1,yaw:.2,roll:-.15,arm:[{pitch:-.20,roll:.18},{pitch:.22,roll:-.18}],leg:[-.14,.14],knee:[0,.10],poseClock:3};
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' — '+e.message);}}
test('opt-in data absence or malformed pose never alters legacy transforms',()=>{const before=boss.matrix.toArray(),arm=boss.getObjectByName('Arm_L').quaternion.toArray();assert.equal(adapter.apply(),false);assert.equal(adapter.apply({...pose,pitch:NaN}),false);assert.deepEqual(boss.matrix.toArray(),before);assert.deepEqual(boss.getObjectByName('Arm_L').quaternion.toArray(),arm);});
test('authoritative pose mirrors current retained GLB bind hierarchy with one facing rotation',()=>{assert(adapter.apply(pose));assert.deepEqual(boss.position.toArray(),[2,1.5,-12]);assert.deepEqual(boss.scale.toArray(),[1.4,1.4,1.4]);assert(Math.abs(model.rotation.y-Math.PI)<1e-8);for(const [name,pitch,roll] of [['Arm_L',-.2,.18],['Arm_R',.22,-.18],['Leg_L',-.14,0],['Leg_R',.14,0],['Knee_R',.1,0]]){const e=new T.Euler().setFromQuaternion(boss.getObjectByName(name).quaternion,'XYZ');assert(Math.abs(e.x-pitch)<1e-8);assert(Math.abs(e.z-roll)<1e-8);}const before=model.getObjectByName('Barrel_L').getWorldPosition(new T.Vector3());adapter.apply({...pose,rootX:3});const after=model.getObjectByName('Barrel_L').getWorldPosition(new T.Vector3());assert(Math.abs(after.x-before.x-1)<1e-8);assert(Math.abs(after.y-before.y)<1e-8);});
test('applying pose preserves missing-part visibility and never resets health',()=>{const part=boss.getObjectByName('Barrel_L');part.visible=false;adapter.apply(pose);assert.equal(part.visible,false);part.visible=true;});
const q=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),Math.PI).toArray(),region={id:'cannonL',x:1.7,y:4.5,z:10,radiusX:.6,radiusY:.6,radiusZ:.8,quaternion:q,hp:30,maxHp:100,vulnerable:true};
test('only current live vulnerable regions get compact cues, with exact world coordinate conversion',()=>{adapter.updateRegions([region,{...region,id:'cannonR',vulnerable:false},{...region,id:'legL',hp:0},{...region,id:'jetL',quaternion:[0,0,0,0]}]);assert.equal(adapter.cues.count,1);const matrix=new T.Matrix4();adapter.cues.getMatrixAt(0,matrix);const position=new T.Vector3().setFromMatrixPosition(matrix);assert(Math.abs(position.x-1.7)<1e-6);assert(Math.abs(position.y-4.5)<1e-6);assert(Math.abs(position.z-(-10+.835))<1e-6);assert.equal(region.hp,30);});
test('compound leg cue follows an actual component and repaired core casing has a distinct cue',()=>{const leg={...region,id:'legL',y:2};const plate={regionId:'legL',active:true,x:.8,y:1.6,z:9.7,radiusX:.3,radiusY:.45,radiusZ:.25,quaternion:q};adapter.updateRegions([leg],true,[plate]);const matrix=new T.Matrix4();adapter.cues.getMatrixAt(0,matrix);const p=new T.Vector3().setFromMatrixPosition(matrix);assert(Math.abs(p.y-1.6)<1e-6);assert(Math.abs(p.z-(-9.7+.285))<1e-6);adapter.updateRegions([{...region,id:'core'}],true,[],50);assert.equal(adapter.reactorCue.material.color.getHex(),0x86eeff);});
test('impact adapter requires actual region and Y, never invents chest contact',()=>{assert.equal(adapter.impact({x:0,z:12}),undefined);const point=adapter.impact({hitRegion:'cannonR',x:-1.5,y:3.8,z:11.2});assert.deepEqual(point.toArray(),[-1.5,3.8,-11.2]);});
test('reset/repeated poses do not retain cues or accumulate native rotation',()=>{const expected=boss.getObjectByName('Arm_L').quaternion.clone(),geo=adapter.cues.geometry;for(let i=0;i<500;i++)adapter.apply(pose);assert(expected.angleTo(boss.getObjectByName('Arm_L').quaternion)<1e-7);assert.equal(adapter.cues.geometry,geo);adapter.reset();assert.equal(adapter.cues.count,0);assert(boss.getObjectByName('Arm_L').quaternion.angleTo(new T.Quaternion())<1e-7);});
test('core cue mirrors measured oval and only actual vulnerability exposes it',()=>{const core={...region,id:'core',x:0,y:4.2754723549,z:11.0842434764,radiusX:.3489084572,radiusY:.50591712,radiusZ:.099688113};adapter.updateRegions([core]);assert.equal(adapter.cues.count,0);assert(adapter.reactorCue.visible);assert.deepEqual(adapter.reactorCue.scale.toArray(),[core.radiusX,core.radiusY,1]);assert.deepEqual(adapter.reactorCue.position.toArray(),[0,core.y,-core.z]);adapter.updateRegions([{...core,vulnerable:false}]);assert(!adapter.reactorCue.visible);});
test('dispose removes only adapter-owned fixed resources',()=>{let disposed=0;adapter.cues.geometry.addEventListener('dispose',()=>disposed++);adapter.cues.material.addEventListener('dispose',()=>disposed++);adapter.reactorCue.geometry.addEventListener('dispose',()=>disposed++);adapter.reactorCue.material.addEventListener('dispose',()=>disposed++);adapter.reactorFlash.geometry.addEventListener('dispose',()=>disposed++);adapter.reactorFlash.material.addEventListener('dispose',()=>disposed++);adapter.dispose();adapter.dispose();assert.equal(disposed,6);assert(!scene.children.includes(adapter.reactorFlash));assert(scene.children.includes(boss));assert(!scene.children.includes(adapter.cues));});
fs.writeFileSync(path.join(root,'builds/boss-rig-adapter-checks.json'),JSON.stringify({scope:'Production boss renderer adapter; actual retained GLB hierarchy, CPU tests only. Gameplay aim and damage are verified separately against the simulation.',passed,failed,generatedAt:new Date().toISOString()},null,2));console.log(`${passed}/${passed+failed} optional boss adapter checks passed`);if(failed)process.exitCode=1;
