// Actual Three geometry and presentation APIs. Gameplay acceptance uses separate real-WASM runs.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const b=await esbuild.build({entryPoints:[path.join(here,file)],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(b.outputFiles[0].text,path.join(deps,'power-check-inline.cjs'));return m.exports;}
const {Battlefield}=await code('world.ts'),{ENVIRONMENT_PALETTES}=await code('environment.ts');
const {CommanderPowerVisuals,CombatMissiles,CombatVisuals}=await code('combat-visuals.ts'),{ArsenalVisuals,createPickup,disposePickup}=await code('arsenal-visuals.ts'),{RelicEffects}=await code('relic-effects.ts');
const scene=new T.Scene(),hero=new T.Group(),boss=new T.Group();scene.add(hero,boss);const fx=new CommanderPowerVisuals(scene),arsenal=new ArsenalVisuals(hero,boss);let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+e.stack);}}
const beam={id:1,x:2,y:1.42,z:1.32,endX:2,endY:4.3,endZ:20,width:1,time:1};
function endpoints(mesh){const m=new T.Matrix4();mesh.getMatrixAt(0,m);return [new T.Vector3(0,0,-.5).applyMatrix4(m),new T.Vector3(0,0,.5).applyMatrix4(m)];}
const state={phase:'run',x:2,bossX:0,bossZ:12,bossY:0,bossAttack:0,bossAction:'strafe',bossPartsMask:0,bossPhase:1,bossPattern:'heavy',bossState:'armored',bossHp:100,empStunTime:0,timePower:'none',timePowerTime:0,weaponPower:'none',powerTime:0,shots:[],enemyShots:[],combatPower:'tempest',combatPowerTime:1,friendlyBeams:[beam]};
test('Tempest exact straight center and full-width cylinder retain authoritative endpoints',()=>{
 fx.update([beam],0);assert.equal(fx.stats.beams,1);const shell=fx.root.getObjectByName('Tempest_ActualCorridor'),core=fx.root.getObjectByName('Tempest_StraightCore'),[a,b]=endpoints(shell);assert(a.distanceTo(new T.Vector3(2,1.42,-1.32))<1e-5);assert(b.distanceTo(new T.Vector3(2,4.3,-20))<1e-5);const [c,d]=endpoints(core);assert(c.distanceTo(a)<1e-5&&d.distanceTo(b)<1e-5);const m=new T.Matrix4();shell.getMatrixAt(0,m);assert(Math.abs(new T.Vector3().setFromMatrixScale(m).x-1)<1e-6);assert(fx.stats.arcs>=36);assert(shell.material.color.b>shell.material.color.r);
});
test('moving source follows actual updated corridor without targeting sideways enemies',()=>{const moved={...beam,x:-2.4,endX:-2.4,endY:1.42};fx.update([moved],.05);const [a,b]=endpoints(fx.root.getObjectByName('Tempest_ActualCorridor'));assert(Math.abs(a.x+2.4)<1e-6&&Math.abs(b.x+2.4)<1e-6);fx.update([],0);assert.equal(fx.stats.beams,0);});
test('Lance cannon physical muzzle equals actual pitched beam start after commander bob',()=>{hero.position.set(2,.055,0);arsenal.update(state,0);hero.updateWorldMatrix(true,true);const socket=hero.getObjectByName('CommanderSocket_tempest').getWorldPosition(new T.Vector3());assert(socket.distanceTo(new T.Vector3(2,1.42,-1.32))<1e-8);const group=hero.getObjectByName('TempestLance_MuzzlePivot'),dir=new T.Vector3(0,0,1).transformDirection(group.matrixWorld),expected=new T.Vector3(0,beam.endY-beam.y,-beam.endZ+beam.z).normalize();assert(dir.distanceTo(expected)<1e-8);});
test('Arc Storm links require exact real recipient endpoints and duplicate events do not replay',()=>{fx.reset();assert(!fx.trigger({id:2,kind:'hit',x:0,y:1,z:0,endX:2,endY:2,endZ:8}));assert(!fx.trigger({id:3,kind:'chainHit',x:0,z:0,endX:2,endY:2,endZ:8}));const hit={id:4,kind:'chainHit',x:0,y:1.8,z:.4,endX:2,endY:1.6,endZ:8};assert(fx.trigger(hit));assert(!fx.trigger(hit));fx.update([],0);assert.equal(fx.stats.links,1);assert(fx.stats.arcs>=10);const l=fx.links.find(l=>l.life>0);assert.deepEqual(l.start.toArray(),[0,1.8,-.4]);assert.deepEqual(l.end.toArray(),[2,1.6,-8]);});
test('pause freezes finite links and electrical geometry byte-for-byte',()=>{fx.update([beam],.04);const before={stats:fx.stats,mat:[...fx.arcs.instanceMatrix.array],links:fx.links.map(l=>l.life)};for(let i=0;i<100;i++)fx.update([beam],0);assert.deepEqual(fx.stats,before.stats);assert.deepEqual([...fx.arcs.instanceMatrix.array],before.mat);assert.deepEqual(fx.links.map(l=>l.life),before.links);for(let i=0;i<20;i++)fx.update([],1/60);assert.equal(fx.stats.links,0);assert.equal(fx.stats.arcs,0);});
test('all beam/link resources remain fixed and bounded across repeated bursts and reset',()=>{const n=fx.root.children.length,geos=new Set(fx.root.children.map(m=>m.geometry));for(let i=0;i<1000;i++){fx.trigger({id:100+i,kind:'chainHit',x:0,y:1,z:0,endX:i%3,endY:2,endZ:15});fx.update(Array.from({length:10},(_,id)=>({...beam,id})),.01);assert(fx.stats.beams<=4&&fx.stats.links<=24&&fx.stats.arcs<=512);if(i%13===0)fx.reset();}assert.equal(fx.root.children.length,n);assert.deepEqual(new Set(fx.root.children.map(m=>m.geometry)),geos);fx.reset();assert.equal(fx.stats.beams+fx.stats.links+fx.stats.arcs,0);});
test('Siege Salvo uses actual 3D heavy rocket positions and launcher tips at committed origins',()=>{const missiles=new CombatMissiles(scene),shots=Array.from({length:6},(_,id)=>({id,x:id%2?.68:-.68,y:2.11,z:.92,dx:0,dy:4,dz:25,heavy:true,kind:'salvo',owner:'commander'}));missiles.update(shots,[],{depthScale:1,bossPhase:true,bossZ:12,bossY:0,overdrive:false,weapon:1,dt:0});assert.equal(missiles.bodies.count,6);assert.equal(missiles.bullets.count,0);const m=new T.Matrix4();missiles.bodies.getMatrixAt(0,m);assert(new T.Vector3().setFromMatrixPosition(m).distanceTo(new T.Vector3(-.68,2.11,-.92))<1e-6);assert(new T.Vector3().setFromMatrixScale(m).x>1.8);hero.position.y=0;arsenal.update({...state,combatPower:'salvo',combatPowerTime:1.8,friendlyBeams:[],shots},0);hero.updateWorldMatrix(true,true);for(const [i,rack] of arsenal.guided.children.entries()){const tip=rack.localToWorld(new T.Vector3(0,.03,.86));assert(tip.distanceTo(new T.Vector3(2+(i===0?-.68:.68),2.11,-.92))<1e-8);const direction=new T.Vector3(0,0,1).transformDirection(rack.matrixWorld);assert(direction.distanceTo(new T.Vector3(0,4,-25).normalize())<1e-8);}missiles.dispose();});
test('three finite pickup symbols have distinct original geometry and finite bounds',()=>{const sizes=[];for(const kind of ['tempest','arcstorm','salvo']){const p=createPickup(kind);p.updateWorldMatrix(true,true);const b=new T.Box3().setFromObject(p),v=b.getSize(new T.Vector3());assert(v.toArray().every(Number.isFinite));assert(v.x>.6&&v.y>.7);sizes.push(v.toArray().map(x=>x.toFixed(2)).join(','));disposePickup(p);}assert.equal(new Set(sizes).size,3);});
test('real power activation gives one reduced-motion-aware scene response without fake combat',()=>{const relic=new RelicEffects(scene,hero,true);relic.trigger({id:1,kind:'combatPower',value:8,variant:8,x:0,z:0,entityId:0,size:1});assert.equal(relic.sceneImpact.zoom,0);assert(relic.sceneImpact.exposureLift>0&&relic.sceneImpact.exposureLift<.05);relic.dispose();});
test('new chapter sky and fog share authored palette while accepted base scenes retain their original color',()=>{const scene=new T.Scene();scene.fog=new T.Fog(0,1,10);const colors=[],actor=Object.create(Battlefield.prototype);actor.scene=scene;actor.renderer={setClearColor(c){colors.push(c);}};for(const stage of [3,4,0,1,2]){actor.applyStagePalette(stage);const expected=stage>=3?ENVIRONMENT_PALETTES[stage].sky:0xadc5c7;assert.equal(colors.at(-1),expected);assert.equal(scene.fog.color.getHex(),expected);}const n=colors.length;actor.applyStagePalette(2);assert.equal(colors.length,n);});
test('dispose owns five fixed geometries/materials once and preserves accepted actors',()=>{let count=0;for(const mesh of fx.root.children){mesh.geometry.addEventListener('dispose',()=>count++);mesh.material.addEventListener('dispose',()=>count++);}fx.dispose();assert.equal(count,10);fx.dispose();assert.equal(count,10);assert(!scene.children.includes(fx.root));assert(scene.children.includes(hero)&&scene.children.includes(boss));arsenal.dispose();});
fs.writeFileSync(path.resolve(here,'../../builds/commander-power-vfx-checks.json'),JSON.stringify({scope:'CPU real Three geometry/source transforms, exact authoritative endpoint adapters, pooling/pause/disposal; rendered appearance and gameplay separately checked',passed,failed,generatedAt:new Date().toISOString()},null,2));if(failed)process.exitCode=1;
