// Independent retained GLB + optional renderer versus the actual compiled C++ helper.
// It validates spatial transforms, not gameplay hit selection or Android rendering.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';import {spawnSync} from 'node:child_process';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
const output=await esbuild.build({entryPoints:[path.join(here,'boss-rig-adapter.ts')],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module('boss-adapter');m.paths=Module._nodeModulePaths(deps);m._compile(output.outputFiles[0].text,path.join(deps,'boss-alignment-inline.cjs'));const {BossRigAdapter}=m.exports;
const bytes=fs.readFileSync(path.join(root,'delivery/playable/forge-tyrant.glb')),len=bytes.readUInt32LE(12),j=JSON.parse(bytes.subarray(20,20+len)),binary=bytes.subarray(28+len);
const nodes=j.nodes.map(n=>{const o=new T.Group();o.name=n.name??'';if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);if(n.mesh!==undefined)for(const p of j.meshes[n.mesh].primitives){const a=j.accessors[p.attributes.POSITION],v=j.bufferViews[a.bufferView],stride=v.byteStride??12,offset=(v.byteOffset??0)+(a.byteOffset??0),values=new Float32Array(a.count*3);for(let i=0;i<a.count;i++)for(let axis=0;axis<3;axis++)values[i*3+axis]=binary.readFloatLE(offset+i*stride+axis*4);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(values,3));g.computeBoundingBox();const mesh=new T.Mesh(g,new T.MeshBasicMaterial());mesh.name='RawGLBGeometry';o.add(mesh);}return o;});for(let i=0;i<nodes.length;i++)for(const c of j.nodes[i].children??[])nodes[i].add(nodes[c]);
const model=new T.Group();model.rotation.y=Math.PI;for(const n of j.scenes[j.scene??0].nodes)model.add(nodes[n]);const boss=new T.Group(),scene=new T.Scene();boss.add(model);scene.add(boss);const adapter=new BossRigAdapter(boss,scene);
const coreMeasured=JSON.parse(fs.readFileSync(path.join(root,'builds/boss-core-luminous-measurement.json'),'utf8'));
const torsoNode=j.nodes.find(n=>n.name==='Torso_MobileMesh'),coreBounds=new T.Box3();let luminousVertices=0;for(const primitive of j.meshes[torsoNode.mesh].primitives){const pa=j.accessors[primitive.attributes.POSITION],pv=j.bufferViews[pa.bufferView],ua=j.accessors[primitive.attributes.TEXCOORD_0],uv=j.bufferViews[ua.bufferView],po=(pv.byteOffset??0)+(pa.byteOffset??0),uo=(uv.byteOffset??0)+(ua.byteOffset??0);for(let i=0;i<pa.count;i++){const u=binary.readFloatLE(uo+i*(uv.byteStride??8)),v=binary.readFloatLE(uo+i*(uv.byteStride??8)+4);if(u>=0&&u<1/3&&v>=0&&v<.5){const point=new T.Vector3(...[0,1,2].map(k=>binary.readFloatLE(po+i*(pv.byteStride??12)+k*4)+(torsoNode.translation?.[k]??0)));coreBounds.expandByPoint(point);luminousVertices++;}}}
assert.equal(luminousVertices,coreMeasured.vertices);assert(coreBounds.getCenter(new T.Vector3()).distanceTo(new T.Vector3(...coreMeasured.localCenter))<1e-12);assert(coreBounds.getSize(new T.Vector3()).multiplyScalar(.5).distanceTo(new T.Vector3(...coreMeasured.localHalf))<1e-12);
const samples=fs.readFileSync(path.join(root,'builds/boss-pose-oracle.txt'),'utf8').trim().split(/\r?\n/);const count=Number(samples[0]);
const run=spawnSync(path.join(root,'builds/boss-pose-tests.exe'),['--dump'],{cwd:root,encoding:'utf8',maxBuffer:8*1024*1024});assert.equal(run.status,0,run.stderr||run.error?.message);const dumped=run.stdout.trim().split(/\r?\n/);assert.equal(Number(dumped[0]),count);assert.equal(dumped.length,1+count*11);
const components=['Barrel_L','Barrel_R','Pod_L','Pod_R','Leg_L','Knee_L','Foot_L','Leg_R','Knee_R','Foot_R','Torso'];let maxPositionError=0,maxOrientationError=0,maxExtentError=0,checked=0;
for(let i=0;i<count;i++){
 const a=samples[1+i*12].split(/\s+/).map(Number);assert.equal(a.length,17);
 const pose={rootX:a[0],rootY:a[1],worldZ:a[2],pitch:a[3],yaw:a[4],roll:a[5],arm:[{pitch:a[6],roll:a[8]},{pitch:a[7],roll:a[9]}],leg:[a[10],a[11]],knee:[a[12],a[13]],barrel:[a[14],a[15]],poseClock:a[16]};assert(adapter.apply(pose));
 for(let c=0;c<11;c++){
  const values=dumped[1+i*11+c].split(/\s+/).map(Number);assert.equal(values[0],i);assert.equal(values[1],c);const native=model.getObjectByName(components[c]),quaternion=native.getWorldQuaternion(new T.Quaternion());let center,half;
  if(c===10){center=native.localToWorld(new T.Vector3(...coreMeasured.localCenter));half=new T.Vector3(...coreMeasured.localHalf).multiplyScalar(1.4);}
  else{const mesh=model.getObjectByName(components[c]+'_MobileMesh').getObjectByName('RawGLBGeometry');center=mesh.geometry.boundingBox.getCenter(new T.Vector3()).applyMatrix4(mesh.matrixWorld);half=mesh.geometry.boundingBox.getSize(new T.Vector3()).multiplyScalar(.7);}
  const cppCenter=new T.Vector3(...values.slice(2,5)),cppQuaternion=new T.Quaternion(...values.slice(5,9)),cppHalf=new T.Vector3(...values.slice(9,12));
  const positionError=center.distanceTo(cppCenter),orientationError=1-Math.abs(quaternion.dot(cppQuaternion)),extentError=half.distanceTo(cppHalf);maxPositionError=Math.max(maxPositionError,positionError);maxOrientationError=Math.max(maxOrientationError,orientationError);maxExtentError=Math.max(maxExtentError,extentError);
  assert(positionError<1e-10,`sample${i}/component${c} position ${positionError}`);assert(Math.abs(orientationError)<1e-12,`sample${i}/component${c} orientation`);assert(extentError<1e-10,`sample${i}/component${c} extent ${extentError}`);checked++;
 }
}
adapter.apply({rootX:0,rootY:0,worldZ:0,pitch:0,yaw:0,roll:0,arm:[{pitch:0,roll:0},{pitch:0,roll:0}],leg:[0,0],knee:[0,0],barrel:[0,0],poseClock:0});assert(model.getObjectByName('Barrel_L').getWorldPosition(new T.Vector3()).x>0);assert(model.getObjectByName('Barrel_R').getWorldPosition(new T.Vector3()).x<0);
adapter.dispose();const receipt={scope:'Actual retained GLB vertices/hierarchy transformed by renderer adapter versus compiled C++ BossPose helper. Spatial alignment only; no independently aimable gameplay/native Android claim.',source:'delivery/playable/forge-tyrant.glb',samples:count,componentTransforms:checked,core:{vertices:luminousVertices,localCenter:coreMeasured.localCenter,localHalf:coreMeasured.localHalf,shape:'measured luminous oval ellipsoid'},maxPositionErrorMetres:maxPositionError,maxOrientationDotError:maxOrientationError,maxExtentErrorMetres:maxExtentError,screenSide:'NativeL is world+X/screen-right at neutral; NativeR screen-left',generatedAt:new Date().toISOString()};fs.writeFileSync(path.join(root,'builds/boss-rig-alignment-checks.json'),JSON.stringify(receipt,null,2));console.log(`PASS ${checked} actual GLB/adapter/C++ transforms across ${count} asymmetric and moving poses; max position error ${maxPositionError}m`);
