// Actual GLB geometry/joint checks on CPU; no claim of WebGL or device validation.
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import Module,{createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),deps=path.resolve(here,'../asset-viewer'),require=createRequire(path.join(deps,'package.json')),T=require('three'),esbuild=require('esbuild');
async function code(file){const build=await esbuild.build({entryPoints:[path.join(here,file)],bundle:true,external:['three'],platform:'node',format:'cjs',nodePaths:[path.join(deps,'node_modules')],write:false});const m=new Module(file);m.paths=Module._nodeModulePaths(deps);m._compile(build.outputFiles[0].text,path.join(deps,'socket-check-inline.cjs'));return m.exports;}
const {WeaponSockets,flightAttitude}=await code('weapon-sockets.ts'),{ArsenalVisuals,syncBossParts}=await code('arsenal-visuals.ts');
function glb(file){const bytes=fs.readFileSync(path.join(root,'delivery/playable',file)),length=bytes.readUInt32LE(12),json=JSON.parse(bytes.subarray(20,20+length)),binary=bytes.subarray(28+length);const nodes=json.nodes.map(n=>{let obj=new T.Object3D();if(n.mesh!==undefined){const primitive=json.meshes[n.mesh].primitives[0],accessor=json.accessors[primitive.attributes.POSITION],view=json.bufferViews[accessor.bufferView],p=new Float32Array(accessor.count*3),stride=view.byteStride??12,offset=(view.byteOffset??0)+(accessor.byteOffset??0);for(let i=0;i<accessor.count;i++)for(let a=0;a<3;a++)p[i*3+a]=binary.readFloatLE(offset+i*stride+a*4);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(p,3));obj=new T.Mesh(geo,new T.MeshStandardMaterial());}obj.name=n.name??'';if(n.translation)obj.position.fromArray(n.translation);if(n.rotation)obj.quaternion.fromArray(n.rotation);if(n.scale)obj.scale.fromArray(n.scale);return obj;});for(let i=0;i<nodes.length;i++)for(const c of json.nodes[i].children??[])nodes[i].add(nodes[c]);const scene=new T.Group();for(const n of json.scenes[json.scene??0].nodes)scene.add(nodes[n]);return scene;}
const boss=new T.Group(),model=glb('forge-tyrant.glb');model.rotation.y=Math.PI;boss.add(model);boss.scale.setScalar(1.4);const sockets=new WeaponSockets(boss),neutral=sockets.positions();let passed=0,failed=0,maxPoseDisplacement=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' — '+e.message);}}
const expected={armL:[1.72480,3.74926,2.09960],armR:[-1.72480,3.74926,2.09960],shoulderL:[1.432465,5.367958,.641911],shoulderR:[-1.432465,5.367958,.641911],core:[0,4.2754723549,1.0154446363]};
test('neutral actual GLB front surfaces match authored immutable launch offsets',()=>{for(const [key,p] of Object.entries(expected))assert.ok(neutral[key].distanceTo(new T.Vector3(...p))<.0002,`${key}: ${neutral[key].toArray()}`);});
test('all sockets are children of their named animated parts',()=>{for(const [key,parent] of Object.entries({armL:'Barrel_L',armR:'Barrel_R',shoulderL:'Pod_L',shoulderR:'Pod_R',core:'Torso',boosterL:'Pod_L',boosterR:'Pod_R'}))assert.equal(sockets.node(key).parent.name,parent);});
test('sampled rotation/translation and arm recoil use exact current world transform',()=>{const origin=new T.Vector3();for(const pitch of [-.18,0,.18])for(const bank of [-.22,0,.22])for(const yaw of [-.32,0,.32])for(const armPitch of [-.20,.30]){boss.position.set(2.3,.85,-9);boss.rotation.set(pitch,yaw,bank);for(const name of ['Arm_L','Arm_R'])model.getObjectByName(name).rotation.x=armPitch;const p=sockets.positions();for(const key of Object.keys(expected)){const node=sockets.node(key);assert.ok(p[key].distanceTo(node.localToWorld(origin.set(0,0,0)))<1e-8);maxPoseDisplacement=Math.max(maxPoseDisplacement,p[key].distanceTo(new T.Vector3(...expected[key]).add(boss.position)));}}});
test('broken barrels/pods and hidden actor cannot keep publishing ghost sources',()=>{syncBossParts(boss,15);const broken=sockets.positions();for(const key of ['armL','armR','shoulderL','shoulderR','boosterL','boosterR'])assert.equal(broken[key],undefined);assert.ok(broken.core);boss.visible=false;assert.deepEqual(sockets.positions(),{});boss.visible=true;syncBossParts(boss,0);assert.equal(Object.keys(sockets.positions()).length,7);});
test('gunner muzzle follows its real GLB gun and rotating root',()=>{const root=new T.Group(),native=glb('cinder-reaver.glb');root.add(native);root.rotation.y=Math.PI;root.position.set(-2,.1,-5);const rig=new WeaponSockets(root,true),before=rig.position('gunner');assert.ok(before&&before.y>.8&&before.y<1.2);root.rotation.y+=.7;const after=rig.position('gunner');assert.ok(before.distanceTo(after)>.3);const n=rig.node('gunner');assert.ok(after.distanceTo(n.localToWorld(new T.Vector3()))<1e-8);rig.dispose();assert.equal(root.getObjectByName('WeaponSocket_gunner'),undefined);});
test('flight attitude banks, brakes and stops thrust when grounded',()=>{assert.ok(flightAttitude(6,8,8,1/60,true).roll<0);assert.ok(flightAttitude(0,0,14.5,1/60,true).pitch<0);assert.equal(flightAttitude(0,0,0,1/60,false).thrust,0);});
const hero=new T.Group(),arsenal=new ArsenalVisuals(hero,boss),base={phase:'boss',timePower:'none',timePowerTime:0,weaponPower:'none',weaponPermanent:false,powerTime:0,shots:[],enemyShots:[],bossPartsMask:0,bossPhase:1,bossPattern:'rockets',bossY:.85,bossAction:'windup',bossAttack:.8,bossHp:2000,bossState:'armored',bossCoreTime:0,relic:0,ability:0,bossX:0,bossZ:12};
test('charge lights only corresponding surviving weapon or explicit fallback core',()=>{arsenal.update(base,1/60);assert.equal(boss.getObjectByName('SocketCharge_armL').visible,false);assert.equal(boss.getObjectByName('SocketCharge_shoulderL').visible,true);assert.equal(boss.getObjectByName('SocketCharge_core').visible,false);arsenal.update({...base,bossPartsMask:15,bossPattern:'sweep'},1/60);assert.equal(boss.getObjectByName('SocketCharge_core').visible,true);assert.equal(boss.getObjectByName('SocketCharge_armL').visible,false);});
test('only actual launch source flashes and absent boosters emit no flame',()=>{arsenal.update({...base,bossAction:'fire',enemyShots:[{id:7,emitter:'shoulderR'}]},1/60);assert.equal(boss.getObjectByName('SocketFlash_shoulderR').visible,true);assert.equal(boss.getObjectByName('SocketFlash_armL').visible,false);arsenal.update({...base,bossPartsMask:12},1/60);for(const side of ['L','R']){const group=boss.getObjectByName('OriginalBoosterExhaust_booster'+side);assert.equal(group.parent.parent.visible,false);}});
test('actual evasion publishes stronger attached tell/dash jets, pauses exactly, and never moves the rig',()=>{
 arsenal.reset();syncBossParts(boss,0);boss.position.set(0,1.2,-12);boss.rotation.set(.10,.12,-.08);arsenal.update({...base,bossAction:'strafe',bossY:1.2},1/60);
 const jets=()=>['L','R'].flatMap(side=>boss.getObjectByName('OriginalBoosterExhaust_booster'+side).children.filter(n=>n.name.startsWith('BoosterPlasmaStage'))),sum=()=>jets().reduce((s,p)=>s+p.scale.y,0),idle=sum();
 const rootPose=[...boss.position.toArray(),...boss.quaternion.toArray()];arsenal.update({...base,bossAction:'evade',bossEvadeTime:1.2,bossEvadeTell:.35,bossY:1.2},1/60);assert(sum()>idle);assert.deepEqual([...boss.position.toArray(),...boss.quaternion.toArray()],rootPose);
 boss.position.x=.075;const moved=[...boss.position.toArray(),...boss.quaternion.toArray()];const state={...base,bossAction:'evade',bossEvadeTime:.8,bossEvadeTell:0,bossY:1.2};arsenal.update(state,1/60);const dash=sum();assert(dash>idle*1.10);assert(jets().every(p=>p.visible));assert.deepEqual([...boss.position.toArray(),...boss.quaternion.toArray()],moved);
 const frozen=jets().map(p=>p.scale.toArray());for(let i=0;i<20;i++)arsenal.update(state,0);assert.deepEqual(jets().map(p=>p.scale.toArray()),frozen);
 arsenal.update({...state,bossAction:'strafe',bossEvadeTime:0,bossFiringWindow:1.4},1/60);assert(sum()<dash);arsenal.update({...state,bossPartsMask:12},1/60);assert(jets().every(p=>!p.visible));syncBossParts(boss,0);arsenal.reset();
});
test('reset clears charge and retained flash state without duplicating sockets',()=>{const count=()=>{let n=0;boss.traverse(o=>{if(o.name.startsWith('SocketFlash_'))n++;});return n;};const before=count();for(let i=0;i<50;i++){arsenal.update(base,1/60);arsenal.reset();}assert.equal(count(),before);assert.equal(boss.getObjectByName('SocketCharge_core').visible,false);assert.equal(boss.getObjectByName('SocketFlash_shoulderR').visible,false);});
arsenal.dispose();sockets.dispose();
const receipt={scope:'CPU actual GLB position/joint verification; browser render and Android not tested here.',testedAt:new Date().toISOString(),passed,failed,maxSampledPoseDisplacementMetres:maxPoseDisplacement,tests:passed+failed,neutralOffsets:expected};fs.writeFileSync(path.join(root,'builds/weapon-socket-checks.json'),JSON.stringify(receipt,null,2));console.log(`${passed}/${passed+failed} passed; max sampled neutral/posed displacement ${maxPoseDisplacement.toFixed(3)}m`);if(failed)process.exitCode=1;
